### ISSUE TITLE
[Python] Inheritance doesn't work 

### ISSUE THREAD

**Issue by emreakca** [OpenAPITools/openapi-generator#623] opened 2018-07-23 09:26 UTC
##### Description

The generated Python SubClass doesn't inherited from the BaseClass, when allOf is used.
```yaml
SubClass:
  allOf:
    - $ref: '#/components/schemas/BaseClass'
```

The generated class shows
```python
class SubClass(object):
```
instead of
```python
class SubClass(BaseClass):
```
This issue was already posted (#453), but it's not solved nor answered. 
##### openapi-generator version

3.1.1

##### Command line used for generation

```
java -jar ~/openapi-generator-cli-3.1.1.jar generate -g python -i openapi.json -o generated/python-client
```
##### Suggestion
Either do the inheritance correctly (as shown at the beginning), with the right constructors (```__init__```) 
or add the Properties of the BaseClass to the SubClass, as in swagger 2.

**Comment by macjohnny** [comment] 2018-07-23 10:17
@emreakca @poli-granot this could be fixed by applying the changes in https://github.com/swagger-api/swagger-codegen/commit/843c638c2a86926f201d006daeb2e8c5028d6cfb to https://github.com/OpenAPITools/openapi-generator/blob/master/modules/openapi-generator/src/main/resources/python/model.mustache#L13 and other relevant files. would you like to file a PR for this?

**Comment by spacether** [comment] 2019-01-23 17:21
I am working on a PR which will fix this issue. The problem is that the mustache files iterate through #vars. #vars does not include the variables inherited from the allOf class. However, the requiredVars and optionalVars DO include those needed properties. My fix will iterate over the requiredVars and optionalVars.

**Comment by spacether** [comment] 2020-05-30 08:00
Inheritance is working in python-experimental
Composed schema inheritance is implemented by storing instances of "ancestor" allOf models rather than using inherited classes.
This was done because multiple allOf models can contain the same property with differing enum and validation constraints on it.
Python class based inheritance generally assumes that a property has its definition/validation in one source of truth class location.

**Closed by spacether** 2020-05-30 08:00 UTC
