### ISSUE TITLE
[BUG] [GO] can't generate codes with xml tag

### ISSUE THREAD

**Issue by gold-kou** [OpenAPITools/openapi-generator#4733] opened 2019-12-09 09:49 UTC
#### Bug Report Checklist

- [x] Have you provided a full/minimal spec to reproduce the issue?
- [x] Have you validated the input using an OpenAPI validator ([example](https://apidevtools.org/swagger-parser/online/))?
- [x] What's the version of OpenAPI Generator used?
- [x] Have you search for related issues/PRs?
- [x] What's the actual output vs expected output?
- [] [Optional] Bounty to sponsor the fix ([example](https://www.bountysource.com/issues/66123212-javascript-client-produces-a-wrong-object-for-a-string-enum-type-that-is-used-with-ref))

##### Description
even though i use `withXml=true`, can't generate codes with xml tag .

actual:

```
type ResponseSample struct {

	StatusCode int64 `json:"status_code"`

	Message string `json:"message"`
}
```

expected(like this):

```
type ResponseSample struct {

        XMLName xml.Name `xml:"response"`

	StatusCode int64 `xml:"status_code"`

	Message string `xml:"message"`
}
```

My Go version: 
go version go1.12.13 darwin/amd64

##### openapi-generator version
v4.1.2

##### OpenAPI declaration file content or url
```yaml
ResponseSample:
      type: object
      properties:
        status_code:
          type: integer
          format: int64
          example: 0
        message:
          type: string
          example: 'success'
      xml:
        name: response
      required:
        - status_code
        - message
```

##### Command line used for generation
```
docker run -v ${PWD}:/local openapitools/openapi-generator-cli:v4.1.2 generate \
  -i /local/openapi/openapi.yaml \
  -g go-server \
  -p withXml=true \
  --output /local/${GENERATE_PATH}
```

##### Steps to reproduce
please paste the above yaml, then docker run.

##### Related issues/PRs
https://github.com/OpenAPITools/openapi-generator/issues/490

**Comment by wing328** [comment] 2019-12-12 08:38
>   -p withXml=true \

Don't think this will work.

Can you try `--additional-properties withXml=true` instead?

I can confirm the templates still use `withXml`

> modules/openapi-generator/src/main/resources/go/model.mustache:38:	{{name}} {{#isNullable}}*{{/isNullable}}{{{dataType}}} `json:"{{baseName}}{{^required}},omitempty{{/required}}"{{#withXml}} xml:"{{baseName}}{{#isXmlAttribute}},attr{{/isXmlAttribute}}"{{/withXml}}{{#vendorExtensions.x-go-custom-tag}} {{{.}}}{{/vendorExtensions.x-go-custom-tag}}`

**Comment by gold-kou** [comment] 2019-12-12 10:21
@wing328 
Thanks for your reply.

Although tried `--additional-properties withXml=true`, json tag still remains 🤔 

```
type ResponseSample struct {

	StatusCode int64 `json:"status_code"`

	Message string `json:"message"`
}
```

BTW, the reason why i used `-p` is what i got the below message when used `-D`.

```
[DEPRECATED] -D arguments after 'generate' are application arguments and not Java System Properties, please consider changing to -p, or apply your options to JAVA_OPTS, or move the -D arguments before the jar option.
```

**Comment by wing328** [comment] 2019-12-12 10:46
```
# if you've executed sbt assembly previously it will use that instead.
export JAVA_OPTS="${JAVA_OPTS} -Xmx1024M -DloggerPath=conf/log4j.properties"
ags="generate -t modules/openapi-generator/src/main/resources/go -i $SPEC -g $GENERATOR -o $STUB_DIR --additional-properties packageName=petstore,withXml=true,withGoCodegenComment=true $@"
```
That's what we use in the Go Petstore (xml) shell script so it looks to me the following is correct:
` --additional-properties withXml=true`

**Comment by wing328** [comment] 2019-12-12 10:50
Just did a test with the following and it works for me:
```
java -jar modules/openapi-generator-cli/target/openapi-generator-cli.jar generate -i https://raw.githubusercontent.com/OpenAPITools/openapi-generator/master/modules/openapi-generator/src/test/resources/2_0/petstore.yaml -o /tmp/go_xml/ --additional-properties withXml=true -g go
```
and here is the Pet model:
```
package openapi
// Pet A pet for sale in the pet store
type Pet struct {
    Id int64 `json:"id,omitempty" xml:"id"`
    Category Category `json:"category,omitempty" xml:"category"`
    Name string `json:"name" xml:"name"`
    PhotoUrls []string `json:"photoUrls" xml:"photoUrls"`
    Tags []Tag `json:"tags,omitempty" xml:"tags"`
    // pet status in the store
    Status string `json:"status,omitempty" xml:"status"`
}
```

Can you try the latest stable docker image instead?

**Comment by wing328** [comment] 2019-12-13 09:20
If it's still an issue, please ping me via Slack.

Closing this for the time being.

**Closed by wing328** 2019-12-13 09:20 UTC
Labels: Issue: Bug, Server: Go
