### ISSUE TITLE
[BUG] Java generated code compilation failure

### ISSUE THREAD

**Issue by rgala** [OpenAPITools/openapi-generator#3293] opened 2019-07-08 05:32 UTC
When model name contains single digit or digits only, for example "1", it will generate Model1.java class with the following equals method:

```
@Override
public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    Model1 1 = (Model1) o;
    return Objects.equals(this.error, 1.error);
  }
```

The compilation of 
`Model1 1 = (Model1) o;`

fails because the java variable name cannot start with digits. It should be escaped like it happens for model names starting with digits and having letters too, for example 5abff9bf gets renamed to _5abff9bf.

The 

`if (name.matches("^[A-Z0-9_]*$")) {` regex in AbstractJavaCodegen class should not match digits only names.

**Comment by pe-st** [comment] 2019-07-21 16:03
This bug bit me too, it's a regression and I was astonished when I could generate my code with 4.0.0-beta3 but not anymore with 4.0.0.

I tracked it down to have been introduced by the PR https://github.com/OpenAPITools/openapi-generator/pull/2794

Either the regex that @rgala mentions should match digits only after the first position (e.g. `^[A-Z_][A-Z0-9_]*$`) or the condition checking for a word starting with a number should be applied before it.

I have reproduced it here: https://github.com/pe-st/openapi-generator/tree/properties_digits ; if you want I can try to fix it and create a PR

**Comment by Fjolnir-Dvorak** [comment] 2019-07-24 10:02
I'm am currently writing a pull request. What bothers me about this issue. It did work in the past. Why and when was this destroyed or was it not intended?

**Comment by pe-st** [comment] 2019-07-24 16:28
> I'm am currently writing a pull request. What bothers me about this issue. It did work in the past. Why and when was this destroyed or was it not intended?

It was destroyed when the PR #2794 was merged, see my comment above. But I don't think that the regression was intended, there was just no unit test there yet with leading digits...

**Closed** 2019-07-25 05:38 UTC
Labels: Client: Java, Issue: Bug, Server: Java
