### ISSUE TITLE
[BUG] [Python] client - response fails to deserialize due to incorrect type for field in model code

### ISSUE THREAD

**Issue by SteveHespelt** [OpenAPITools/openapi-generator#8227] opened 2020-12-17 22:27 UTC
#### Bug Report Checklist

- [x] Have you provided a full/minimal spec to reproduce the issue?
- [x] Have you validated the input using an OpenAPI validator ([example](https://apidevtools.org/swagger-parser/online/))?
- [x] Have you [tested with the latest master](https://github.com/OpenAPITools/openapi-generator/wiki/FAQ#how-to-test-with-the-latest-master-of-openapi-generator) to confirm the issue still exists?
- [X] Have you searched for related issues/PRs?
- [x] What's the actual output vs expected output?
- [ ] [Optional] Sponsorship to speed up the bug fix or feature request ([example](https://github.com/OpenAPITools/openapi-generator/issues/6178))

##### Description

The generated model code for type Elements for the response schema uses a type 'object' which causes an ApiValueError exception to be raised when the model_utils.py deserialize_model() is invoked - object is not a supported type. I was expecting that for a freeform property of type object in the spec would result in a dict type being used.

I would expect a model/element.py to be generated (based on the schema) and for the Elements.openapi_types method to return a dictionary using 'elements' : ([Element],)  
rather than the generated code:
```python
        return {
            'elements': ([object],),  # noqa: E501
            'comment': (str,),  # noqa: E501
            'source': (str,),  # noqa: E501
        }
```
 

##### openapi-generator version

5.0.0-beta3, api-latest-master.openapi-generator.tech

##### OpenAPI declaration file content or url
a complete but minimal spec available here:  [minimal-spec.txt](https://github.com/OpenAPITools/openapi-generator/files/5712404/minimal-spec.txt)

##### Generation Details

openapi-generator-cli generate -g python -o ./client  -i minimal-spec.yaml  
also used the online generator at api-latest-master.openapi-generator.tech to try with a SNAPSHOT deployment of master

##### Steps to reproduce

Of some potential interest, if I submit the same spec to the online swagger generator generator3.swagger.io, the generated code includes the expected Element type and elements.py makes use of it in the swagger_types dictionary.

**Comment by SteveHespelt** [comment] 2020-12-18 16:31
If I remove the use of the ELement type in the Elements model (ie.
```yaml
    Elements:
      type: "object"
      required:
        - "elements"
      properties:
        elements:
          type: "array"
          items:
            type: object  <- No more use of the type Element
            #$ref: "#/components/schemas/Element"
        comment:
          type: "string"
        source:
          type: "string"
```
The python client generated code's model/elements.py now has openapi_types returning dictionary 
```python
        return {
            'elements': ([{str: (bool, date, datetime, dict, float, int, list, str, none_type)}],),  # noqa: E501
            'comment': (str,),  # noqa: E501
            'source': (str,),  # noqa: E501
        }
```
which is as one would expect.  
Using python-flask as the generator value, the server code's models/elements.py Elements.__init__ uses an openapi_types dictionary: 
```python
        self.openapi_types = {
            'elements': List[object],  # <- a 'bit' different from that used by the python client code.
            'comment': str,
            'source': str
        }

```
Hopefully this helps?

**Comment by spacether** [comment] 2021-01-15 22:11
Can you provide your full input spec?
You have left out the Element definition and the endpoint definition that uses it.

**Comment by spacether** [comment] 2021-01-15 22:17
Our sample spec includes a similar-to example in the Pet model.
Pet.tag definition: https://github.com/OpenAPITools/openapi-generator/blob/master/modules/openapi-generator/src/test/resources/3_0/python/petstore-with-fake-endpoints-models-for-testing-with-http-signature.yaml#L1500
```
        tags:
          type: array
          items:
            $ref: '#/components/schemas/Tag'
```


Generated model:
https://github.com/OpenAPITools/openapi-generator/blob/master/samples/openapi3/client/petstore/python/petstore_api/model/pet.py#L93
Please see Pet.tags defined as `([Tag],)` which is an array of Tag
```
    def openapi_types():
        """
        This must be a method because a model may have properties that are
        of type self, this must run after the class is loaded
        Returns
            openapi_types (dict): The key is attribute name
                and the value is attribute type.
        """
        lazy_import()
        return {
            'name': (str,),  # noqa: E501
            'photo_urls': ([str],),  # noqa: E501
            'id': (int,),  # noqa: E501
            'category': (Category,),  # noqa: E501
            'tags': ([Tag],),  # noqa: E501
            'status': (str,),  # noqa: E501
        }
```

**Comment by spacether** [comment] 2021-01-15 22:19
This is happening because your Element class is a vanilla object definition so no model is created for it. It is the same as a dictionary that accepts any values. If you need your model to be defined, please add any optional property to it and your model will be generated and the types will be defined correctly.

**Comment by spacether** [comment] 2021-01-15 22:21
One way to fix this may be to add `typeMapping.put("object", "dict");` into PythonCLientCodegen.java
I welcome any PRs adding this.

**Comment by spacether** [comment] 2021-02-05 17:55
Trying this with the latest 5.0.1 release I see these types being generated with the python denerator:
```
    @cached_property
    def openapi_types():
        """
        This must be a method because a model may have properties that are
        of type self, this must run after the class is loaded

        Returns
            openapi_types (dict): The key is attribute name
                and the value is attribute type.
        """
        lazy_import()
        return {
            'elements': ([Element],),  # noqa: E501
            'comment': (str,),  # noqa: E501
            'source': (str,),  # noqa: E501
        }
```
So it looks like this is working

**Comment by spacether** [comment] 2021-02-05 19:21
@SteveHespelt
I'm having trouble understanding what you want here.
- Do you want elements to be a list of dicts containing values of any type?
- Do you want elements to be a list of Element?
- Do you want elements to be a list containing values of any type?

**Comment by spacether** [comment] 2021-03-29 17:16
Closing this issue because it is unreproducible. Per tests in https://github.com/OpenAPITools/openapi-generator/issues/8227#issuecomment-774189117 the type generation here is correct.

**Closed by spacether** 2021-03-29 17:16 UTC
Labels: Client: Python, Issue: Bug
