### ISSUE TITLE
[BUG] No more inheritance for components generated by version 5.0.0

### ISSUE THREAD

**Issue by antonio-petricca** [OpenAPITools/openapi-generator#8495] opened 2021-01-21 08:25 UTC
##### Description

No schema inheritance.

##### openapi-generator version

5.0.0

##### OpenAPI declaration file content or url

```yaml
schemas:
  UserDTO:
      type: object
      properties:
        id:
          type: string
          minLength: 1
          maxLength: 20

  QueryUserResponseDTO:
      type: object
      allOf:
        - $ref: '#/components/schemas/UserDTO'
```

##### Generation Details

The above YAML produces:

```java
public class QueryUserResponseDTO   {
   private @Valid String id;
}
```

Instead as for the 4.3.1:

```java
public class QueryUserResponseDTO extends UserDTO   {
}
```

##### Suggest a fix

Does exist a configuration parameter to enforce the DTO inheritance generation? Or it is a bug?

**Comment by Msurrow** [comment] 2021-01-22 09:46
Just to confirm. I updated from 4.3.1 -> 5.0.0 and I'm seeing the same issue (with dotnet-core generator) and AllOf inheritance. 
For us, this makes vers 5.0.0 unusable.

**Comment by antonio-petricca** [comment] 2021-01-25 08:03
I am going to revert to 4.3.1. :(

**Comment by Msurrow** [comment] 2021-01-25 08:34
@antonio-petricca  I'm getting this from the log when running the generator: 

```bash
[main] INFO  o.o.codegen.utils.ModelUtils - [deprecated] inheritance without use of 'discriminator.propertyName' has been deprecated in the 5.x release. Composed schema name: null. Title: null
[main] INFO  o.o.codegen.utils.ModelUtils - [deprecated] inheritance without use of 'discriminator.propertyName' has been deprecated in the 5.x release. Composed schema name: null. Title: null
```

I havn't had time to dive into it fully yet (we've reverted to 4.3.1 for now) but from what I can gather it seems that my swagger.json doesnt have the discriminator field on the supertype. However I'm using asp.net swashbuckle to generate the swagger.json/.yaml which is setup to OAS3. So what I havn't figured out yet is if the problem really is the yaml not being generated correctly by swashbuckle (i.e. missing the discriminator field). I cant seem to get it to generate the discriminator field. (yet - working on it when I have time)

**Comment by felschr** [comment] 2021-01-27 13:19
This happened to me after upgrading from `5.0.0-beta3` to `5.0.0`.
Our openapi schema hasn't changed.

**Comment by adsanche** [comment] 2021-02-10 11:36
I have the same problem from 5.x.x.

Actually, the following warning doesn't make sense :
`[INFO] [deprecated] inheritance without use of 'discriminator.propertyName' has been deprecated in the 5.x release. Composed schema name: null. Title: null`

As I have a propertyName placed on the discriminator on the parent object :

```
DeliveryDateApi:
      description: 'Delivery date information.'
      oneOf:
        - $ref: '#/components/schemas/RangeDeliveryDateApi'
        - $ref: '#/components/schemas/FixedDeliveryDateApi'
      discriminator:
        propertyName: type
        mapping:
          RANGE: '#/components/schemas/RangeDeliveryDateApi'
          FIXED: '#/components/schemas/FixedDeliveryDateApi'
      required: 
        - type
```

Are there any updated on this that could avoid rollbacking to 4.3.1?

**Comment by antonio-petricca** [comment] 2021-02-11 10:23
I reverted to 4.3.1.

**Comment by tamershahin** [comment] 2021-02-11 12:44
I have the same problems with kotlin-spring generator. 
is this independent from the generator?

**Comment by Blackclaws** [comment] 2021-03-12 07:17
This might be a bug in how ambiguousness of inheritance is being determined. I'm on it

**Comment by tamershahin** [comment] 2021-03-12 07:36
> This might be a bug in how ambiguousness of inheritance is being determined. I'm on it

I don't know if it's related to this bug, but I documented what worked for me here:
https://github.com/OpenAPITools/openapi-generator/issues/8687

**Comment by Blackclaws** [comment] 2021-03-12 08:39
So right now the issue is the following: 

The spec itself says that allOf by itself does not imply a hierarchic relationship between the components. Therefore even if there is only a single reference in allOf this means that generating an inheritance relationship between them is not per se wrong (as the spec does not forbid it) but it also goes further than the spec and infers something that some people might not want to have.

I've opened an issue on the OpenAPI Spec itself to maybe get some clarification into the spec as to whether treating a single allOf ref as inheritance might make sense. 

For now the solution is to simply add a discriminator property to the base object in order to get inheritance.

**Comment by Msurrow** [comment] 2021-03-12 09:16
> For now the solution is to simply add a discriminator property to the base object in order to get inheritance.
@Blackclaws 
Its some time since I've looked at this, but for me part of the problem is that the spec generated by Swashbuckle doesn't include a discriminator on the base object.

You can see a code example in my post above, and a snippet of the generated spec is shown below. Perhaps this is the wrong place for this question (but mentioned discriminators), but am I doing something wrong here? 

´´´
      "Product": {
        "type": "object",
        "properties": {
          "productId": {
            "type": "integer",
            "format": "int32"
          },
          "debtors": {
            "type": "array",
            "items": {
              "$ref": "#/components/schemas/Debtor"
            },
            "nullable": true
          },
          "collaterals": {
            "type": "array",
            "items": {
              "$ref": "#/components/schemas/Collateral"
            },
            "nullable": true
          }
        },
        "additionalProperties": false
      },
      "ProductBankLoan": {
        "type": "object",
        "allOf": [
          {
            "$ref": "#/components/schemas/Product"
          }
        ],
        "properties": {
          "balance": {
            "type": "number",
            "format": "double"
          }
        },
        "additionalProperties": false
      }
´´´

This is using the configuraton:
´´´
Services.AddSwaggerGen(c =>
            {
                // Add discrimitators to swagger generator to handle inheritance types e.g. Product
                c.UseAllOfForInheritance();
              
                c.SwaggerDoc("v1", new OpenApiInfo { Title = "NECSApi", Version = "v1" });
            });
´´´

**Comment by Blackclaws** [comment] 2021-03-12 10:04
You need to actually add a discriminator to your base class and then add the annotation [SwaggerDiscriminator("discriminatorPropertyName")] as well. That has worked for me.

**Comment by marabunta62** [comment] 2021-05-26 20:11
> I am going to revert to 4.3.1. :(

I should do the same.
Impossible to generate with 5.X.X "com.fasterxml.jackson.core.JsonParseException: Unrecognized token 'openapi': was expecting .... truncated XXX chars"
Inspect with cli validate my spec bring me here

**Comment by Blackclaws** [comment] 2021-05-26 20:21
The problem is that the behavior of adding inheritance to schema composition by allOf without a discriminator was actually non-compliant regarding the spec. 

If you add a discriminator everything should work as expected. See also the linked issue in the spec repository. If you want this sort of behavior then please go ahead an lobby for general code generation hints as part of the spec.

**Comment by valkum** [comment] 2021-06-02 13:58
We hit the same issue with model composition as described here: https://swagger.io/docs/specification/data-models/inheritance-and-polymorphism/

**Comment by rgoers** [comment] 2021-06-26 18:49
The problem is that the base class can't always know all the classes that will extend it. In my case, #9756 it isn't even necessary as the base class isn't used for Serialization/Deserialization. But I need the base class for methods that operate on the fields it provides. In my environment we have a "BasePage" object for paged requests. All the services that need paging extend that. BasePage can't possibly know all the services that will support paging as it is in a common library that the services import. This change has made it impossible to support this.

**Comment by wing328** [comment] 2022-12-20 17:07
Hi all, I've filed https://github.com/OpenAPITools/openapi-generator/pull/14172 to allow using $ref as parent in allOf with a new option called "openapi-normalizer".

Please give it a try as follows:
```
git clone --depth 1 -b allof-parent-type https://github.com/OpenAPITools/openapi-generator/
cd openapi-generator
mvn clean package -DskipTests -Dmaven.javadoc.skip=true
java -jar modules/openapi-generator-cli/target/openapi-generator-cli.jar generate -g java -i /Users/williamcheng/Code/openapi-generator7/modules/openapi-generator/src/test/resources/3_0/allOf_extension_parent.yaml -o /tmp/java-okhttp/ --additional-properties hideGenerationTimestamp="true" --openapi-normalizer REF_AS_PARENT_IN_ALLOF=true
```

**Comment by endreszilagyi1** [comment] 2023-01-16 10:57
Hi @wing328,

we tried it out with your suggestion, however didn't worked.
We are getting the following error:
Exception in thread "main" java.lang.NullPointerException: Cannot invoke "java.util.List.iterator()" because the return value of "io.swagger.v3.oas.models.media.Schema.getAllOf()" is null
        at org.openapitools.codegen.OpenAPINormalizer.normalizeOneOf(OpenAPINormalizer.java:328)
        at org.openapitools.codegen.OpenAPINormalizer.normalizeSchema(OpenAPINormalizer.java:276)
        at org.openapitools.codegen.OpenAPINormalizer.normalizeContent(OpenAPINormalizer.java:154)
        at org.openapitools.codegen.OpenAPINormalizer.normalizeRequestBody(OpenAPINormalizer.java:180)
        at org.openapitools.codegen.OpenAPINormalizer.normalizePaths(OpenAPINormalizer.java:130)
        at org.openapitools.codegen.OpenAPINormalizer.normalize(OpenAPINormalizer.java:101)
        at org.openapitools.codegen.DefaultGenerator.configureGeneratorProperties(DefaultGenerator.java:261)
        at org.openapitools.codegen.DefaultGenerator.generate(DefaultGenerator.java:907)
        at org.openapitools.codegen.cmd.Generate.execute(Generate.java:473)
        at org.openapitools.codegen.cmd.OpenApiGeneratorCommand.run(OpenApiGeneratorCommand.java:32)
        at org.openapitools.codegen.OpenAPIGenerator.main(OpenAPIGenerator.java:66)

This is the command I'm using:
java -jar modules/openapi-generator-cli/target/openapi-generator-cli.jar generate -g java -i swagger.json -o .\generated --additional-properties hideGenerationTimestamp="true" --openapi-normalizer REF_AS_PARENT_IN_ALLOF=true

When executing the same command but without --openapi-normalizer REF_AS_PARENT_IN_ALLOF=true works fine.
Could you please check if we are doing something wrong or it is a bug?

I'm using windws 10 with JDK 19 x64 and maven 3.8.7.

Thank in advance for you help.

**Comment by wing328** [comment] 2023-03-23 13:30
can you share the spec to repeat the issue? hard to troubleshoot without the spec.

**Comment by wing328** [comment] 2023-04-15 07:19
closing this as https://github.com/OpenAPITools/openapi-generator/pull/14172 has been merged.

please use https://github.com/OpenAPITools/openapi-generator/blob/master/docs/customization.md#openapi-normalizer moving forward.

**Closed by wing328** 2023-04-15 07:19 UTC
Labels: Issue: Bug

**Comment by wing328** [comment] 2023-04-15 08:08
@endreszilagyi1 I've merged https://github.com/OpenAPITools/openapi-generator/pull/15224 with better null check. Hopefully that should address the issue you reported.
