### ISSUE TITLE
[BUG] Default Content Type for StringContent is "text/plain" not JSON in new library=generichost

### ISSUE THREAD

**Issue by ikill69** [OpenAPITools/openapi-generator#13505] opened 2022-09-23 02:31 UTC
#### Bug Report Checklist

- [ ] Have you provided a full/minimal spec to reproduce the issue?
- [ ] Have you validated the input using an OpenAPI validator ([example](https://apidevtools.org/swagger-parser/online/))?
- [ ] Have you [tested with the latest master](https://github.com/OpenAPITools/openapi-generator/wiki/FAQ#how-to-test-with-the-latest-master-of-openapi-generator) to confirm the issue still exists?
- [ ] Have you searched for related issues/PRs?
- [ ] What's the actual output vs expected output?
- [ ] [Optional] Sponsorship to speed up the bug fix or feature request ([example](https://github.com/OpenAPITools/openapi-generator/issues/6178))

##### Description

I think there may be an issue in the "AddxxxxWithHttpInfoAsync" methods. 

From what I can tell the issue is that when using "StringContent()" class the default content type is always  "{text/plain; charset=utf-8}"

This then cause an exception to be thrown back from the server.

![image](https://user-images.githubusercontent.com/49211294/191879856-81024d32-ecc0-48f8-b59a-23f16fa20c52.png)

```
{
  "httpStatus" : 415,
  "message" : "Unsupported content type",
  "developerMessage" : "A request was made of a resource using a request method not supported by that resource - Content type 'text/plain;charset=utf-8' not supported",
  "code" : 71
}
```

I also can not find a working example of the content type header being added like this **"ContentType"**
![image](https://user-images.githubusercontent.com/49211294/191881771-ea7c4464-02d7-46f6-9559-d97a7e6885a6.png)

Normal it looks like this **"Content-Type"**

![image](https://user-images.githubusercontent.com/49211294/191881826-e361f2bb-abe2-459c-9762-cb63813a1e90.png)

 

##### openapi-generator version

`docker run --rm -v C:\Dev\OpenAPI_CodeGen:/local openapitools/openapi-generator-cli:v6.1.0 generate -i /local/My_swagger.json -g csharp-netcore -o /local/csharp/OpenApi --skip-validate-spec --additional-properties=netCoreProjectFile=true,targetFramework=net6.0,packageName=MyClient.SDK --library=generichost`

##### Steps to reproduce
`
docker run --rm -v C:\Dev\OpenAPI_CodeGen:/local openapitools/openapi-generator-cli:v6.1.0 generate -i /local/My_swagger.json -g csharp-netcore -o /local/csharp/OpenApi --skip-validate-spec --additional-properties=netCoreProjectFile=true,targetFramework=net6.0,packageName=MyClient.SDK --library=generichost
`

##### Suggest a fix

One fix/work-around that I have found to this is to set the actual default content type in the constructor.

![image](https://user-images.githubusercontent.com/49211294/191879915-d3ce4803-ebc3-4fc1-a57c-3488a1fe95d5.png)

Or better still. 
![image](https://user-images.githubusercontent.com/49211294/191883304-36aa0f2e-f856-48db-996b-556fcff300bf.png)

I am not sure if this is the exact right solution, but it works.

Another fix might be that lower down in the code where the correct content type is added, we have a check to see if one already exists first and edit/remove it.  But this breaks away with what the other generator libraries are doing in this area like "restsharp".

![image](https://user-images.githubusercontent.com/49211294/191881052-033c47b2-a70b-4069-bb23-6f8a3cf45097.png)

**Comment by ikill69** [comment] 2022-10-18 23:32
Hi @wing328 

Has this maybe gone in a queue some where? 

cc: @devhl-labs

**Comment by kYann** [comment] 2023-01-26 20:19
Hello,

Is this fix merged ?

Thanks,

**Comment by devhl-labs** [comment] 2023-01-26 20:58
Yes, content type is added like this now `request.Content.Headers.ContentType = new MediaTypeHeaderValue` which should resolve the issue. You can clone this repo, or wait for the next release which I think is coming soon, but I don't know when.

**Comment by kYann** [comment] 2023-01-27 08:41
Ok good to know, thank you !

**Comment by kYann** [comment] 2023-01-27 16:52
I've tried the latest 6.3.0 (openapi-generator-cli-6.3.0-20230125.125049-89). And there is some compilation error :/

```csharp
// Error	CS1615	Argument 1 may not be passed with the 'ref' keyword
date = JsonSerializer.Deserialize<DateTime>(ref reader, options);
```

**Comment by devhl-labs** [comment] 2023-01-28 01:39
That is a different issue, and one that I do not see. It may just be a stale file that you need to delete. If not, please start a new issue and provide a minimal spec so I can reproduce it.
![image](https://user-images.githubusercontent.com/29644329/215234946-a603aa7e-447b-4ef7-b141-591c9d8d48a9.png)

**Comment by kYann** [comment] 2023-01-28 16:49
This was due to a parameter in my project where we transform null warning to error. Sorry.
I've found another issue with nullable Guid. i'm opening an issue.

**Comment by kYann** [comment] 2023-01-28 17:14
There is a naming config, that was the real issue. here is the opened issue : https://github.com/OpenAPITools/openapi-generator/issues/14553

**Comment by ikill69** [comment] 2023-01-30 01:44
> Yes, content type is added like this now request.Content.Headers.ContentType = new MediaTypeHeaderValue(contentType); which should resolve the issue. You can clone this repo, or wait for the next release which I think is coming soon, but I don't know when.

Hi @devhl-labs 

Could you please send a link to the exact file/branch where you have changed this? 
I would like to see it and search is not bringing it up.

Thanks

**Comment by devhl-labs** [comment] 2023-01-30 02:13
https://github.com/OpenAPITools/openapi-generator/blob/b538c2adf8f65d27f0bce6a2dcb0553760998a9e/modules/openapi-generator/src/main/resources/csharp-netcore/libraries/generichost/api.mustache#L415

Adding the header with the wrong key should be fixed. Let me know if it's still using the wrong value.

**Closed** 2023-11-13 02:15 UTC
Labels: Issue: Bug
