### ISSUE TITLE
[BUG] [Dart] json_serializable Multipart generator broken

### ISSUE THREAD

**Issue by JustFrederik** [OpenAPITools/openapi-generator#15235] opened 2023-04-16 18:15 UTC
#### Bug Report Checklist

- [X] Have you provided a full/minimal spec to reproduce the issue?
- [X] Have you validated the input using an OpenAPI validator ([example](https://apidevtools.org/swagger-parser/online/))?
- [X] Have you [tested with the latest master](https://github.com/OpenAPITools/openapi-generator/wiki/FAQ#how-to-test-with-the-latest-master-of-openapi-generator) to confirm the issue still exists?
- [X] Have you searched for related issues/PRs?
- [ ] What's the actual output vs expected output?
- [ ] [Optional] Sponsorship to speed up the bug fix or feature request ([example](https://github.com/OpenAPITools/openapi-generator/issues/6178))

##### Description
After generating there are still errors where `includeIfNull: truefalse`. This only occurs for multipart queries.

An example would be 
```
 @JsonKey(
    
    name: r'tags',
    required: true,
    includeIfNull: truefalse
  )
```

After fixing that code the project compiles but the request isnt working. To be more specific the body for the multipart isnt attached. The request is empty(no payload).

This is the call in dart: 
```
openapi.getCreateApi().createMultipart(
        image: image,
        kind: kind,
        names: titles,
        test: test,
        tags: tags);
```

Usually when using json i need to create an object, which isnt the case here.

When looking into the code i noticed that the request body is defined as null. Then there is an empty try catch and then the request. My guess is that it is supposed to set the body.

##### openapi-generator version

6.5.0

##### OpenAPI declaration file content or url

```json
{
    "/create_multipart": {
        "post": {
            "tags": [
                "create"
            ],
            "operationId": "create_multipart",
            "requestBody": {
                "content": {
                    "multipart/form-data": {
                        "schema": {
                            "$ref": "#/components/schemas/MultipartRequest"
                        }
                    }
                },
                "required": true
            },
            "responses": {
                "200": {
                    "description": "Adds new"
                },
                "500": {
                    "description": "Internal Server Error",
                    "content": {
                        "application/json": {
                            "schema": {
                                "$ref": "#/components/schemas/ApiErrorResponse"
                            }
                        }
                    }
                }
            }
        }
    }
}
```
```json
"MultipartRequest": {
    "type": "object",
    "required": [
      "names",
      "kind",
      "tags",
      "image",
      "test",
    ],
    "properties": {
      "image": {
        "type": "string",
        "format": "binary"
      },
      "kind": {
        "type": "string"
      },
      "names": {
        "type": "array",
        "items": {
          "type": "string"
        }
      },
      "test": {
        "type": "boolean"
      },
      "tags": {
        "type": "array",
        "items": {
          "type": "string"
        }
      }
    }
  },
```
  -->

##### Generation Details

openapi-generator generate -i http://127.0.0.1:8080/api/docs -g dart-dio -o ./generated--skip-validate-spec -p serializationLibrary=json_serializable

**Comment by ahmednfwela** [comment] 2023-05-28 17:52
@jaumard (2018/09) @josh-burton (2019/12) @amondnet (2019/12) @sbu-WBT (2020/12) @kuhnroyal (2020/12) @agilob (2020/12) @ahmednfwela (2021/08)

**Comment by kuhnroyal** [comment] 2023-07-17 11:14
Note: This is actually related to dart-dio.

**Comment by kuhnroyal** [comment] 2023-07-17 11:57
Duplicate of Same as https://github.com/OpenAPITools/openapi-generator/issues/14472
@wing328 Please close as duplicate

**Closed** 2023-07-17 12:09 UTC
Labels: Issue: Bug
