### ISSUE TITLE
[BUG] [axios-typescript] header values configured via Configuration#baseOptions are dropped 

### ISSUE THREAD

**Issue by johannes-darms** [OpenAPITools/openapi-generator#4121] opened 2019-10-10 10:14 UTC
#### Bug Report Checklist

- [x] Have you provided a full/minimal spec to reproduce the issue?
- [x] Have you validated the input using an OpenAPI validator 
- [x] What's the version of OpenAPI Generator used?
- [x] Have you search for related issues/PRs?
- [x] What's the actual output vs expected output?

##### Description
Custom headers set via `baseOptions` of a Configuration object are not present in the axios request. Expected behaviour: they are present ;). 

##### openapi-generator version
4.1.2
##### OpenAPI declaration file content or url
 any, can be used
##### Command line used for generation
 any, can be used
##### Steps to reproduce
Pass this Configuration to a `*AxiosParamCreator`, the axios request should contain the custom header but is doesn't. 
```
new Configuration({
        baseOptions: {
          headers: {
            'x-CUSTOM-VALUE': `xxx`,
          },
        },
      })
```
##### Suggest a fix
https://github.com/johannes-darms/openapi-generator/commit/cd12d42df1cb139c1b16d80b4a8b9bc8425357f1

**Comment by macjohnny** [comment] 2019-10-10 10:37
I think the problem is that
https://github.com/OpenAPITools/openapi-generator/blob/b69b8cdd31aef20bf41022d84df08bc62aca747e/samples/client/petstore/typescript-axios/builds/default/api.ts#L294

should be changed to something like
```typescript
localVarRequestOptions.headers = {
  ...localVarHeaderParameter, 
  ...options.headers,
  ...(baseOptions ? baseOptions.headers : {})
};
```

@johannes-darms would you like to implement and test this fix in 
https://github.com/OpenAPITools/openapi-generator/blob/b69b8cdd31aef20bf41022d84df08bc62aca747e/modules/openapi-generator/src/main/resources/typescript-axios/apiInner.mustache#L191
?

**Comment by macjohnny** [comment] 2019-10-10 10:39
the suggested fix https://github.com/johannes-darms/openapi-generator/commit/cd12d42df1cb139c1b16d80b4a8b9bc8425357f1 looks good
would you like to file a PR?

**Comment by johannes-darms** [comment] 2019-10-10 11:07
> the suggested fix [johannes-darms@cd12d42](https://github.com/johannes-darms/openapi-generator/commit/cd12d42df1cb139c1b16d80b4a8b9bc8425357f1) looks good
> would you like to file a PR?

sure.

**Comment by jonathan-c-avento** [comment] 2020-02-11 15:47
What is the status of this, was a PR ever created?

**Comment by joshlang232** [comment] 2020-12-02 00:38
It looks like this commit fixes the issue: https://github.com/OpenAPITools/openapi-generator/commit/a4fc3195023dc0fd54944fb1cdf8f89bae0aa7ac

It seems safe to close this issue as a duplicate of https://github.com/OpenAPITools/openapi-generator/issues/5420

**Closed** 2020-12-02 06:38 UTC
Labels: Client: TypeScript, Issue: Bug
