### ISSUE TITLE
[BUG] Incorrect ENUM generation

### ISSUE THREAD

**Issue by Noed** [OpenAPITools/openapi-generator#19066] opened 2024-07-03 17:17 UTC
#### Bug Report Checklist

- [x] Have you provided a full/minimal spec to reproduce the issue?
- [x] Have you validated the input using an OpenAPI validator ([example](https://apidevtools.org/swagger-parser/online/))?
- [ ] Have you [tested with the latest master](https://github.com/OpenAPITools/openapi-generator/wiki/FAQ#how-to-test-with-the-latest-master-of-openapi-generator) to confirm the issue still exists?
- [x] Have you searched for related issues/PRs?
- [x] What's the actual output vs expected output?
- [ ] [Optional] Sponsorship to speed up the bug fix or feature request ([example](https://github.com/OpenAPITools/openapi-generator/issues/6178))

##### Description

ENUM is being generated with additional "_" character when there's a number on the ENUM name.

##### openapi-generator version

Issue started on 7.7.0, works fine on 7.7.6.

##### OpenAPI declaration file content or url

Example ENUM attribute in the YAML spec:

```
        myAttribute:
          description: this is a ENUM            
          type: string
          enum:
          - MOVE2STOCK
          - MOVE2SHELF
          - KEEP
```

##### Generation Details

Java 17, Gradle build.

##### Steps to reproduce

Add ENUM attribute to the spec that has numbers in the attribute name.
Generate java model using openapi generator 7.7.0.
Look into the source code generated, the ENUM attribute names will have an "_" after the number.

For example:

```
  public enum MyAttributeEnum {
    MOVE2_STOCK("MOVE2STOCK"),
    MOVE2_SHELF("MOVE2SHELF"),
    KEEP("KEEP"),
```

**Comment by Trebuac** [comment] 2024-07-04 13:13
Hello,
I got the same issue (different behaviour in my Java Enum generation between 7.6.0 and 7.7.0).

I suspect this commit to be the root cause : https://github.com/OpenAPITools/openapi-generator/commit/bfa26ea6be6af4984f94b60c67bc4fb0a5d76181#diff-a98cba8ecadaf5a662edc508aa5857972339552ec6bd6e4216680c7c6070e643

which is linked to this request https://github.com/OpenAPITools/openapi-generator/issues/4837 

Sadly it seems that we can't change this behavior (some generator have the option to choose the 'enumPropertyNaming' -
'camelCase', 'PascalCase', 'snake_case', 'UPPERCASE', and 'original'), a feature request has been opened for Java/Spring : https://github.com/OpenAPITools/openapi-generator/issues/18987

**Comment by Maran23** [comment] 2024-07-05 08:47
Is there an option to just use the enum as is? Without any futher modifications?

**Comment by AndresBena19** [comment] 2024-09-25 15:32
Any idea when https://github.com/OpenAPITools/openapi-generator/pull/19277 will be merged?

**Comment by magiusdarrigo** [comment] 2024-09-26 04:51
^^^

**Comment by goldel777** [comment] 2024-12-11 18:18
Looks like this overrode me

Under configOptions:

additionalProperties : enumPropertyNaming=original,modelPropertyNaming=original</additionalProperties

enumPropertyNaming: legacy

**Comment by wing328** [comment] 2024-12-11 18:19
Merged https://github.com/OpenAPITools/openapi-generator/pull/20172 two weeks ago. 

Please give it a try with the latest master or snapshot version.

**Closed** 2024-12-11 18:19 UTC
Labels: Issue: Bug

**Comment by goldel777** [comment] 2024-12-11 18:29
Can you help me understand where the mvn repo for openapi snapshots  can be found?

**Comment by wing328** [comment] 2024-12-12 05:27
please refer to the FAQ: https://github.com/OpenAPITools/openapi-generator/wiki/FAQ#how-to-test-with-the-latest-master-of-openapi-generator
