### ISSUE TITLE
[BUG] Python generator generating reserved word ("from")

### ISSUE THREAD

**Issue by rmerceragari** [OpenAPITools/openapi-generator#7119] opened 2020-08-03 17:39 UTC
#### Bug Report Checklist

- [x] Have you provided a full/minimal spec to reproduce the issue?
- [x] Have you validated the input using an OpenAPI validator ([example](https://apidevtools.org/swagger-parser/online/))?
- [x] What's the version of OpenAPI Generator used? v4.3.1 (implementation-version: 4.3.1)
- [x] Have you search for related issues/PRs? Yes
- [x] What's the actual output vs expected output? See below
- [ ] [Optional] Bounty to sponsor the fix ([example](https://www.bountysource.com/issues/66123212-javascript-client-produces-a-wrong-object-for-a-string-enum-type-that-is-used-with-ref))

##### Description

When using the python generator (not the experimental one) the provided spec generates a python test that uses a reserved word as a variable name. This causes python to blow up.

The spec has to have this property: A python reserved word is used as a nested property in a schema (FailureStats -> FailureStat -> from). From is a reserved word in python but is not escaped because it's nested. In the provided sample it ends up being generated in a test file:

```python
 def make_instance(self, include_optional):
        """Test FailureStats
            include_option is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # model = openapi_client.models.failure_stats.FailureStats()  # noqa: E501
        if include_optional :
            return FailureStats(
                version = 56, 
                status = '0', 
                code = 56, 
                offset = 56, 
                count = 56, 
                failure_stats = [
                    openapi_client.models.failure_stat.FailureStat(
                        samples = 56, 
                        subject = '0', 
                        from = '0',  # HERE!
                        domain = '0', 
                        first_occurrence = datetime.datetime.strptime('2013-10-20 19:20:30.00', '%Y-%m-%d %H:%M:%S.%f'), 
                        last_occurrence = datetime.datetime.strptime('2013-10-20 19:20:30.00', '%Y-%m-%d %H:%M:%S.%f'), 
                        ip_count = 56, 
                        links = [
                            '0'
                            ], )
                    ]
            )
        else :
            return FailureStats(
        )

```

##### openapi-generator version

v4.3.1 (implementation-version: 4.3.1). Does not appear to be a regression that I can see.

##### Command line used for generation

java -jar modules/openapi-generator-cli/target/openapi-generator-cli.jar generate -i spec3.yaml -g python -o ./output/

##### Steps to reproduce

Download openapi-generator-cli.jar from github.
java -jar modules/openapi-generator-cli/target/openapi-generator-cli.jar generate -i spec3.yaml -g python -o ./output/
pytest ./output/test/

##### Related issues/PRs

I couldnt find any that seemed to mimic this issue for python.

##### Suggest a fix

In PythonClientCodegen.java. On line 872. Just add the following:
```java
if (isReservedWord(propname)) {
     propname = escapeReservedWord(propname);
}

```

**Comment by ryan-beisner** [comment] 2020-10-12 21:15
I have a nearly identical scenario, where the "del" reserved operator is generated and used as an assignment inside the make_instance method, and it reproduces on 4.2.3 and 5.0.3b.

**Comment by 0xDAFE** [comment] 2020-12-08 11:58
Having the same problem with a nested "self" unfortunately.

`TypeError: wrapped_init() got multiple values for argument 'self'`.

Tested with v5.0.0-beta3 and 4.3.1.

**Comment by indydcarr** [comment] 2021-03-10 18:59
> Having the same problem with a nested "self" unfortunately.
> 
> `TypeError: wrapped_init() got multiple values for argument 'self'`.
> 
> Tested with v5.0.0-beta3 and 4.3.1.

I have the same exact issue, were you able to find a past version that this was resolved in?

**Comment by Kylmakalle** [comment] 2021-06-09 14:16
Experiencing this problem with `_self` attribute of AppStoreConnect API on 5.2.0-SNAPSHOT generator.

Works pretty fine on `5.1.1`

Looks like this diff 5.2.0 vs 5.1.1 changed the behaviour
![image](https://user-images.githubusercontent.com/24507532/121371218-114bb500-c946-11eb-921c-be1f1a8bfb57.png)

**Comment by mugx-fc** [comment] 2021-07-15 19:09
I had a similar issue while using the keyword `self` (trying to be respectful of the HAL schema definition: https://datatracker.ietf.org/doc/html/draft-kelly-json-hal#section-8.1), so I found a solution using the following flag

`--reserved-words-mappings self=self`

hope that can help you.

**Comment by Lnk2past** [comment] 2022-09-29 15:50
I am hitting this error (specifically with `from`). Trying `--reserved-words-mappings from=from` didn't seem to have any effect on the generated code. Am I using this flag incorrectly, or is there another workaround? I am attempting to use a spec (that I do not control) and it uses reserved words from Python as a part of various schemas/components.

**Comment by spacether** [comment] 2022-10-05 18:59
This is working in v6.2.0 and onward in the python client if the property has an inline schema.
If the property is a refed schema, then this is working in commit [57f5cc4](https://github.com/OpenAPITools/openapi-generator/commit/57f5cc4000aa90c44a382956927dd24599c81927) which will land in 6.2.1.

**Closed by spacether** 2022-10-05 18:59 UTC
Labels: Client: Python, Issue: Bug
