### ISSUE TITLE
[BUG][csharp-netcore] C# Client for Net Core generate port exaustion

### ISSUE THREAD

**Issue by lucamazzanti** [OpenAPITools/openapi-generator#9060] opened 2021-03-24 13:00 UTC
##### Description
I moved from Net Framework 4.7 to Net Core 3.1 and 5 and I have a critical issue.

The csharp-netcore client uses RestSharp and is not stable with Net Core actually. See [this](https://github.com/restsharp/RestSharp/issues/1406) issue. 
It seems to be a net core breaking change they won't patch in time and actually this is impacting on RestSharp.

It silently open at every call a new socket, creating a new HttpWebRequest each time. 
This is a behavior totally different in NetFramework where it keep the same.
You can reproduce it easily generating a simple client and using it in both verisons.
Test multiple calls and watch the connection in Wireshark, I can further add images or a report if you prefer.

While NetFramework honors the keep-alive header (supported also by the server) in Net Core it doesnt.
- In NetFramework  it do the handshake and TLS connection just 1 time, and it consumes just one socket keeping working on it with the next calls.
- In Net Core not, it open a new socket each times.

This is critical because you cannot understand it when moving your client to net core until you have a feedback from the server closing the connections to all.

I see there is a version with HttpClient, i tried it but it create every time:
` var handler = new HttpClientHandler(); var client = new HttpClient();`

##### openapi-generator version
openapi-generator-cli-5.1.0.jar with csharp-netcore client without settings.

**Comment by wing328** [comment] 2021-03-24 13:03
The latest version of OpenAPI Generator v5.1.0 supports HttpClient (--library httpclient). Please give it a try.

**Comment by lucamazzanti** [comment] 2021-03-24 13:04
I see there is a version with HttpClient, i tried it but it create every time:

```
var handler = new HttpClientHandler(); 
var client = new HttpClient();
```

So the issue remains

**Comment by devhl-labs** [comment] 2021-03-25 01:01
You'll want this pr once it's merged. You pass in the HttpClient, so you control it entirely.

https://github.com/OpenAPITools/openapi-generator/pull/9073

Note that it requires a bit of post processing, but here is a script for it, just edit the parameters to suite your needs.

```ps1
java -jar "../openapi-generator/modules/openapi-generator-cli/target/openapi-generator-cli.jar" generate `
    -g csharp-netcore `
    -i "your-swagger-file.yml" `
    -c generator-config.json `
    -o output `
    -t templates `
    --library httpclient

$files = Get-ChildItem output -Recurse | Where-Object {-Not($_.PSIsContainer)}
foreach ($file in $files)
{
    $content=Get-Content $file.PSPath

    if (-Not($content)){
        continue;
    }

    # if null reference types are enabled
    $content=$content -replace '\?{3,4}', '?' # replace every three to four consecutive occurrences of '?' with a single one

    # if null reference types are not enabled
    # $content=$content.Replace("????", "?") # reference type
    # $content=$content.Replace("???", "") # value type

    Set-Content $file.PSPath $content    
}
```

**Comment by Blackclaws** [comment] 2021-03-25 08:55
You are absolutely right. The issue is that HttpClient is not disposed. Will fix immediately. There is also the additional property reUseHttpClient which should alleviate the problem as only a single HttpClient is used for the whole ApiClient then.

Passing in an HttpClient is on the roadmap.

**Comment by Blackclaws** [comment] 2021-03-25 09:25
After some further investigation the issue appears a bit larger as even a static HttpClient will break after some usage. I'll investigate and try to get a pull request up today.

**Comment by Blackclaws** [comment] 2021-03-25 11:47
Pull request is up which fixes this issue

**Closed** 2021-03-27 07:20 UTC
Labels: Issue: Bug
