### ISSUE TITLE
[BUG] [Spring] [Java] Invalid code generated for schemas with oneOf object attributes

### ISSUE THREAD

**Issue by wagnerrobsan** [OpenAPITools/openapi-generator#11932] opened 2022-03-21 17:34 UTC
#### Bug Report Checklist

- [x] Have you provided a full/minimal spec to reproduce the issue?
- [x] Have you validated the input using an OpenAPI validator ([example](https://apidevtools.org/swagger-parser/online/))?
- [x] Have you [tested with the latest master](https://github.com/OpenAPITools/openapi-generator/wiki/FAQ#how-to-test-with-the-latest-master-of-openapi-generator) to confirm the issue still exists?
- [x] Have you searched for related issues/PRs?
- [x] What's the actual output vs expected output?
- [ ] [Optional] Sponsorship to speed up the bug fix or feature request ([example](https://github.com/OpenAPITools/openapi-generator/issues/6178))

##### Description

When generating a **spring** or **java** code with a spec that contains an attribute with _oneOf_, the code generator creates a code with a bug

Spec: https://gist.github.com/wagnerrobsan/88d81d113d4add401667e64ab814e3aa

Creates the following java code:
```
public Fruit putBodyItem(String key,  bodyItem) {
    if (this.body == null) {
      this.body = ;
    }
    this.body.put(key, bodyItem);
    return this;
  }
```
##### openapi-generator version

latest version, build from master 

##### OpenAPI declaration file content or url

Providing minimal reproducing example (YAML):

Spec: https://gist.github.com/wagnerrobsan/88d81d113d4add401667e64ab814e3aa

##### Generation Details

see `Steps to reproduce` for more details 

##### Steps to reproduce

`git clone https://github.com/openapitools/openapi-generator`
`cd openapi-generator`
`mvn clean package`
`java -jar modules/openapi-generator-cli/target/openapi-generator-cli.jar generate \`
`   -i https://gist.githubusercontent.com/wagnerrobsan/88d81d113d4add401667e64ab814e3aa/raw/ab969d651c60e76be6b44ba69950c77b9992c108/openapi-oneOfbug.yaml \ `
`   -g spring \`
`   -o /outputFolder/oneOfBugApiClient`

##### Related issues/PRs

Related to 
* https://github.com/OpenAPITools/openapi-generator/pull/11650
* https://github.com/OpenAPITools/openapi-generator/issues/5381
##### Suggest a fix

The code generator should skip in the mustache file the putBodyItem method creation.
see file JavaSpring/pojo.mustache

**Comment by wing328** [comment] 2022-03-22 06:38
Please try the latest master (snapshot version can be found in the readme) as there's a merged PR related to Spring's oneOf support.

**Comment by wagnerrobsan** [comment] 2022-03-22 12:11
> Please try the latest master (snapshot version can be found in the readme) as there's a merged PR related to Spring's oneOf support.

Hi William,
I'm building the code from master, actually I found it when I was testing the feature #11650 used to fix the bug. Take a look **steps to reproduce**
The java generator thinks it's a Map Schema and tries to create _putItem_ method
```
  {{#isMap}}
  public {{classname}} put{{nameInCamelCase}}Item(String key, {{{items.datatypeWithEnum}}} {{name}}Item) {
    {{^required}}
    if (this.{{name}} == null) {
      this.{{name}} = {{{defaultValue}}};
    }
    {{/required}}
    this.{{name}}.put(key, {{name}}Item);
    return this;
  }
  {{/isMap}}
```
Thanks

**Comment by wagnerrobsan** [comment] 2022-03-25 18:25
Hi @wing328 
I fixed the bug (added a unit test, a yaml file and a small change to the DefaultCodegen class), but I'm getting 403 trying to push the new branch. 
Can you please advise? If you want I can share more details about the patch here, 
Thanks

**Comment by cachescrubber** [comment] 2022-03-26 06:40
@wagnerrobsan IMO this is not a Bug. Inline definition of oneOf is currently not supported  You have to model an explicit `FruitBody` Schema.

      fruit:
        title: fruit
        additionalProperties: false
        properties:
          fruitId:
            type: string
            description: The unique ID of the fruit
          body:
            $ref: '#/components/schemas/FruitBody'
      FruitBody:
        type: object
        description: The raw event payload that will be different based on the event.
        discriminator:
          propertyName: kind
        oneOf:
          - $ref: '#/components/schemas/apple'
          - $ref: '#/components/schemas/banana'

The following spec should do the trick: https://gist.github.com/cachescrubber/f77ebc1d6f1b7f0e20aa593dde469ad2.

**Comment by wagnerrobsan** [comment] 2022-03-28 13:07
Hi @cachescrubber 
Thanks for your quick response and propose the alternative solution , appreciate it!

I created a Pull Request to support oneOf inline usage. I hope it makes sense, it's not a big change and it implements/fix the inline oneOf support
https://github.com/OpenAPITools/openapi-generator/pull/11987
Thanks

**Comment by wing328** [comment] 2022-09-05 10:37
Please give the latest master another try as we've improved inline schema handling and oneOf support in Spring generator.

Happy to reopen if this is still an issue.

**Closed by wing328** 2022-09-05 10:37 UTC
Labels: Issue: Bug
