### ISSUE TITLE
[BUG] Missing dependency in pom.xml on Java 11

### ISSUE THREAD

**Issue by kibertoad** [OpenAPITools/openapi-generator#5358] opened 2020-02-18 13:10 UTC
#### Bug Report Checklist

- [X] What's the version of OpenAPI Generator used? 4.2.3

##### Description

Default pom.xml generated for Java project fails on Java 11 because javax.annotation is no longer bundled with the language.

##### Command line used for generation

`java -jar openapi-generator-cli-4.2.3.jar generate -i ../specs\hilton\hospitality-partner.json -g java -o ../src/generated/hilton -c config.json`

##### Steps to reproduce

Try compiling any generated Java project using Java 11.

##### Suggest a fix

It shouldn't cause any issues if javax.annotation is included as a dependency by default in pom.xml generated for Java, especially since Java 8 was deprecated for commercial use, so supporting Java 11 out-of-the-box sounds like a good idea.

If this is approved, I can prepare a PR for that.

**Comment by kibertoad** [comment] 2020-02-19 22:22
@wing328 What do you think?

**Comment by wing328** [comment] 2020-02-20 06:46
Let's have a quick chat via Slack when you've time today or tomorrow.

**Comment by kibertoad** [comment] 2020-02-20 21:43
@wing328 Sure, which workspace should we use for that? I'm also on gitter.

**Comment by wing328** [comment] 2020-02-21 07:48
https://join.slack.com/t/openapi-generator/shared_invite/enQtNzAyNDMyOTU0OTE1LTY5ZDBiNDI5NzI5ZjQ1Y2E5OWVjMjZkYzY1ZGM2MWQ4YWFjMzcyNDY5MGI4NjQxNDBiMTlmZTc5NjY2ZTQ5MGM

**Comment by ingnil** [comment] 2020-03-04 13:13
There is a Generated class in the javax.annotation.processing package. Was the class moved from the javax.annotation package?

I ran into the same problem, and happened to find the class in the new package. After editing the generated sources, the problem goes away. Checking the API docs, it seems the class was moved in JDK 10. JDK 9 still has the javax.annotation.Generated class.

**Comment by M3lkior** [comment] 2020-07-28 16:07
Same problem here. i need to use java11 for packaging but stuck with this java 8 limitation

**Comment by wing328** [comment] 2020-07-29 02:20
Which version are you using? Can you try the latest master or 5.0.0-beta?

**Comment by M3lkior** [comment] 2020-07-29 12:25
It seems to be ok using the 5.0.0-beta version but it is still a pre-release version ;)

Thanks

**Comment by wing328** [comment] 2020-07-30 01:25
Just reviewed my conversations with @kibertoad and confirmed the issue has been fixed in v4.3.1

**Closed by wing328** 2020-07-30 01:25 UTC
Labels: Issue: Bug

**Comment by M3lkior** [comment] 2020-07-30 06:49
For info, I'm previously using v4.3.1 and it does not work with this version
