### ISSUE TITLE
[BUG][typescript-fetch] Typescript error in generated code for endpoint returning type boolean

### ISSUE THREAD

**Issue by matthewbpt** [OpenAPITools/openapi-generator#2870] opened 2019-05-11 10:45 UTC
#### Bug Report Checklist

- [x] Have you provided a full/minimal spec to reproduce the issue?
- [x] Have you validated the input using an OpenAPI validator ([example](https://apidevtools.org/swagger-parser/online/))?
- [x] What's the version of OpenAPI Generator used? 4.0.0-beta3 from npm
- [x] Have you search for related issues/PRs?
- [x] What's the actual output vs expected output?
- [ ] [Optional] Bounty to sponsor the fix ([example](https://www.bountysource.com/issues/66123212-javascript-client-produces-a-wrong-object-for-a-string-enum-type-that-is-used-with-ref))

##### Description

When generating the typescript api client, the generated client has type errors for any methods returning a boolean.

```typescript
export class UserApi extends runtime.BaseAPI {

    async userEmailExistsRaw(requestParameters: UserEmailExistsRequest): Promise<runtime.ApiResponse<boolean>> {
        if (requestParameters.email === null || requestParameters.email === undefined) {
            throw new runtime.RequiredError('email','Required parameter requestParameters.email was null or undefined when calling userEmailExists.');
        }

        const queryParameters: runtime.HTTPQuery = {};

        const headerParameters: runtime.HTTPHeaders = {};

        const response = await this.request({
            path: `/api/1.0/users/userExists/{email}`.replace(`{${"email"}}`, encodeURIComponent(String(requestParameters.email))),
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        });

        return new runtime.TextApiResponse(response);
    }

    async userEmailExists(requestParameters: UserEmailExistsRequest): Promise<boolean> {
        const response = await this.userEmailExistsRaw(requestParameters);
        return await response.value();
    }
}
```

The return statement from `userEmailExistsRaw` has error:

```
Type 'TextApiResponse' is not assignable to type 'ApiResponse<boolean>'.
  Types of property 'value' are incompatible.
    Type '() => Promise<string>' is not assignable to type '() => Promise<boolean>'.
      Type 'Promise<string>' is not assignable to type 'Promise<boolean>'.
        Type 'string' is not assignable to type 'boolean'.ts(2322)
```
##### openapi-generator version
4.0.0-beta3 from npm

##### OpenAPI declaration file content or url
```yaml
---
swagger: '2.0'
info:
  description: Operations related to the API
  version: '1.0'
  title: API
host: api.example.com
basePath: "/"
tags:
- name: User
  description: All apis relating to Users
schemes:
- http
- https
produces:
- application/xml
- application/json
paths:
  "/api/1.0/users/userExists/{email}":
    get:
      tags:
      - User
      operationId: userEmailExists
      parameters:
      - name: email
        in: path
        description: email
        required: true
        type: string
      responses:
        '200':
          description: Successfully retrieved result!
          schema:
            type: boolean
  "/api/1.0/users/id/{id}":
    get:
      tags:
      - User
      summary: Get specific User by id
      operationId: findUserById
      parameters:
      - name: id
        in: path
        description: id
        required: true
        type: integer
        format: int64
      responses:
        '200':
          description: Successfully retrieved result!
          schema:
            "$ref": "#/definitions/UserDto"
definitions:
  UserDto:
    type: object
    required:
    - id
    - email
    - firstName
    - lastName
    properties:
      id:
        type: integer
        format: int64
      email:
        type: string
      firstName:
        type: string
      lastName:
        type: string
    title: UserDto

```

##### Command line used for generation

```openapi-generator generate --additional-properties supportsES6=true -i ./openapi.yaml -g typescript-fetch -o out/typescript-fetch```

##### Steps to reproduce
Save yaml to `openapi.yaml` in current directory and run the command above.

##### Suggest a fix
Since `true` and `false` are both valid json responses, should the return statement simple be `return new runtime.JSONApiResponse(response);` (This also satisfies the typechecker)

**Comment by macjohnny** [comment] 2019-07-23 07:59
@matthewbpt is this issue still present? 
would you like to implement a fix for this?

**Comment by matthewbpt** [comment] 2019-07-24 09:04
Hi @macjohnny , the issue is still present as far as I can see. I was thinking of implementing a fix when I reported the issue, but did not find the time, and we decided to use the typescript-axios generator instead as it does not have this issue.

**Comment by macjohnny** [comment] 2019-07-24 10:49
cc @TiFu

**Comment by TiFu** [comment] 2019-07-24 11:54
I think the issue is probably in this line:

https://github.com/OpenAPITools/openapi-generator/blob/master/modules/openapi-generator/src/main/resources/typescript-fetch/apis.mustache#L214

The fix could be as simple as adding additional conditions here and adding a new response type to https://github.com/OpenAPITools/openapi-generator/blob/master/modules/openapi-generator/src/main/resources/typescript-fetch/runtime.mustache

Unfortunately I don't have time to implement this as I will be moving to another country next week.

**Comment by macjohnny** [comment] 2019-07-24 12:16
@matthewbpt would you give us a hand and try to fix it with @TiFu's suggestion?

**Comment by ffMathy** [comment] 2019-10-02 11:46
This is still present today on the latest version.

**Comment by ffMathy** [comment] 2019-10-02 11:47
The ironic part is that if you look at `userEmailExistsRaw`, it actually contains the correct return type, but isn't able to write out the correct return statement.

Should be relatively simple to fix, but I don't have much time.

**Comment by pavel-zdenek** [comment] 2019-10-02 11:54
We have fixed this for our project by dropping primitive return values altogether in favour of objects with a single value of the primitive type. It can even be considered "better design" (i.e. consistent JSON) but not applicable for every one and every project out there.

**Closed** 2019-10-02 15:26 UTC
Labels: Client: TypeScript, Issue: Bug

**Comment by keesvanlierop** [comment] 2020-02-05 11:59
Typings are fixed, but serialization of the responses is still incorrect with `runtime.TextApiResponse` instead of `runtime.JSONApiResponse`. @matthewbpt were you able to fix it with the latest commits you've pushed in your fork? If so, can you submit a PR?

**Comment by pengcheng** [comment] 2020-09-24 02:41
I think the root cause is the CodeGen uses `return data type` while choosing `TextApiResponse` or `JSONApiResponse`, this seems incorrect, we should use the content type (i.e. application/json) in the response body definition instead, if it is  'application/json', `JSONApiResponse` should be used for all types (object, simple type, etc).

**Comment by tobq** [comment] 2022-10-13 03:42
This is still an issue

**Comment by borispetrovdev** [comment] 2023-01-25 17:32
Confirmed still an issue in 6.2.1
