### ISSUE TITLE
[BUG] BigDecimal not imported in 7.0.0

### ISSUE THREAD

**Issue by OlliL** [OpenAPITools/openapi-generator#16166] opened 2023-07-23 08:24 UTC
##### Description
Client generation from that API:

```
		"parameters": [
			{
				"name": "amount",
				"in": "path",
				"required": true,
				"schema": {
					"type": "number"
				}
			},
```
full 'get' definition: https://github.com/OlliL/moneyjinn-server/blob/master/moneyjinn-server/src/main/resources/openapi/moneyflow/paths/SearchMoneyflowsByAmount.json

Is generated as:
```
  public SearchMoneyflowsByAmountResponse searchMoneyflowsByAmount(BigDecimal amount, String dateFromStr, String dateTilStr) throws ApiException {
    return this.searchMoneyflowsByAmount(amount, dateFromStr, dateTilStr, Collections.emptyMap());
  }
```

**But**: BigDecimal is not imported! The file can't be compiled:

```
MoneyflowControllerApi.java:[288,68] cannot find symbol
  symbol:   class BigDecimal
  location: class org.laladev.moneyjinn.hbci.backend.api.MoneyflowControllerApi
MoneyflowControllerApi.java:[303,68] cannot find symbol
  symbol:   class BigDecimal
  location: class org.laladev.moneyjinn.hbci.backend.api.MoneyflowControllerApi
```

##### openapi-generator version

7.0.0-beta generates this error.
6.6.0 works fine!

##### generator configuration

```
<configuration>
	<inputSpec>${project.basedir}/../moneyjinn-server/src/main/resources/openapi.json</inputSpec>
	<generatorName>java</generatorName>
	<apiPackage>org.laladev.moneyjinn.hbci.backend.api</apiPackage>
	<modelPackage>org.laladev.moneyjinn.hbci.backend.model</modelPackage>
	<skipOperationExample>true</skipOperationExample>
	<configOptions>
		<library>apache-httpclient</library>
		<sourceFolder>src/gen/java/main</sourceFolder>
		<useJakartaEe>true</useJakartaEe>
		<openApiNullable>false</openApiNullable>
		<useTags>true</useTags>
	</configOptions>
</configuration>
````

**Comment by martin-mfg** [comment] 2023-07-25 06:32
This problem happens since #13897. @karzang, do you know what's going wrong here?

**Comment by karzang** [comment] 2023-07-25 13:15
Hi, I assume this has to do with my PR #13897 and I'll look into this issue.

I think it has to do with these changes:

 https://github.com/OpenAPITools/openapi-generator/pull/13897/files#diff-e939f76e33b14e4de9645853ba5bdeb050b5fa0b6676693ff900fd60aaf08528
 
 Can you please provide a minimal input specification for which the error occurs so I can reproduce it myself?

**Comment by OlliL** [comment] 2023-07-25 13:40
there you go:

```
{
	"openapi": "3.0.1",
	"info": {
		"title": "OpenAPI definition",
		"version": "v0"
	},
	"paths": {
		"/test": {
			"get": {
				"parameters": [
					{
						"name": "amount",
						"in": "path",
						"schema": {
							"type": "number"
						}
					}
				],
				"responses": {
				}
			}
		}
	}
}
```

generates this:
```
/*
 * OpenAPI definition
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

package org.laladev.moneyjinn.hbci.backend.api;

import com.fasterxml.jackson.core.type.TypeReference;

import org.laladev.moneyjinn.hbci.backend.ApiException;
import org.laladev.moneyjinn.hbci.backend.ApiClient;
import org.laladev.moneyjinn.hbci.backend.Configuration;
import org.laladev.moneyjinn.hbci.backend.Pair;



import java.util.ArrayList;
import java.util.Collections;
import java.util.HashMap;
import java.util.List;
import java.util.Map;
import java.util.StringJoiner;

@jakarta.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen", date = "2023-07-25T15:39:25.509850100+02:00[Europe/Berlin]")
public class DefaultApi {


  private ApiClient apiClient;

  public DefaultApi() {
    this(Configuration.getDefaultApiClient());
  }

  public DefaultApi(ApiClient apiClient) {
    this.apiClient = apiClient;
  }

  public ApiClient getApiClient() {
    return apiClient;
  }

  public void setApiClient(ApiClient apiClient) {
    this.apiClient = apiClient;
  }

  /**
   * 
   * 
   * @param amount  (optional)
   * @throws ApiException if fails to make API call
   */
  public void testGet(BigDecimal amount) throws ApiException {
    this.testGet(amount, Collections.emptyMap());
  }


  /**
   * 
   * 
   * @param amount  (optional)
   * @param additionalHeaders additionalHeaders for this call
   * @throws ApiException if fails to make API call
   */
  public void testGet(BigDecimal amount, Map<String, String> additionalHeaders) throws ApiException {
    Object localVarPostBody = null;
    
    // create path and map variables
    String localVarPath = "/test"
      .replaceAll("\\{" + "amount" + "\\}", apiClient.escapeString(amount.toString()));

    StringJoiner localVarQueryStringJoiner = new StringJoiner("&");
    String localVarQueryParameterBaseName;
    List<Pair> localVarQueryParams = new ArrayList<Pair>();
    List<Pair> localVarCollectionQueryParams = new ArrayList<Pair>();
    Map<String, String> localVarHeaderParams = new HashMap<String, String>();
    Map<String, String> localVarCookieParams = new HashMap<String, String>();
    Map<String, Object> localVarFormParams = new HashMap<String, Object>();

    
    localVarHeaderParams.putAll(additionalHeaders);

    
    
    final String[] localVarAccepts = {
      
    };
    final String localVarAccept = apiClient.selectHeaderAccept(localVarAccepts);

    final String[] localVarContentTypes = {
      
    };
    final String localVarContentType = apiClient.selectHeaderContentType(localVarContentTypes);

    String[] localVarAuthNames = new String[] {  };

    apiClient.invokeAPI(
        localVarPath,
        "GET",
        localVarQueryParams,
        localVarCollectionQueryParams,
        localVarQueryStringJoiner.toString(),
        localVarPostBody,
        localVarHeaderParams,
        localVarCookieParams,
        localVarFormParams,
        localVarAccept,
        localVarContentType,
        localVarAuthNames,
        null
    );
  }

}
```

**Comment by karzang** [comment] 2023-07-27 14:48
@OlliL I provided a potential fix for your problem in the above PR. If you can confirm that this would fix your problem I think the PR has more chance to be merged soon.

**Closed** 2023-08-06 03:16 UTC
Labels: Issue: Bug

**Comment by wing328** [comment] 2023-08-06 05:19
PR merged and added a test separately to catch the issue moving forward. Please pull the latest master to give it a try.
