### ISSUE TITLE
-DdebugModels returns StackOverFlowException

### ISSUE THREAD

**Issue by emreakca** [OpenAPITools/openapi-generator#883] opened 2018-08-23 11:17 UTC
##### Description

Hey, can someone help me with this issue: when i try to -DdebugModels, i get an StackOverFlowErrorException. Generating the client works without problems, so does
-DdebugOperations...
Had someone the same error or know a fix? Or a suggestion on how I can find the cause?

##### error
```
com.fasterxml.jackson.databind.JsonMappingException: Infinite recursion (StackOverflowError) (through reference chain: java.util.ArrayList[0]->org.openapitools.codegen.CodegenModel["parentModel"]
```
##### openapi-generator version

3.1 & 3.2.3

##### Command line used for generation

`java -DdebugModels -jar modules/openapi-generator-cli/target/openapi-generator-cli.jar generate -i http://localhost:8080/openapi.json -g java`

**Comment by jmini** [comment] 2018-08-24 05:06
Maybe this is a duplicate of #241 ?

**Comment by wing328** [comment] 2018-08-27 03:48
UPDATE: I've filed #903 to fix the issue.

Please take a look when you've time.

**Comment by wing328** [comment] 2018-08-27 14:06
#903 has been merged into master. Please try the latest (SNAPSHOT, docker images, etc) when you've time

**Closed by wing328** 2018-08-27 14:06 UTC
Labels: Feature: Generator, Issue: Bug
