### ISSUE TITLE
[BUG] [SPRING] incorrect generation of add*Item methods for List-fields in 6.5.0

### ISSUE THREAD

**Issue by arandth** [OpenAPITools/openapi-generator#15402] opened 2023-05-03 10:01 UTC
##### Description

Migrating from 6.2.1 to 6.5.0 we run into an issue with list fields which might be defined as

    AdditionalProperties:
      properties:
        additional_properties:
          type: array
          default: []
          items:
            type: string

The generator will generate a add a addAdditionalPropertiesItem method wich is wrong:

  public AdditionalProperties addAdditionalPropertiesItem(String additionalPropertiesItem) {
    if (this.additionalProperties == null) {
      this.additionalProperties = null;     // **here is the bug**
    }
    this.additionalProperties.add(additionalPropertiesItem);
    return this;
  }

##### openapi-generator version

6.5.0 (maven plugin)

##### OpenAPI declaration file content or url

see above

**Comment by m-kay** [comment] 2023-05-05 05:42
I'm having the same issue, however removing the `default: []` makes things even worse. Without the default the generated code looks like this:
```java
public AdditionalProperties addAdditionalPropertiesItem(String additionalPropertiesItem) {
   if (this.additionalProperties == null) {
      this.additionalProperties = ; // this does not even compile
   }
   this.additionalProperties.add(additionalPropertiesItem);
   return this;
}
```

**Comment by arandth** [comment] 2023-05-05 06:08
I'm asking myself whether there are no regression tests for the generator that could avoid these kind of errors. It's annoying having a feature that used to work for so long, and suddenly, with a new version, something is broken.

**Comment by wing328** [comment] 2023-05-05 06:19
@arandth agreed we can do better to catch regressions.

I filed a fix or 2 like 2 weeks ago. 

Can you please give it a try with the latest master?

**Comment by wing328** [comment] 2023-05-05 07:01
>       default: []

the default behaviour is to initialise an empty list as the default.

setting `nullable: true` will use `null` as the default.

**Comment by arandth** [comment] 2023-05-05 07:31
totally right. But as explained, it doesn't work so

**Comment by m-kay** [comment] 2023-05-05 07:37
With version `6.6.0-SNAPSHOT` the problem still exists.

**Comment by wing328** [comment] 2023-05-05 08:26
generated with the latest master with `./bin/configs/spring-boot-3.yaml`
```
generatorName: spring
outputDir: samples/openapi3/server/petstore/springboot-3
inputSpec: modules/openapi-generator/src/test/resources/3_0/petstore.yaml
templateDir: modules/openapi-generator/src/main/resources/JavaSpring
additionalProperties:
  groupId: org.openapitools.openapi3
  documentationProvider: springdoc
  artifactId: springboot
  snapshotVersion: "true"
  useSpringBoot3: true
  useBeanValidation: true
  hideGenerationTimestamp: "true"
```
added the following to `modules/openapi-generator/src/test/resources/3_0/petstore.yaml`

and got the following new java file partially shown below:
```java
@Generated(value = "org.openapitools.codegen.languages.SpringCodegen")
public class AdditionalProperties {

  @Valid
  private List<String> additionalProperties;

  public AdditionalProperties additionalProperties(List<String> additionalProperties) {
    this.additionalProperties = additionalProperties;
    return this;
  }

  public AdditionalProperties addAdditionalPropertiesItem(String additionalPropertiesItem) {
    if (this.additionalProperties == null) {
      this.additionalProperties = new ArrayList<>();
    }
    this.additionalProperties.add(additionalPropertiesItem);
    return this;
  }
```

in other words I cannot reproduce the issue  you reported.

can you please give it another try with the latest master?

**Comment by m-kay** [comment] 2023-05-05 08:33
Oh sorry, I was actually using the java client generator. Shout I open a new bug for that?

**Comment by wing328** [comment] 2023-05-05 08:33
yes please

**Comment by arandth** [comment] 2023-05-05 09:59
@wing328 I would love to try the latest master, but I do not know how to do. Is there a (SNAPSHOT) maven artifact for the generator plugin?
Concerning your latest post: You forget to tell the changes in the yaml file you made. But assuming you added 'default: []' to the field, the generated code would not be correct. The field definition must be
@Valid
  private List<String> additionalProperties = new ArrayList<>();
  (or the get-Method would have to make sure a not-null value is returned)

**Comment by wing328** [comment] 2023-05-05 10:10
> Is there a (SNAPSHOT) maven artifact for the generator plugin?

it's in the readme. just search for "snapshot"

**Comment by Klaboe** [comment] 2023-05-05 10:28
When talking about undesired behavior connected with ```default: []``` , spring-generator and the latest release (6.5):

I have a Set of Sets, defined by

```
{
    "theSet":  {
        "type": "array",
        "default": [],
        "uniqueItems": true,
        "items": {
            "type": "array",
            "uniqueItems": true,
            "items": {
                "type": "string",
                "format": "uuid"
            }
        }
}
```

Having the ```default: []``` set, will produce 
```
private Set<Set<UUID>> theSet = new LinkedHashSet<>();
(...)
if (this.theSet== null) {
      this.theSet = new LinkedHashSet<>();
    }
    this.theSet.add(anotherSet);
return this;
(...)
```
in 6.2.1, 

```
private Set<Set<UUID>> theSet = ;
(...)
if (this.theSet== null) {
      this.theSet = ;
    }
    this.theSet.add(anotherSet);
return this;
(...)
``` 
with openApiGenerator 6.4, and

```
private Set<Set<UUID>> theSet;
(...)
if (this.theSet == null) {
      this.theSet = new LinkedHashSet<>();
    }
this.theSet.add(anotherSet);
return this;
(...)
``` 

in 6.5 ; not sure if this is intended, but now at least it compiles.

Removing ```default: []``` produces in 6.5
```
private Set<Set<UUID>> theSet= new LinkedHashSet<>();
(...)
if (this.theSet== null) {
      this.theSet= new LinkedHashSet<>();
    }
this.theSet.add(anotherSet);
return this;
```

**Comment by arandth** [comment] 2023-05-08 10:18
Hi @Klaboe 
concerning your last post, last section ("removing default: [] produces in 6.5").  Are you sure that your code snippet is really from the generated output? As it is very unusual that it initialises the Set-field variable if there is no "default" setting for it.

**Comment by Klaboe** [comment] 2023-05-08 11:08
Yes; that is from the generated output. As a doble-wammy: for a regular list: 

```
"aList": {
    "type": "array",
    "items": {
        "$ref": "#/components/schemas/SomeType"
    },
    "default": []
}
```
produces in 6.5.0

```
private List<@Valid SomeType> aList = null;
(...)
if (this.aList == null) {
      this.aList = null;
    }
this.aList.add(<providedItem>);
return this;
```
If i remove ```default[]```, den this is produced:
```
private List<@Valid SomeType> aList= new ArrayList<>();
(...)
if (this.aList == null) {
      this.aList = new ArrayList<>();
    }
this.aList.add(<providedItem>);
return this;
```

**Comment by wing328** [comment] 2023-05-24 07:12
openapi generator v6.6.0 has been released. please give it a try and let us know if it's still an issue.

**Comment by arandth** [comment] 2023-05-25 09:39
Hi @wing328 
thanks for that suggestion!
From my side I unfortunately also have to say that there is absoblutely no change. Whenever I have a List-field specifying an empty list as default the code-generator generates that null-setting in the add*Items methods

**Comment by wing328** [comment] 2023-05-29 07:53
Just so we're all on the same page. Removing `default: []` and the output works as expected.

The goal is to support `default: []` as well to initialise an empty array/set.

Is my understanding correct?

**Comment by arandth** [comment] 2023-05-30 05:06
From my POV: I would say Yes!

**Comment by wing328** [comment] 2023-06-14 03:19
I've just merged https://github.com/OpenAPITools/openapi-generator/pull/15836. 

Can you please pull the latest master to give it a try?

**Comment by arandth** [comment] 2023-06-14 08:13
I did. No change :-(
  public And addOrItem(Or orItem) {
    if (this.or == null) {
      this.or = null;
    }
    this.or.add(orItem);
    return this;
  }

**Comment by wing328** [comment] 2023-06-14 08:45
thanks for the quick test. will take another look over the weekend.

**Comment by wing328** [comment] 2023-06-16 10:20
@arandth I've filed https://github.com/OpenAPITools/openapi-generator/pull/15862 to fix the issue and added a test to cover the issue moving forward.

Can you please give it a try to see if it works for you? Thanks.

**Comment by wing328** [comment] 2023-06-20 03:28
@arandth I just merged the fix into the master. Please give it another try when you've time.

happy to reopen this issue if needed.

**Closed** 2023-06-20 03:27 UTC
Labels: Issue: Bug

**Comment by arandth** [comment] 2023-06-20 13:37
Hi @wing328 ,
I tested it with the new version, and if seems to be solved! At least all the locations that I looked at were correctly generated!
Thanks a lot, Thomas
