### ISSUE TITLE
[BUG] The kotlin-spring generator ApiUtil object doesn't compile

### ISSUE THREAD

**Issue by hemynem** [OpenAPITools/openapi-generator#5476] opened 2020-02-28 10:39 UTC
##### Description

the kotlin-spring generator produces code which doesn't compile.

##### openapi-generator version

openapi-generator version: 4.2.3
gradle version: 5.6.2

##### Command line used for generation

I'm using gradle to generate the classes

```
tasks.create<GenerateTask>("generateEndpoint") {
	generatorName.set("kotlin-spring")
	inputSpec.set("${specsDir}/test.yaml")
	outputDir.set("${genDir}/something")
	apiPackage.set("${package}.api")
        invokerPackage.set("${package}.invoker")
	modelPackage.set("${package}.model")
	additionalProperties.set(mapOf("serviceInterface" to "true"))
}
```

##### Steps to reproduce

just call gradle task generate endpoints and build, after that you see three compile errors.

e: /home/.../api/ApiUtil.kt: (12, 16): Only safe (?.) or non-null asserted (!!.) calls are allowed on a nullable receiver of type HttpServletResponse?
e: /home/.../api/ApiUtil.kt: (13, 16): Only safe (?.) or non-null asserted (!!.) calls are allowed on a nullable receiver of type HttpServletResponse?
e: /home/.../api/ApiUtil.kt: (14, 16): Only safe (?.) or non-null asserted (!!.) calls are allowed on a nullable receiver of type HttpServletResponse?

##### Suggest a fix

fix mustache file: [apit-mustache](https://github.com/OpenAPITools/openapi-generator/blob/master/modules/openapi-generator/src/main/resources/kotlin-spring/apiUtil.mustache)

and add questionmarks

```
            res?.setCharacterEncoding("UTF-8")
            res?.addHeader("Content-Type", contentType)
            res?.getWriter()?.print(example)
```

**Comment by quackes** [comment] 2020-03-02 13:40
I encountered the same error. 
Still works with 4.2.1, but ApiUtil.kt is not generated.

I suspect the following PR to be the cause:
https://github.com/OpenAPITools/openapi-generator/pull/3925

**Comment by EivindAntonsen** [comment] 2020-03-29 12:57
In case this helps for anybody..

In the tasks with KotlinCompile, they come by default with strict compiler args. You can disable these like so:

```
tasks.withType<KotlinCompile> {
    dependsOn(generateTask)

    kotlinOptions {
        //freeCompilerArgs = listOf("-Xjsr305=strict")
        jvmTarget = "1.8"
    }
}
```

After that, the compiler wasn't as strict and the code was compiled.

**Comment by sylvainmoindron** [comment] 2020-04-28 07:06
I submitted a PR for fixing this bug #6084

**Comment by huehnerlady** [comment] 2020-05-27 15:08
Any update on this? We run into the same problem.

**Comment by sylvainmoindron** [comment] 2020-05-27 15:54
my PR has been reviewed but not yet merged in the master branch

**Comment by huehnerlady** [comment] 2020-05-28 05:57
@sylvainmoindron thanks, do you know why this is? I had a look and your branch was approved 25 days ago... 😞

**Closed** 2020-06-05 01:29 UTC
Labels: Issue: Bug

**Comment by huehnerlady** [comment] 2020-06-05 05:43
@jimschubert could you maybe estimate when this will be released?

**Comment by jimschubert** [comment] 2020-06-07 00:51
@huehnerlady we'll likely have a beta of 5.0 within the next few weeks. If you need this now, you could pull the latest docker image (it tracks master).

**Comment by huehnerlady** [comment] 2020-06-12 13:54
@jimschubert thanks for the info. I am using the gradle plugin, so not sure how I would do that with a docker image. I am happy to wait for a beta to come out to use it :)

**Comment by huehnerlady** [comment] 2020-06-30 09:19
@jimschubert I have seen that there is a beta of 5.0 out now. Will there also be a beta release for the gradle plugin soon, or can I use this generator version in the current gradle-plugin-version somehow? 

Many thanks

**Comment by shrralis** [comment] 2023-10-21 23:22
Hey!
The same `Only safe (?.) or non-null asserted (!!.) calls are allowed on a nullable receiver` error pops up for nullable `enum`s
A part of my OpenAPI spec:
```yaml
...
  /oauth2/token:
    post:
      tags:
      - authorization-server-endpoints
      parameters:
      - name: Authorization
        in: header
        schema:
          type: string
      requestBody:
        content:
          application/x-www-form-urlencoded:
            schema:
              type: object
              properties:
                grant_type:
                  type: string
                  enum:
                  - authorization_code
                  - refresh_token
                  - client_credentials
...
```
The generated code:
```kotlin
fun oauth2TokenPostRequestConfig(authorization: kotlin.String?, grantType: GrantTypeOauth2TokenPost?, code: kotlin.String?, redirectUri: kotlin.String?, refreshToken: kotlin.String?, scope: kotlin.String?, clientId: kotlin.String?, clientSecret: kotlin.String?, clientAssertionType: kotlin.String?, clientAssertion: kotlin.String?, additionalParameters: kotlin.collections.Map<kotlin.String, kotlin.String>?) : RequestConfig<Map<String, PartConfig<*>>> {
        val localVariableBody = mapOf(
            "grant_type" to PartConfig(body = grantType.value, headers = mutableMapOf()), // <-- the problem in this line, `grantType?.value` should be
            "code" to PartConfig(body = code, headers = mutableMapOf()),
```
