### ISSUE TITLE
[REQ] Handle list of String special case in webclient generator

### ISSUE THREAD

**Issue by dlicois** [OpenAPITools/openapi-generator#7118] opened 2020-08-03 15:31 UTC
### Is your feature request related to a problem? Please describe.

When describing an operation that returns an array of string, the openapi-generator for java-webclient generates an api returning a `Flux<String>`.

However Spring's Webclient handles serialization of JSON array of strings in a special way : spring-projects/spring-framework#22662

This means expecting a `Flux<String>` when a server return an array of String is a mistake.

Please see sample Gradle project https://github.com/dlicois/webclient-liststring, it contains a test class (WebClientListStringTest.java) to better explain the behaviour.
The `openapi.yaml` describes an operation returning an array of string, openapi-generator generates a `DefaultApi.java` class returning a `Flux<String>`.
When the webclient receive the answer `["one","two", "three"]`, it publishes a single String of value `["one","two", "three"]`.
I would have expected three Strings.

This makes the generated api unusable for this case, requiring to parse the response a second time to handle it.

## Describe the solution you'd like

Recommended solution by Spring developers (see spring-projects/spring-framework#22662 and https://docs.spring.io/spring/docs/current/spring-framework-reference/web-reactive.html#webflux-codecs-jackson) is to use a Mono<List<String>> for string arrays.

This would mean making a special case for operations described as arrays of string to generate a Mono<List<String>> instead of Flux<String>.

**Comment by bossqone** [comment] 2020-12-10 15:40
Same issue with java spring generator when `@RequestBody` is used with `Flux<String>` to parse json request `["a", "b", "c"]`.

**Comment by garzy** [comment] 2022-05-05 08:28
I'm having the same issue ¿won't be fixed yet in 2022? this issue was opened in 2020, please fix them

I'm generating WebClient code with the 5.4.0 version of open API-generator cli.

**Comment by yasammez** [comment] 2022-11-07 13:55
I can confirm the problem still exists in version `6.2.1` of openapi-generator. For now, the only option seems to be to wrap the array in a useless JSON object (that is, if you control the API as well as the implementation).

**Closed** 2023-08-15 05:53 UTC
Labels: Enhancement: Feature
