### ISSUE TITLE
[REQ] [dart] Migration to Dart 2.12

### ISSUE THREAD

**Issue by bartektartanus** [OpenAPITools/openapi-generator#8893] opened 2021-03-04 19:44 UTC
Dart 2.12 with sound null safety is now stable. Any plans to migrate?

**Comment by agilob** [comment] 2021-03-04 21:46
Duplicate of https://github.com/OpenAPITools/openapi-generator/issues/8278

**Closed by agilob** 2021-03-04 21:46 UTC
Labels: Client: Dart, Enhancement: Feature
