### ISSUE TITLE
[BUG] [JAVA] Java generation of 'extra' class with allOf

### ISSUE THREAD

**Issue by renskesterrenburg** [OpenAPITools/openapi-generator#3100] opened 2019-06-05 12:57 UTC
**Description**

I am using the pet store example to create java classes with inheritance. In the newest release (4.0.1) I found a bug. When I generate code with the OpenApi declaration file it generates an extra class.

![image](https://user-images.githubusercontent.com/44677507/58957311-a8526500-87a0-11e9-9f85-b9cbfe6281b5.png)

The class 'CatAllOf' I did not expect. It looks the same as 'Cat' except that it does not extends Pet.

**OpenAPI declaration file:**

```
openapi: 3.0.1
info:
  title: Article Event
  description: 'Article Event schema'
  version: 1.0.0
paths:
  /:
    get:
      responses:
        200:
          description: OK
          content: {}
components:
  schemas:
    TextChunk:
      type: object
      discriminator:
        propertyName: textChunkType
      properties:
        parent:
          type: string
    Dog:
      allOf: 
      - $ref: '#/components/schemas/TextChunk'
      - type: object
    Cat:
      allOf:
      - $ref: '#/components/schemas/TextChunk'
      - type: object
        properties:
          bark:
            type: string
```

**openapi-generator version**
I used the gradle plugin with version 4.0.1.

**older version**
I tested the same thing in the version 4.0.0-beta3 and there I did net see the 'extra' class. In other words, I got the expected behavior. It seems the bug was introduced with the latest release.

**Comment by msymonov** [comment] 2019-07-09 10:22
And it's not about presence of extra class only. The expected inheritance is missing as well.
It seems to me that the whole 4.x is affected

**Comment by gerardbosch** [comment] 2019-07-16 11:49
I'm with this issue as well. But when I have realized the generator working this way I asked myself if this was intended or really a weird bug. Could someone clarify it? I was pretty happy with 3.3.4 so I will go back to it for now. @wing328

**Comment by frankyjuang** [comment] 2019-08-30 09:06
Also happen in csharp client and server https://github.com/OpenAPITools/openapi-generator/issues/3338

**Comment by wing328** [comment] 2019-08-30 09:19
```
      - type: object
        properties:
          bark:
            type: string
```
That's treated as an inline schema (which can be replaced with $ref to avoid the additional model generation).

**Comment by valliman** [comment] 2019-09-03 15:20
The proposed solutions would lead to a file being generated for the inline schema again. That sounds a bit counter-intuitive. Why would I want to give the inline schema a dedicated name, if I didn't had the need before?

**Comment by valliman** [comment] 2019-10-22 09:39
@wing328 any comment on my post above? Is it possible to add the option to add the old behaviour?

**Comment by roxspring** [comment] 2019-11-11 10:14
> That's treated as an inline schema (which can be replaced with $ref to avoid the additional model generation).

This seems to miss the point entirely. Spec authors understand that these are inline schemas and are used *precisely* "to avoid the additional model generation". Replacing with a `$ref` necessitates the creation of the additional model that spec authors wish to avoid.

> If users prefer the old way of not generating this inline schema, technically we can add an option to restore the old behaviour.

It seems clear from the number of bugs raised in this area that many users do "prefer the old way". What I'm really not clear on is:

1. What benefits there are to "the new way" - i.e. whether it's worth keeping both ways as options
2. Where in the codebase I should be looking to patch in order to address the underlying problem

**Comment by nexen505** [comment] 2020-03-25 16:35
Still got this problem on 4.2.2.

**Comment by ahokkonen** [comment] 2020-04-09 09:15
This is also a behavior for .net generators. Still an issue in 4.3.0

**Comment by papegaaij** [comment] 2020-04-21 12:54
Even the examples have this issue. For example, the Java RestEasy example has several files with `AllOf`, like this one https://github.com/OpenAPITools/openapi-generator/blob/v4.3.0/samples/client/petstore/java/resteasy/src/main/java/org/openapitools/client/model/CatAllOf.java

These files are not used at all by the API. The only reference to this class is an unused import from `Cat` and the testcase `CatAllOfTest`. The same is true for the other `AllOf` classes.

**Comment by wing328** [comment] 2020-04-21 12:59
What about using `.openapi-generator-ignore` (in the output directory) to skip those files from being generated?

**Comment by papegaaij** [comment] 2020-04-21 13:06
@wing328 That seems like a strange solution to me. Why would I need to ignore files that shouldn't have been generated in the first place? Also, as I said, the classes are referenced by an unused import from other classes. Deleting the files, breaks the build.

**Comment by ahokkonen** [comment] 2020-04-21 13:14
> What about using `.openapi-generator-ignore` (in the output directory) to skip those files from being generated?

Great! Using .openapi-generator-ignore including "**/*AllOf.cs" for .net generation solves this!

**Comment by gerardbosch** [comment] 2020-04-22 10:22
Good news to listen about restoring to the original behavior. We rely upon inheritance that the `v3.x` provided, i.e. `Cat extends Animal` (or as per OP example `Cat extends TextChunk`).

**Comment by wing328** [comment] 2020-04-22 10:55
> We rely upon inheritance that the v3.x provided

That's not going to be restored. 

You will need to use `discriminator` for inheritance: https://github.com/OAI/OpenAPI-Specification/blob/master/versions/3.0.0.md#models-with-polymorphism-support

**Comment by sko-ob** [comment] 2020-05-01 01:32
> @wing328 That seems like a strange solution to me. Why would I need to ignore files that shouldn't have been generated in the first place? Also, as I said, the classes are referenced by an unused import from other classes. Deleting the files, breaks the build.

Facing the same issue here, where configuring the generator to ignore these AllOf files causes the unused imports not to compile... using Java here

**Comment by jharmelink** [comment] 2020-05-12 18:00
Can someone explain why these `*AllOf.java` files are being generated in the first place?

**Comment by gerardbosch** [comment] 2020-06-05 17:12
> 
> 
> > We rely upon inheritance that the v3.x provided
> 
> That's not going to be restored.
> 
> You will need to use `discriminator` for inheritance: https://github.com/OAI/OpenAPI-Specification/blob/master/versions/3.0.0.md#models-with-polymorphism-support

(Sorry for the bit delay...)

Sure @wing328 we use the `discriminator` to allow inheritance on model classes be generated (at least in the generator `v3.x`. But the whole point is that the `v4.x` does not generate the inheritance in the Java classes. So this is the behavior that was broken and that we would like to recover back.

Aside of that, and as others state, the new generated classes `*AllOf.java` in `v4.x` seems not useful at all and pollutes the generated artifact.

Is there any news for the `v5.x` you mentioned regarding this issue? Thanks!! 🙏 😃

**Comment by gerardbosch** [comment] 2020-08-13 15:33
@renskesterrenburg @wing328 (or any other with edit permission), Maybe the issue title should be updated to reflect the actual problem: [Java] Broken inheritance (and hence polimorphism). What do you think?

**Comment by gerardbosch** [comment] 2020-08-14 14:02
I've just realized that I have been confused on all my previous assertions regarding inheritance. The inheritance is not actually broken and seems never was (I've tried again with several generator versions 4.0, 4.02, 4.0.3, 4.1, 4.3.1) and Java inheritance is still fine. So I apologize if I introduced noise. I think other commenter stated the inheritance was broken as well.

So the actual problem is only about the extra unuseful `AllOf` generated classes (this ones are the ones that has no inheritance, but for the sake of the issue are the ones we want to remove).

The main point is that this pollutes the generated JAR with unnecessary, unused classes, so breaks the point of a sane API artifact.

I've just tried using the `.openapi-generator-ignore` file with `**/*AllOf.java` in `output` directory, and as others already said, classes are not generated, **BUT** the unused imports in other classes (say Cat.java) prevents the code to compile.

Maybe I could hack the POM of my generator (here using `openapi-generator-maven-plugin`) to remove all `^import.*AllOf;$` using sed or something similar but this is not the right way to go. Could work as a patch at most.

**Comment by gmcelhoe** [comment] 2020-08-26 00:51
>  the unused imports in other classes (say Cat.java) prevents the code to compile.
That seems like the most solvable problem -- if the generated file only imported classes it used, then the .openapi-generator-ignore trick would work.

**Comment by surmabck** [comment] 2020-08-26 12:00
As a workaround I can suggest adding `additionalProperties: true` to _child_ schema.  
For example, below would not generate additional CatAllOf.java
```   
Cat:
   allOf:
   - $ref: '#/components/schemas/TextChunk'
   - type: object
     additionalProperties: true
     properties:
       bark:
         type: string
```
That works because composed schema (allOf, oneOf, anyOf) that also defines `additionalProperties` are considered to be  a `MapSchema` and models are not generated for MapSchemas. 
I haven't encountered any problems so far with this solution so far, but I have not tested other generators

**Comment by gerlacdt** [comment] 2020-09-30 18:24
Are there any news about this? Is it on the roadmap for the upcoming 5.x release?

**Comment by milczarekIT** [comment] 2020-10-05 08:21
When you change from:
```
Cat:
      allOf:
      - $ref: '#/components/schemas/TextChunk'
      - type: object
        properties:
          bark:
            type: string
```

To:
```
Cat:
   type: object
   properties:
      bark:
         type: string   
   allOf:
      - $ref: '#/components/schemas/TextChunk'
      
```

So, if additional properties for `Cat` are added to the root of `Cat`, then there is no additional class `CatAllOf`

**Comment by skchande** [comment] 2020-10-06 08:53
Very nice Workaround @milczarekIT 
Does anyone know if this intended behaviour? I could not find any documentation for this.

**Comment by MattLichter** [comment] 2020-10-23 16:23
@milczarekIT Nice workaround.  It allowed me to generate the intended client code without the dummy classes (I'm using csharp-netcore 5.0.0-SNAPSHOT).

Does anyone know if this is still valid OpenAPI syntax though?  I haven't found any official examples with this structure.

**Comment by thobiaskarlsson** [comment] 2020-11-03 13:28
That is a nice workaround. Sadly for Java the "builder" methods does not work since they return the super type, e.g. 
```
Dog dog = new Dog().bark(true); // Ok since "bark" belongs to Dog
```
```
Pet dog = new Dog().bark(true).name("Doggie"); // Returns Pet (since "name" belongs to Pet), should return Dog
```
I've tried so many different patterns but none of them work for Java inheritance, this was the closest though, but I can't live with:
```
Dog dog = (Dog) new Dog().bark(true).name("Doggie");
```
nor...
```
Dog dog = new Dog().bark(true);
dog.name("Doggie"); // <- Pet
```
nor...
```
Dog dog = new Dog();
dog.setBark(true);
dog.setName("Doggie");
```
A simple override of the builder methods would suffice I believe, e.g. 
```
@Override
public Dog name(String name) {
  return (Dog) super.name(name);
}
```
Then this workaround would be very acceptable imo.

**Comment by stapel** [comment] 2021-03-03 13:22
There's the same problem with kotlin and kotlin-server (in 5.0.1)

**Comment by mizolight** [comment] 2021-03-30 17:48
@wing328 why can't you just have the old behavior? I think a lot of folks are disappointed with the new behavior. We are supposed to make things better not worse. 

Thanks!

**Comment by phirzel** [comment] 2021-04-11 09:39
Since I annotate the @Schema directly in my java code and even generate openapi.yml out of it, I cannot influence the positioning of :allOf ref much (as in the nice hack above ;-)
Therefore I created another silly hack class **CatAllOf** to please the non-understandable import without being used in the generated class code at all, just like:

```
package pet.model;
/**
 * Just an unnecessary generated "import" compiler workaround class
 * @see <a href="https://github.com/OpenAPITools/openapi-generator/issues/3100">*AllOf imports</a>
 * @see Cat
 */
@Deprecated
public class CatPlaceAllOf {}
```

To OpenApi developers:
* I suggest you clean up generated code within the plugin (for e.g. like IntellJ's feature to remove unneccessary imports), that would do it in that case (as a quick fix)
* of course such usage for code continuous quality comparison of generated code, would be more handy
* I can follow the missunderstandings above, but I did not found any explanation, whether it is ok to remove the "silly import" or if there is another fault in my annotation or in the generated code

Thanks for fixing soon and appreciate your work!

**Comment by rgoers** [comment] 2021-06-13 07:17
I am not sure what the status is of this. I have specified

`    OrganizationPage:
      type: object
      allOf:
        - $ref: '#/components/schemas/BasePage'
      properties:
        data:
          type: array
          items:
            $ref: '#/components/schemas/Organization'`

OrganizationPage must be an instance of BasePage but it is not. instead all the properties from BasePage are included in BasePage. If this syntax no longer causes inheritance what is the new spec format that does?

**Comment by gerardbosch** [comment] 2021-06-13 10:54
@rgoers the corrent form should be something like this https://github.com/OpenAPITools/openapi-generator/issues/3100#issuecomment-703481081

**Comment by rgoers** [comment] 2021-06-13 18:07
I tried

    OrganizationPage:
      allOf:
        - $ref: '#/components/schemas/BasePage'
        - type: object
          properties:
            data:
              type: array
              items:
                $ref: '#/components/schemas/Organization'

and 

    OrganizationPage:
      type: object
      properties:
        data:
          type: array
          items:
            $ref: '#/components/schemas/Organization'
      allOf:
        - $ref: '#/components/schemas/BasePage'

they both ended up with

    public class OrganizationPage  implements Serializable {

instead of 

    public class OrganizationPage extends BasePage implements Serializable {

which is what I really need. However, the format that has everything under the allof element also generates a class named OrganizationPageAllOf as 

    public class OrganizationPageAllOf  implements Serializable 

but this class has none of the attributes from BasePage and doesn't extend it so it is unusable for anything.

So what do I need to do to get OrganizationPage to extend BasePage?

**Comment by ntroutman** [comment] 2022-01-14 18:04
Still seeing this as an issue. Interestingly the swagger-codegen doesn't produce these extra files.

**Comment by efriandika** [comment] 2022-07-06 19:28
It's been 3 years, this issue is still open. the swagger-codegen doesn't produce this extra files. But why openapi-generator still produce this extra files? 

Could you please give us explanation / insight wether these extra files useful or no @wing328 ?

**Comment by wing328** [comment] 2022-09-22 13:41
I've filed https://github.com/OpenAPITools/openapi-generator/pull/13498 to improve how the allOf inline schemas are created. Please give it a try as follows:
```
git clone -b inline-schema-improve3 https://github.com/OpenAPITools/openapi-generator
cd openapi-generator
mvn clean package
java -jar modules/openapi-generator-cli/target/openapi-generator-cli.jar generate -g java  -i /var/tmp/your_spec.yaml -o /var/tmp/java/
```

I tested with java, csharp-netcore and the result is good - no longer seeing those *AllOf files created.

**Comment by wing328** [comment] 2022-09-24 02:20
Tagging @msymonov @gerardbosch @yilinjuang @valliman @roxspring @nexen505 @ahokkonen @papegaaij @sko-ob @jharmelink @gmcelhoe @surmabck @gerlacdt @milczarekIT @MattLichter @thobiaskarlsson @stapel @mizolight @phirzel @rgoers @ntroutman @efriandika  to review the PR 🙏 

Have a nice weekend.

**Comment by pfconrey** [comment] 2023-02-27 16:00
Is there any hope of getting the fix into the main release any time soon?

**Comment by pfconrey** [comment] 2023-05-19 21:50
> I've filed #13498 to improve how the allOf inline schemas are created. Please give it a try as follows:
> 
> ```
> git clone -b inline-schema-improve3 https://github.com/OpenAPITools/openapi-generator
> cd openapi-generator
> mvn clean package
> java -jar modules/openapi-generator-cli/target/openapi-generator-cli.jar generate -g java  -i /var/tmp/your_spec.yaml -o /var/tmp/java/
> ```
> 
> (if you're using mvn wrapper that comes with the project, just replace `mvn` with `mvnw` (Mac/Linux) or `mvnw.cmd` (Windows))
> 
> I tested with java, csharp-netcore and the result is good - no longer seeing those *AllOf files created.

The problem still occurs in the plugin. When merging together 2 YAML files, one of which has an allOf object, the resulting YAML file still has the 3 objects (Object1, Object2, Object2_allOf)

**Comment by wing328** [comment] 2023-06-11 07:36
Closed via https://github.com/OpenAPITools/openapi-generator/pull/15682

Please pull the latest master to give it a try.

**Closed** 2023-06-11 07:36 UTC
Labels: Issue: Bug
