### ISSUE TITLE
[BUG] [typescript-fetch] v4.3.1 introduced "Module has no exported member 'AnyType"

### ISSUE THREAD

**Issue by gnuletik** [OpenAPITools/openapi-generator#6273] opened 2020-05-12 17:38 UTC
#### Bug Report Checklist

- [x] Have you provided a full/minimal spec to reproduce the issue?
- [x] Have you validated the input using an OpenAPI validator ([example](https://apidevtools.org/swagger-parser/online/))?
- [x] What's the version of OpenAPI Generator used?
- [x] Have you search for related issues/PRs?
- [x] What's the actual output vs expected output?
- [ ] [Optional] Bounty to sponsor the fix ([example](https://www.bountysource.com/issues/66123212-javascript-client-produces-a-wrong-object-for-a-string-enum-type-that-is-used-with-ref))

##### Description

Starting from openapi-generator v4.3.1 and using the typescript-fetch, the following error occurs when compiling the generated typescript code:
```
> tsc

src/apis/DefaultApi.ts:18:5 - error TS2305: Module '"../models"' has no exported member 'AnyType'.

18     AnyType,
       ~~~~~~~

src/apis/DefaultApi.ts:19:5 - error TS2305: Module '"../models"' has no exported member 'AnyTypeFromJSON'.

19     AnyTypeFromJSON,
       ~~~~~~~~~~~~~~~

src/apis/DefaultApi.ts:20:5 - error TS2305: Module '"../models"' has no exported member 'AnyTypeToJSON'.

20     AnyTypeToJSON,
       ~~~~~~~~~~~~~


Found 3 errors.
```

##### openapi-generator version

Using openapi-generator v4.3.1 and typescript-fetch.
This is a regression as I was not able to reproduce it on v4.3.0

##### OpenAPI declaration file content or url

```yaml
# openapi.yml
openapi: 3.0.2
info:
  title: Example API
  version: 1.0.0
paths:
  /some-working-route/:
    get:
      operationId: listWorking
      description: ''
      parameters: []
      responses:
        '200':
          content:
            application/json:
              schema:
                type: object
                properties:
                  id:
                    type: integer
                  name:
                    type: string
          description: ''
  /some-failing-route/:
    get:
      operationId: listFailing
      description: ''
      parameters: []
      responses:
        '200':
          content:
            application/json:
              schema:
                type: array
                items: {}
          description: ''
servers:
  - url: http://localhost
```

##### Command line used for generation

```yaml
# config.yml

typescriptThreePlus: true
npmName: some-example
npmVersion: '1.0.0'
```

```bash
docker run --rm \
    -v ${PWD}:/local
    --user "$(id -u):$(id -g)" \
    openapitools/openapi-generator-cli:v4.3.1 generate \
        -i /local/openapi.yml \
        -g typescript-fetch \
        -c /local/config.yml \
        -o /local/dist
```
##### Steps to reproduce

- Download `openapi.yml` and `config.yml` pasted above.
- Run the docker command pasted above
- `cd dist`
- `npm install` to install typescript and run `tsc` (because `tsc` is called in the post-install script in the `package.json` file)

##### Related issues/PRs

Seems to be linked to this PR : https://github.com/OpenAPITools/openapi-generator/pull/6091

##### Suggest a fix

The previous version set the type of empty object as `object`. 
It may be linked to @mwilby proposal on the PR:
>         typeMapping.put("AnyType", "object");

**Comment by mboutet** [comment] 2020-05-13 00:40
Same problem with the python-flask generator

**Comment by sergiofigueras** [comment] 2020-05-17 19:12
Same thing happening with Kotlin generator.

**Comment by macjohnny** [comment] 2020-05-19 11:49
duplicate of https://github.com/OpenAPITools/openapi-generator/issues/6332

**Closed by macjohnny** 2020-05-19 11:49 UTC
Labels: Client: TypeScript, Issue: Bug
