### ISSUE TITLE
[BUG] $ref to common parameter not being resolved

### ISSUE THREAD

**Issue by john3300** [OpenAPITools/openapi-generator#1714] opened 2018-12-19 16:41 UTC
##### Description

Validation is failing to resolve a `$ref` in the parameter list to a common parameter defined outside the operation.  Neither refs local to the same file nor refs to external files work.  Both should.  I've tried it with both Swagger 2.0 and OAS 3.0 specs, both fail the same way.
```
Exception in thread "main" org.openapitools.codegen.SpecValidationException: There were issues with the specification. The option can be disabled via validateSpec (Maven/Gradle) or --skip-validate-spec (CLI).
 | Error count: 1, Warning count: 0
Errors: 
	-attribute paths.'/employees/{id}'. Declared path parameter id needs to be defined as a path parameter in path or operation level

	at org.openapitools.codegen.config.CodegenConfigurator.toClientOptInput(CodegenConfigurator.java:569)
	at org.openapitools.codegen.cmd.Generate.run(Generate.java:346)
	at org.openapitools.codegen.OpenAPIGenerator.main(OpenAPIGenerator.java:62)
```

##### openapi-generator version

4.0.0-SNAPSHOT

##### OpenAPI declaration file content or url

```yaml
openapi: 3.0.0
info:
  title: Test
  description: Test YAML
  version: '1.0'
servers:
  - url: http://localhost
paths:
  /employees/{id}:
    get:
      operationId: getEmployeeById
      parameters:
        - $ref: '#/components/parameters/id'
      responses:
        200:
          description: Success
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/employee'
components:
  schemas:
    employee:
      type: object
      properties:
        name:
          type: string
      required:
        - name
  parameters:
    id:
      name: id
      in: path
      required: true
      schema:
        type: string
```

##### Command line used for generation

`java -jar openapi-generator-cli-4.0.0-20181217.102953-101.jar generate -g html -i test.yaml`

##### Related issues/PRs

#455 seems to be related.  But that one was resolved.  So that makes this a regression.

##### Suggest a fix

This could be another issue with the `swagger-parser` like in #455.

**Comment by john3300** [comment] 2018-12-19 16:46
I can't see how to add a label to this issue, but I think it should also have `Issue: Regression`

**Comment by jimschubert** [comment] 2018-12-19 20:34
@john3300 Did this work with another tool or a previous version of the generator? It seems to me this is an issue with swagger parser.

If it previously worked, can you provide the previous version of openapi-generator so we can look at the regression?

**Comment by john3300** [comment] 2018-12-20 16:32
It works fine with 3.3.4.

**Comment by ericraymond** [comment] 2018-12-26 23:52
FYI if you expand the ref the issue goes away (not that it helps much):

```openapi: 3.0.0
info:
  version: 1.0.0
  title: |
    This fails to generate code when the path paramter is defined via schema $ref
     - attribute paths.'/bar/{id}'. Declared path parameter id needs to be defined as a path parameter in path or operation level

paths:
  '/foo/{id}':
    get:
      summary: Returns the foo of a prior request
      operationId: fooGet
      parameters:
        -
          name: id
          in: path
          required: true
          description: ID returned from a prior POST operation of the same name
          schema:
            type: string
      responses:
        '200':
          description: A list of predicted text boxes
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/FooBarResponse'
  '/bar/{id}':
    get:
      summary: Returns the bar of a prior request
      operationId: barGet
      parameters:
        - $ref: '#/components/parameters/ID'
      responses:
        '200':
          description: A list of predicted text boxes
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/FooBarResponse'

components:
  parameters:
    ID:
      name: id
      in: path
      required: true
      description: ID returned from a prior POST operation of the same name
      schema:
        type: string
  schemas:
    FooBarResponse:
      type: object
      properties:
        foo:
          type: string
        bar:
          type: string

```

**Comment by wing328** [comment] 2018-12-30 10:08
@john3300 can you try with `--skip-validate-spec`? I tried to repeat the issue with the spec you provided but couldn't after using the `--skip-validate-spec` option.

**Comment by ericraymond** [comment] 2018-12-31 20:34
Above test file works via the gradle plugin with validateSpec =  false.  It complains about the error, but seems to continue.  

Larger test case is failing on another issue.   This test case would further test the generated code.   Will investigate and comment/log bugs as necessary.

**Comment by advance512** [comment] 2019-01-07 19:56
I can confirm this happens with 4.0.0 nightly and JavaScript generator.

I like the validation, so we'll wait until it is working before migrating to 4.0.0.

**Comment by jjlin** [comment] 2019-01-10 01:30
> @john3300 Did this work with another tool or a previous version of the generator? It seems to me this is an issue with swagger parser.
> 
> If it previously worked, can you provide the previous version of openapi-generator so we can look at the regression?

This issue was carried over from https://github.com/swagger-api/swagger-parser/issues/911.

Upstream has an open PR: https://github.com/swagger-api/swagger-parser/pull/977

**Comment by GeneticGenesis** [comment] 2019-01-16 13:02
I assume this happens in all client generators - maybe we can remove the `client:HTML` tag?

**Comment by wing328** [comment] 2019-01-16 14:13
> Obviously that's not a valid long term solution for something that worked in the previous release.

@john3300 please use `--skip-validate-spec` for the time being until the issue (false alarm) is addressed in the swagger parser.

**Comment by wing328** [comment] 2019-01-16 14:14
@GeneticGenesis done

**Comment by fantavlik** [comment] 2019-02-01 17:58
I believe this could be the fix? Hoping it gets merged soon. https://github.com/swagger-api/swagger-parser/pull/977

**Comment by tcjcodes** [comment] 2019-02-12 01:27
This seems to fail when `in: path` but `in: query` params will work.

The workaround for gradle works: `openApiGenerate { .... validateSpec = false }`

**Comment by GeneticGenesis** [comment] 2019-02-20 11:00
https://github.com/swagger-api/swagger-parser/pull/977 has now been merged into master of swagger-parser. 

Can we pull in the latest swagger-parser and re-test?

Thanks

**Comment by ntfrnzn** [comment] 2019-02-26 20:53
https://github.com/swagger-api/swagger-parser/tree/v2.0.9 is released & should be incorporated.

**Comment by wing328** [comment] 2019-03-29 16:21
Please try the latest master with the upgrade parser to see if it's still an issue.

**Closed by wing328** 2019-03-29 16:21 UTC
Labels: Issue: Non-operational, Issue: Workaround available, Swagger-Parser

**Comment by GeneticGenesis** [comment] 2019-04-03 14:40
This seems to have fixed this specific issue, but sadly ref'd parameters have now been broken by https://github.com/swagger-api/swagger-parser/issues/1063

**Comment by advance512** [comment] 2019-04-03 15:05
@GeneticGenesis 

What do you mean when you say "now been broken"? You are referencing a different project. 

Maybe you mean to say "this fix has exposed an older problem that was hidden" or something like that?

**Comment by GeneticGenesis** [comment] 2019-04-03 15:09
Sorry I should be more clear @advance512:

Using parameters which involves refs was previously broken by swagger-api/swagger-parser#911 which was fixed by pulling in the upstream change in swagger-parser.

Using parameters which involves refs is now broken because of another issue in swagger-parser - swagger-api/swagger-parser#1063 which is not yet fixed upstream, so if you're using refs under path parameters, you still have to disable verification on master (and V4 betas) of openapi-generator.

**Comment by lacksfish** [comment] 2019-04-25 09:47
Having a similar issue:
```
/random/api_endpoint:
    get:
        parameters:
            - $ref: '#/parameters/some_param'
```
When automatically generating the code for it, the parameters get omitted and the produced functions take no arguments... Troublesome. `:parameters` is defined in the root beginning of the same spec document. None of the `$ref` params make it into the autogenerated code, all methods just have no params if using `$ref` for the params.

I get a lot of those here when skipping validation as well (may be a separate issue):

```
[main] WARN  o.o.codegen.utils.ModelUtils - #/components/schemas/types/something_name is not defined
```

**Comment by GeneticGenesis** [comment] 2019-04-25 09:50
I believe the new issue is now fixed upstream in https://github.com/swagger-api/swagger-parser/issues/1063

It looks like they cut release 2.0.12 of swagger-parser 18 hours ago with these fixes, so hopefully this can get bumped here soon.

**Comment by lacksfish** [comment] 2019-04-25 10:27
Definitely sounds like my issue.

So I should update `<swagger-parser-version>2.0.11-OpenAPITools.org-1</swagger-parser-version>` in `pom.xml` to 2.0.12 version once available? Or can I monkeypatch the version right now?

**Comment by lacksfish** [comment] 2019-04-29 12:13
@wing328 Since this issue is closed, is there another ticket to refer to? Waiting or the updated swagger parser.

**Comment by lacksfish** [comment] 2019-05-03 12:51
"I got my eyes on you~" 🎶

https://github.com/OpenAPITools/swagger-parser/tags

**Comment by fantavlik** [comment] 2019-05-08 00:01
For those following this issue or https://github.com/OpenAPITools/openapi-generator/issues/2631, swagger-parser was updated: https://github.com/OpenAPITools/openapi-generator/pull/2775 and I've confirmed that the `validate` function is no longer returning erroneous `There are duplicate parameter values` messages. So https://github.com/swagger-api/swagger-parser/issues/1063 has now been fixed in openapi-generator. 🎉

**Comment by lacksfish** [comment] 2019-05-13 12:01
This might be only a symptom of a greater issue, so for the impatient:

To fix my problem, I've used https://github.com/APIDevTools/json-schema-ref-parser (after turning my main yaml spec into json) and de-referenced all the `$ref`'s automatically with the aforementioned tool.

Then, I was able to generate the client code :)

PSA: This is a hotfix and any code generated should be well tested.

**Comment by GeneticGenesis** [comment] 2019-05-13 14:30
@lacksfish Interesting... I'm using `swagger-cli bundle` to do the bundling and dereferencing today, but still run into issues.

I'll take a look at the tool you linked, thanks!

**Comment by ragazzojp** [comment] 2019-07-22 15:48
I can still reproduce this problem with 4.0.3. @wing328 , can we please reopen it?

**Comment by ghacupha** [comment] 2020-02-13 09:02
Experienced this issue once when I was running an application with openjdk 8 update 41 RI. I then changed the environment to use oracle jdk 8 update 202 ( 1.8.0_202), and that fixed the problem. My guess: missing schemas in your jdk?

**Comment by sumanthakannantha** [comment] 2022-11-23 15:18
This issue is still visible with the latest version.
