### ISSUE TITLE
[BUG] [Swift] Generating/Calling NSDecimalString function crashes the Swift compiler

### ISSUE THREAD

**Issue by borsosbe** [OpenAPITools/openapi-generator#19459] opened 2024-08-27 06:26 UTC
##### Description

NSDecimalString generation causing a complier error after xCode beta 5 and 6.

The following code that calls NSDecimalString crashes the compiler with the message:

SILFunction type mismatch for 'NSDecimalString': '$@convention(c) (UnsafePointer, Optional) -> @autoreleased Optional' != '$@convention(c) (UnsafePointer, Optional) -> @autoreleased NSString'

https://github.com/swiftlang/swift/issues/75752

See the issue in swift language repo. If the new xCode 16 stays that way, openapi should change is generation. There is a workaround on the issue which works.
It is currently a problem regardless of the beta, since developers have to adapt the new xCode beta to prepare for iOS 18 which is coming out soon.

##### openapi-generator version

7.8

##### Generation Details

openapi-generator generate \
    -i etc/xxxyaml \
    -g swift5 \
    -o Sources/Packages/XXX \
    --global-property models,supportingFiles,modelDocs=false \
    --model-name-suffix=DTO \
    --additional-properties=projectName= XXX,swiftPackagePath=Sources,removeMigrationProjectNameClass=true

##### Suggest a fix

Problematic generation:
`extension KeyedEncodingContainerProtocol {
    public mutating func encode(_ value: Decimal, forKey key: Self.Key) throws {
        var mutableValue = value
        let stringValue = NSDecimalString(&mutableValue, Locale(identifier: "en_US"))
        try encode(stringValue, forKey: key)
    }
}`

Workaround:
` extension KeyedEncodingContainerProtocol {
    public mutating func encode(_ value: Decimal, forKey key: Self.Key) throws {
        let decimalNumber = NSDecimalNumber(decimal: value)
        let numberFormatter = NumberFormatter()
        numberFormatter.numberStyle = .decimal
        numberFormatter.locale =  Locale(identifier: "en_US")
        let formattedString = numberFormatter.string(from: decimalNumber) ?? "\(value)"
        try encode(formattedString, forKey: key)
    }
}`

**Comment by aehlke** [comment] 2024-08-29 07:21
please share the change as a PR, I'd love to have this... thanks

**Comment by borsosbe** [comment] 2024-08-29 11:10
@aehlke Just generate your stuff that you normally do. Look for `NSDecimalString ` in the generated code and implement the workaround from the example.

**Comment by r3econ** [comment] 2024-09-04 15:39
We are experiencing the same problem. The issue is critical 🔴

**Comment by aehlke** [comment] 2024-09-04 15:54
> We are experiencing the same problem. The issue is critical 🔴 

It has an easy workaround so I wouldn't call it critical at least - just drop in a template replacement

**Comment by lilidotshi** [comment] 2024-09-06 18:15
Would also like to see a fix for this as we would like to rely on not having to update our generated code manually for CI.

**Comment by aehlke** [comment] 2024-09-07 19:45
> Would also like to see a fix for this as we would like to rely on not having to update our generated code manually for CI.

You don't need to manually change anything - override the specific template file in your automation

**Comment by lilidotshi** [comment] 2024-09-10 22:38
@aehlke I opened up a PR with the changes that @borsosbe suggested here if you wanted to take a look. https://github.com/OpenAPITools/openapi-generator/pull/19564

**Comment by 4brunu** [comment] 2024-10-30 09:34
I'm closing this issue, as this should now be fixed, if the issue is still present, please reopen this issue.
Thanks

**Closed by 4brunu** 2024-10-30 09:34 UTC
Labels: Issue: Bug
