### ISSUE TITLE
[BUG] [csharp-netcore] When requestBody has OneOf, then it generates client with "UNKNOWN_BASE_TYPE"

### ISSUE THREAD

**Issue by prajon84** [OpenAPITools/openapi-generator#9788] opened 2021-06-16 16:10 UTC
#### Bug Report Checklist

- [x] Have you provided a full/minimal spec to reproduce the issue?
- [x] Have you validated the input using an OpenAPI validator ([example](https://apidevtools.org/swagger-parser/online/))?
- [x] Have you [tested with the latest master](https://github.com/OpenAPITools/openapi-generator/wiki/FAQ#how-to-test-with-the-latest-master-of-openapi-generator) to confirm the issue still exists?
- [x] Have you searched for related issues/PRs?
- [x] What's the actual output vs expected output?
- [ ] [Optional] Sponsorship to speed up the bug fix or feature request ([example](https://github.com/OpenAPITools/openapi-generator/issues/6178))

##### Description

When the requestBody has `oneOf` properties, then the client is generated with `UNKNOWN_BASE_TYPE` as a request parameter.

##### openapi-generator version

master @ https://github.com/OpenAPITools/openapi-generator/commit/e600f7d149df999c7a549ba0b467658f87e0acec

##### OpenAPI declaration file content or url

```yaml
openapi: 3.0.3
info:
  title: C# Object with requestBody has oneOf
  version: v1
paths:
  '/hello':
    patch:
      responses:
        '200':
          description: returns compared object
          content:
            application/json:
              schema:
                type: string
      requestBody:
        required: true
        content:
          application/json:
            schema:
              oneOf:
                - type: string
                - type: integer
```

##### Steps to reproduce

```
>openapi-generator generate -g csharp-netcore -i openapi.yaml --library httpclient -o out/requestBody_with_oneOf/ --model-package Model --api-package Api

>cd out/requestBody_with_oneOf
>dotnet build --configuration Release
```

produces:

```
C:\Projects\ssh_clone\try-for-openapi-issue\requestBody_with_oneOf\src\Org.OpenAPITools\Api\DefaultApi.cs(299,34): error CS0246: The type or namespace name 'UNKNOWN_BASE_TYPE' could not be found (are you missing a using directive or an assembly reference?) [C:\Projects\ssh_clone\try-for-openapi-issue\requestBody_with_oneOf\src\Org.OpenAPITools\Org.OpenAPITools.csproj]
C:\Projects\ssh_clone\try-for-openapi-issue\requestBody_with_oneOf\src\Org.OpenAPITools\Api\DefaultApi.cs(36,27): error CS0246: The type or namespace name 'UNKNOWN_BASE_TYPE' could not be found (are you missing a using directive or an assembly reference?) [C:\Projects\ssh_clone\try-for-openapi-issue\requestBody_with_oneOf\src\Org.OpenAPITools\Org.OpenAPITools.csproj]
C:\Projects\ssh_clone\try-for-openapi-issue\requestBody_with_oneOf\src\Org.OpenAPITools\Api\DefaultApi.cs(311,83): error CS0246: The type or namespace name 'UNKNOWN_BASE_TYPE' could not be found (are you missing a using directive or an assembly reference?) [C:\Projects\ssh_clone\try-for-openapi-issue\requestBody_with_oneOf\src\Org.OpenAPITools\Org.OpenAPITools.csproj]
C:\Projects\ssh_clone\try-for-openapi-issue\requestBody_with_oneOf\src\Org.OpenAPITools\Api\DefaultApi.cs(67,61): error CS0246: The type or namespace name 'UNKNOWN_BASE_TYPE' could not be found (are you missing a using directive or an assembly reference?) [C:\Projects\ssh_clone\try-for-openapi-issue\requestBody_with_oneOf\src\Org.OpenAPITools\Org.OpenAPITools.csproj]
C:\Projects\ssh_clone\try-for-openapi-issue\requestBody_with_oneOf\src\Org.OpenAPITools\Api\DefaultApi.cs(47,52): error CS0246: The type or namespace name 'UNKNOWN_BASE_TYPE' could not be found (are you missing a using directive or an assembly reference?) [C:\Projects\ssh_clone\try-for-openapi-issue\requestBody_with_oneOf\src\Org.OpenAPITools\Org.OpenAPITools.csproj]
C:\Projects\ssh_clone\try-for-openapi-issue\requestBody_with_oneOf\src\Org.OpenAPITools\Api\DefaultApi.cs(79,86): error CS0246: The type or namespace name 'UNKNOWN_BASE_TYPE' could not be found (are you missing a using directive or an assembly reference?) [C:\Projects\ssh_clone\try-for-openapi-issue\requestBody_with_oneOf\src\Org.OpenAPITools\Org.OpenAPITools.csproj]
C:\Projects\ssh_clone\try-for-openapi-issue\requestBody_with_oneOf\src\Org.OpenAPITools\Api\DefaultApi.cs(356,74): error CS0246: The type or namespace name 'UNKNOWN_BASE_TYPE' could not be found (are you missing a using directive or an assembly reference?) [C:\Projects\ssh_clone\try-for-openapi-issue\requestBody_with_oneOf\src\Org.OpenAPITools\Org.OpenAPITools.csproj]
C:\Projects\ssh_clone\try-for-openapi-issue\requestBody_with_oneOf\src\Org.OpenAPITools\Api\DefaultApi.cs(369,123): error CS0246: The type or namespace name 'UNKNOWN_BASE_TYPE' could not be found (are you missing a using directive or an assembly reference?) [C:\Projects\ssh_clone\try-for-openapi-issue\requestBody_with_oneOf\src\Org.OpenAPITools\Org.OpenAPITools.csproj]
```

##### Related issues/PRs

None that I could find.

##### Suggest a fix

@wing328 @Blackclaws @shibayan @lucamazzanti @devhl-labs @jfeltesse-mdsol

**Comment by jfeltesse-mdsol** [comment] 2021-06-17 03:58
Probably related to https://github.com/OpenAPITools/openapi-generator/issues/5903

The root cause is in the generator core itself and as such affects multiple languages.

**Comment by wing328** [comment] 2022-05-13 02:36
This should be fixed via https://github.com/OpenAPITools/openapi-generator/pull/12353. Please pull the latest master to give it a try.

Happy to reopen this issue if needed.

**Closed by wing328** 2022-05-13 02:36 UTC
Labels: Issue: Bug
