### ISSUE TITLE
[BUG] [python-experimental] Can't load config class with name 'python-experimental'

### ISSUE THREAD

**Issue by MalteEbner** [OpenAPITools/openapi-generator#11285] opened 2022-01-12 09:52 UTC
#### Bug Report Checklist

- [x] Have you [tested with the latest master](https://github.com/OpenAPITools/openapi-generator/wiki/FAQ#how-to-test-with-the-latest-master-of-openapi-generator) to confirm the issue still exists?
- [x] Have you searched for related issues/PRs?

##### Description

Using python-experimental fails with 

```
Can't load config class with name 'python-experimental'
Available:
ada
ada-server
...
protobuf-schema
python-legacy
python
python-fastapi
python-flask
python-aiohttp
python-blueplanet
r
...
wsdl-schema

[error] Check the spelling of the generator's name and try again.
```

##### openapi-generator version
version: 5.3.1
installed with `npm install -g @openapitools/openapi-generator-cli`

##### Steps to reproduce

Run `openapi-generator-cli generate -i $PATH_TO_SPEC -g python` such that it works.
Then switch to `openapi-generator-cli generate -i $PATH_TO_SPEC -g python-experimental`.

##### Suggest a fix
@spacether Do you know how to fix this?

**Comment by spacether** [comment] 2022-01-12 19:14
Closing this because it's not a bug; new generators don't exist in older releases.

**Closed by spacether** 2022-01-12 19:14 UTC
Labels: Issue: Bug
