### ISSUE TITLE
[BUG][MARKDOWN] Method descriptions are missing from README.md

### ISSUE THREAD

**Issue by zeljkot** [OpenAPITools/openapi-generator#6103] opened 2020-04-29 08:09 UTC
##### Description

Method descriptions are missing from README.md

Example: warningsGet has description in YAML, but not in MD.
```markdown
Class | Method | HTTP request | Description
------------ | ------------- | ------------- | -------------
*WarningsApi* | [**warningClearMultiple**](Apis/WarningsApi.md#warningclearmultiple) | **POST** /v1/warnings/cleared | 
*WarningsApi* | [**warningGet**](Apis/WarningsApi.md#warningget) | **GET** /v1/warnings/list/{id} | 
*WarningsApi* | [**warningUsers**](Apis/WarningsApi.md#warningusers) | **GET** /v1/warnings/users | 
*WarningsApi* | [**warningsGet**](Apis/WarningsApi.md#warningsget) | **GET** /v1/warnings/list | 
```

##### openapi-generator version

4.3.0

##### OpenAPI declaration file content or url

[bug.zip](https://github.com/OpenAPITools/openapi-generator/files/4550445/bug.zip)

##### Command line used for generation

```xml
<groupId>org.openapitools</groupId>
<artifactId>openapi-generator-maven-plugin</artifactId>
<version>4.3.0</version>
<executions>
  <execution>
    <id>markdown</id>
```

`mvn clean compile`

##### Steps to reproduce

Add descriptions to methods.

##### Suggest a fix

**Comment by ybelenko** [comment] 2020-04-30 08:05
Default template uses `summary` prop for description column. And I agree with you that it's a bit confusing, but short messages are better for table views so `summary` prop seems like a best fit.

You can edit `README.mustache` template to show full `descriptions` in a way:

```diff
diff --git a/modules/openapi-generator/src/main/resources/markdown-documentation/README.mustache b/modules/openapi-generator/src/main/resources/markdown-documentation/README.mustache
index 221d492557..05b4345a5a 100644
--- a/modules/openapi-generator/src/main/resources/markdown-documentation/README.mustache
+++ b/modules/openapi-generator/src/main/resources/markdown-documentation/README.mustache
@@ -8,7 +8,7 @@ All URIs are relative to *{{{basePath}}}*
 
 Class | Method | HTTP request | Description
 ------------ | ------------- | ------------- | -------------
-{{#apiInfo}}{{#apis}}{{#operations}}{{#operation}}*{{classname}}* | [**{{operationId}}**](Apis/{{apiDocPath}}{{classname}}.md#{{operationIdLowerCase}}) | **{{httpMethod}}** {{path}} | {{#summary}}{{{summary}}}{{/summary}}
+{{#apiInfo}}{{#apis}}{{#operations}}{{#operation}}*{{classname}}* | [**{{operationId}}**](Apis/{{apiDocPath}}{{classname}}.md#{{operationIdLowerCase}}) | **{{httpMethod}}** {{path}} | {{#notes}}{{notes}}{{/notes}}
 {{/operation}}{{/operations}}{{/apis}}{{/apiInfo}}
 {{/generateApiDocs}}
```

I think that I can close this, because it's obviously not a bug.

**Comment by zeljkot** [comment] 2020-04-30 13:12
Is that documented?
Can you show a description if a summary is missing?

**Comment by zeljkot** [comment] 2020-04-30 13:33
Maybe it is just me, but as *description* exists on all elements while *summary* only exists on some, I tend to write just *description* so I do not have to think what to write where. That is why I think it would be practical to have *description* as a fallback.

**Comment by ybelenko** [comment] 2020-04-30 14:04
@zeljkot 

> Is that documented?

Well it's not documented specifically, [Mustache Template Variables](https://github.com/OpenAPITools/openapi-generator/wiki/Mustache-Template-Variables) article is best I found. You can check out official Mustaches docs to learn syntax.

> Can you show a description if a summary is missing?

Yes,
```nunjucks
{{#summary}}{{{summary}}}{{/summary}}{{^summary}}{{{notes}}}{{/summary}}
```
Tip from offical Mustaches doc about triple bracets:
> All variables are HTML escaped by default. If you want to return unescaped HTML, use the triple mustache: `{{{name}}}`.

**Comment by zeljkot** [comment] 2020-05-02 09:43
Cool, can you make it part of standard release?

**Comment by ybelenko** [comment] 2020-05-02 10:04
> Cool, can you make it part of standard release?

I don't think so, sorry. 

First of all, mustaches gives enough flexibility to solve your issue with a small effort. Change original mustache template, save it with the same name(`README.md`) somewhere then use `generate` method `[(-t <template directory> | --template-dir <template directory>)]` option to use modified template. It's faster to edit template than wait for PR approve and next release which isn't coming soon.

Second,  I'm not an author of `markdown` generator. It's up to @jimschubert to change this template.

**Comment by jimschubert** [comment] 2020-05-02 15:31
Yeah we can add a condition like this. It'll probably be a while before I get to it, though. I have a ton going on atm.

**Comment by wing328** [comment] 2020-05-02 15:36
@zeljkot I wonder if you can file a PR with the suggested fix from @ybelenko 

(everyone, not only the creator of the generator/template, can submit a PR to enhance something in this project)

**Closed** 2020-05-05 03:24 UTC
Labels: Doc: Markdown, General: Question
