### ISSUE TITLE
DefaultCodegen: Inheritance (allOf) parent not working when it is not at first position

### ISSUE THREAD

**Issue by janssen92** [OpenAPITools/openapi-generator#340] opened 2018-06-18 09:09 UTC
##### Description

The inheritance is not working, the inherited attributes are not included in the generated files. (E.g. GetProofingConfigDto misses all ProofingConfigDto attriubtes)

Additionally, the generator warns about Objects, which SwaggerCodegen did not:
[main] WARN  o.o.codegen.DefaultCodegen - Unknown type found in the schema: object

##### openapi-generator version

3.0.2

##### OpenAPI declaration file content or url

https://github.com/janssen92/swagger-feedback-service-api/blob/testOpenApiGenerator/swagger-feedback.json
https://github.com/janssen92/swagger-feedback-service-api/blob/testOpenApiGenerator/swagger-feedback-conf.json

##### Command line used for generation
`
java -jar ~/git/openapi-generator/modules/openapi-generator-cli/target/openapi-generator-cli.jar generate -i swagger-feedback.json -g spring -o ~/testOpenApiGen --library spring-boot --config swagger-feedback-conf.json 
`
But also same result with less parameters:
`
java -jar ~/git/openapi-generator/modules/openapi-generator-cli/target/openapi-generator-cli.jar generate -i swagger-feedback.json -g spring -o ~/testOpenApiGen 
`

##### Steps to reproduce

- Checkout file(s)
- Generate Code

**Comment by janssen92** [comment] 2018-06-18 09:10
Tested it with v3 as well as v2

**Comment by jmini** [comment] 2018-06-19 03:45
Might be a duplicate of #192

**Comment by jmini** [comment] 2018-06-20 07:04
I did not investigate this issue in detail, but I think it is the same than #192 and therefore it might be fixed with PR #358.

**Comment by jmini** [comment] 2018-06-22 08:46
Can you check the latest `3.0.3-SNAPSHOT` version?

**Comment by janssen92** [comment] 2018-06-25 08:54
I can not find any 3.0.3-SNAPSHOT, but I just pulled and build current Master. There is still no inherited Attributes in some classes. (In others the 'extend' ist used just fine). I think the reason is: If you use 'allOf' and then a $ref as the first array element it works just fine. But if the $ref is a later array Element (e.g. the last one) the 'extend' isn't generated. This wasn't an Issue with Swagger-Gen so far.

**Comment by jmini** [comment] 2018-06-25 10:52
Our SNAPSHOT builds are pushed to the sonatype snapshot repository:
https://oss.sonatype.org/content/repositories/snapshots

For example the CLI jar is the newest jar in this folder:
https://oss.sonatype.org/content/repositories/snapshots/org/openapitools/openapi-generator-cli/3.0.3-SNAPSHOT/

Or you can just use Maven to download it for you.

----

Anyway thanks for having tested this...

You are telling that this works:

```yaml
definitions:
  SomeObject:
    type: object
    allOf:
      - $ref: "#/definitions/OtherObject"
      - type: object
        required:
          - bla
        properties:
          bla:
            type: string
  OtherObject:
    type: object
    properties:
      p1:
        type: string
      p2:
        type: string
```

And this one does not work:

```yaml
definitions:
  SomeObject:
    type: object
    allOf:
      - type: object
        required:
          - bla
        properties:
          bla:
            type: string
      - $ref: "#/definitions/OtherObject"
  OtherObject:
    type: object
    properties:
      p1:
        type: string
      p2:
        type: string
```

If this is your issue, I can have a look at it.

**Comment by janssen92** [comment] 2018-06-25 11:07
Ah thanks for the links, I will check it out.

Yes, your example is correct, didn't notice that pattern when I created the issue, but now that I know it, it seems to be correct for alle Problems

**Comment by jmini** [comment] 2018-06-25 11:48
Well with `3.0.2` both cases are broken. `3.0.3-SNAPSHOT` solves the case with `$ref` at first position. The remaining work to solve this issue is to handle cases where `$ref` is not at first position.

**Comment by ackintosh** [comment] 2018-10-04 10:54
https://github.com/OpenAPITools/openapi-generator/issues/340#issuecomment-400013067
> In my opinion we could improve this by taking the first $ref we find in the allOf-List...

I agree with that. I'll file a PR to improve so. 😉

**Closed** 2018-10-05 15:28 UTC
Labels: Feature: Composition / Inheritance, Server: Java
