### ISSUE TITLE
[cpp-pistache-server] Setters not generated for arrays of objects and/or strings

### ISSUE THREAD

**Issue by bocse** [OpenAPITools/openapi-generator#1379] opened 2018-11-05 17:42 UTC
##### Description

In C++ Pistache, the setters for arrays of objects are not created in the generated source code

##### openapi-generator version

Master branch at the moment of creation of this issues.

##### OpenAPI declaration file content or url

The full OpenAPI spec is available as JSON at:
https://github.com/deepviss/deepviss-server-example/blob/master/src/main/resources/deep-viss-openapi-v3.json

For instance, from the definition of "Frame", not setter is generated the C++ code for the field "Events"
```
"Frame": {
        "type": "object",
        "properties": {
          "timestamps": {
            "description": "Defines the several timestamps of acquisition, reception, pre-processing and post-processing respectively.",
            "type": "array",
            "items": {
              "$ref": "#/definitions/FrameTimestamp",
              "type": "FrameTimestamp"
            }
          },
          "sourceId": {
            "type": "string",
            "description": "Video source id."
          },
          "image": {
            "type": "Image",
            "$ref": "#/definitions/Image",
            "description": "Image information"
          },
          "events": {
            "type": "array",
            "items": {
              "$ref": "#/definitions/Event",
              "type": "Event"
            }
          }
        }
      }
```

The generated code lacks setters for arrays of objects (i.e. Events):

```
Last login: Mon Nov  5 10:49:47 on console
Bogdans-MacBook-Air:~ bocse$ ssh kraken@research-bsv-03-vsgc.westeurope.cloudapp.azure.com
kraken@research-bsv-03-vsgc.westeurope.cloudapp.azure.com's password: 
Welcome to Ubuntu 16.04.5 LTS (GNU/Linux 4.15.0-1022-azure x86_64)

 * Documentation:  https://help.ubuntu.com
 * Management:     https://landscape.canonical.com
 * Support:        https://ubuntu.com/advantage

  Get cloud support with Ubuntu Advantage Cloud Guest:
    http://www.ubuntu.com/business/services/cloud

53 packages can be updated.
0 updates are security updates.


*** System restart required ***
Last login: Fri Nov  2 09:20:40 2018 from 86.121.227.48
kraken@research-bsv-03:~$ ls
2002  cmake-3.12.1    dlib          jni-seeta  old_openapi-generator  pistache
2003  deep-viss.json  fast-backend  json.hpp   openapi-generator
kraken@research-bsv-03:~$ cd openapi-generator/
kraken@research-bsv-03:~/openapi-generator$ mc





































Select an editor.  To change later, run 'select-editor'.
  1. /bin/ed
  2. /bin/nano        <---- easiest
  3. /usr/bin/mcedit
  4. /usr/bin/vim.basic
  5. /usr/bin/vim.tiny

Choose 1-5 [2]: 4

/// </summary>
class  Frame
    : public ModelBase
{
public:
    Frame();
    virtual ~Frame();
    
    /////////////////////////////////////////////
    /// ModelBase overrides
    
    void validate() override;
    
    nlohmann::json toJson() const override;
    void fromJson(nlohmann::json& json) override;
    
    /////////////////////////////////////////////
    /// Frame members
    
    /// <summary>
    /// Defines the several timestamps of acquisition, reception, pre-processing and post-processing respectively.
    /// </summary>
    std::vector<FrameTimestamp>& getTimestamps();
    bool timestampsIsSet() const;
    void unsetTimestamps();
    /// <summary>
    /// Video source id.
    /// </summary>
    std::string getSourceId() const;
    void setSourceId(std::string const& value);
    bool sourceIdIsSet() const;
    void unsetSourceId();
    /// <summary>
    /// 
    /// </summary>
    Image getImage() const;
    void setImage(Image const& value);
    bool imageIsSet() const;
    void unsetImage();
    /// <summary>
    /// 
    /// </summary>
    std::vector<Event>& getEvents();
    bool eventsIsSet() const;
    void unsetEvents();

protected:
    std::vector<FrameTimestamp> m_Timestamps;
    bool m_TimestampsIsSet;
    std::string m_SourceId;
    bool m_SourceIdIsSet;
    Image m_Image;
    bool m_ImageIsSet;
    std::vector<Event> m_Events;
    bool m_EventsIsSet;
};

```

##### Command line used for generation

```
java -jar modules/openapi-generator-cli/target/openapi-generator-cli.jar generate \
   -i https://raw.githubusercontent.com/deepviss/deepviss-server-example/master/src/main/resources/deep-viss-openapi-v3.json \
   -g cpp-pistache-server \
   -o output_dir


```

##### Steps to reproduce

Build the OpenAPI-v2 specification of DeepVISS.
Notice the setters are missing from attributes defined as arrays.

##### Related issues/PRs

Possible related to 
https://github.com/OpenAPITools/openapi-generator/issues/1251

##### Suggest a fix/enhancement

Create the setter methods for array of objects or strings.
Alternatively, please suggest a work-around. This is a blocking issue for our use of OpenAPI generator.

**Comment by bocse** [comment] 2018-11-12 14:15
Any suggestions for a workaround until a fix is available?

This is a blocking issue for releasing our first implementation with OpenAPI :)

**Comment by bocse** [comment] 2018-11-23 12:14
A fix or workaround for this issue would be really helpful. Please advise.

**Comment by etherealjoy** [comment] 2018-11-24 10:08
@bocse 
This is not related to #1251 

See the return type here is reference to the vector.
```c++
std::vector<Point2D>& getKeypoints();
std::vector<Event>& getEvents();
```
Once you get the reference to the vector you can clear it and  push_back elements into it.
So this is not an issue but rather it is like this by design.
Please check it and confirm if it works for you.

**Comment by etherealjoy** [comment] 2019-01-06 08:11
Closing this issue as not a bug.

**Closed by etherealjoy** 2019-01-06 08:11 UTC
Labels: Issue: Workaround available, Server: C++
