### ISSUE TITLE
[BUG][PYTHON] Multiple authentication schemes are used, only want to use one

### ISSUE THREAD

**Issue by phillip-elliott** [OpenAPITools/openapi-generator#3844] opened 2019-09-05 19:01 UTC
#### Bug Report Checklist

- [x] Have you provided a full/minimal spec to reproduce the issue?
- [x] Have you validated the input using an OpenAPI validator ([example](https://apidevtools.org/swagger-parser/online/))?
- [x] What's the version of OpenAPI Generator used?
- [x] Have you search for related issues/PRs?
- [x] What's the actual output vs expected output?
- [ ] [Optional] Bounty to sponsor the fix ([example](https://www.bountysource.com/issues/66123212-javascript-client-produces-a-wrong-object-for-a-string-enum-type-that-is-used-with-ref))

##### Description

I have a spec with the following securitySchemes:
```
"securitySchemes": {
      "APIKeyHeader": {
        "type": "apiKey",
        "name": "API-Key",
        "in": "header"
      },
      "basicAuth": {
        "type": "http",
        "scheme": "basic"
      }
    }
```

I am applying these schemes globally, indicating that either APIKeyHeader OR basicAuth can be used:
```
security": [
    {
      "APIKeyHeader": []
    },
    {
      "basicAuth": []
    }
  ],
```

When using a python client, I do the following:
```
config = Configuration()
config.host = base_url
config.api_key['API-Key'] = api_key

api_client = ApiClient(configuration=config)
project_api = ProjectsApi(api_client)
```

I am not providing a username or password. I would expect the python client to ignore the basic auth scheme and just use the apiKey scheme instead. Instead, both are used and all requests are denied (403).

##### openapi-generator version

4.1.1

##### OpenAPI declaration file content or url

https://gist.github.com/phillip-elliott/0438a8159f138e1f270a7814b81e65d9

##### Command line used for generation

openapi-generator generate -i openapispec.json -g python 

##### Suggest a fix

The python client's Configuration class has a method named get_basic_auth_token. This method could return None if username and password are both set to None. If it returns None, then I believe the basic auth header will not be added to the requests (see ApiClient.update_params_for_auth).

**Comment by wing328** [comment] 2019-09-06 03:29
> I would expect the python client to ignore the basic auth scheme and just use the apiKey scheme instead. Instead, both are used and all requests are denied (403).

In other clients, if username and password are not set, then the HTTP basic header won't be sent out.

I wonder if you've time to make a similar enhancement to the Python client.

**Comment by martyzz1** [comment] 2019-09-11 16:32
I've just run up against this when supplying an ApiKey header - but on an endpoint configured for a Bearer or ApiKey header....  I'll see if I can submit a patch

**Comment by martyzz1** [comment] 2019-09-11 18:06
My custom configuration.mustache file is looking a bit out of date so hard to post a diff....

But the crux of the issue is here...

https://github.com/OpenAPITools/openapi-generator/blob/master/modules/openapi-generator/src/main/resources/python/configuration.mustache#L251

If auth_settings() returns *any* value, then the api_client's update_params_for_auth() . will get a "value" for the Authorization header... this in turn means that whichever Aothorisation methods are supplied in the openapi file,  - the last one as python iterates through them - will be the one the client tries to use....

I customised the function for my version to this

```def get_api_key_for_prefix(self, identifier, desired_prefix):
        """Gets API key (with prefix if set).

        :param identifier: The identifier of apiKey.
        :param prefix: The prefix of apiKey e.g. 'Bearer' or  'ApiKey'.
        :return: The token for api key authentication or return nothing.
        """
        if (self.api_key.get(identifier) and
                self.api_key_prefix.get(identifier) and
                self.api_key_prefix.get(identifier) == desired_prefix):
            return self.api_key_prefix[identifier] + ' ' + self.api_key[identifier]  # noqa: E501
```

**Comment by sebastien-rosset** [comment] 2019-11-24 17:22
My observation is the generated update_params_for_auth() function loops through all security schemes listed in the OpenAPI spec for the operation and updates the attributes (cookie, header, query) whether or not the auth settings are initialized.

A service could require more than one authentication method, so we need to be able to specify which security scheme to use. For example, if the OpenAPI spec specifies OAuth2, basic auth and api key, the service could potentially required both basic auth and api keys. This can be done by adding a security_schemes attribute in configuration.mustache:
```
        self.security_schemes = None
        """The security schemes to use (typically one, should be a subset of what is specified in the OpenAPI spec)
        """
```
And in api_client.mustache, modify update_params_for_auth() to calculate the intersection of the auth_settings and security_schemes:
```
       if self.configuration.security_schemes:
            auth_settings = [value for value in auth_settings if value in self.configuration.security_schemes]
```
Another way would be to use whatever settings (username, password, OAuth2...) have been initialized, but being explicit about which scheme to use is less ambiguous. I'd be happy to submit a PR unless someone is already working on it.

**Comment by spacether** [comment] 2020-01-27 06:31
This has been resolved by https://github.com/OpenAPITools/openapi-generator/pull/4988

**Closed by spacether** 2020-01-27 06:31 UTC
Labels: Client: Python, Issue: Bug
