### ISSUE TITLE
Model interface not generated in version 2.0 typescript-angular for nested properties

### ISSUE THREAD

**Issue by topce** [OpenAPITools/openapi-generator#304] opened 2018-06-13 10:17 UTC
##### Description
Model interface not generated in version 2.0 typescript-angular for nested properties

##### openapi-generator version
3.0.1 master

it is regression if we compare with swagger-codegen master
##### OpenAPI declaration file content or url

```yaml
swagger: '2.0'
info:
  title: Test
  description: Test
  version: "1.0.0"
host: "localhost:8002"
schemes:
  - http
basePath: /v1
produces:
  - application/json
securityDefinitions:
  basicAuth:
    type: basic
    description: HTTP Basic Authentication
security:
  - basicAuth: []
paths:

definitions:
  NotificationDefinition:
    type: object
    description: the representation of all the notification configuration of one node
    properties:
      profiles:
        type: array
        items:
          type: object
          properties:
            profile:
              $ref: "#/definitions/Profile"
            notifications:
              type: string
            inherited:
              type: boolean
      users:
        type: array
        items:
          type: object
          properties:
            user:
              $ref: "#/definitions/User"
            notifications:
              type: string
            inherited:
              type: boolean
  User:
    type: object
    description: a CIRCABC user
    properties:
      userId:
        type: string
      firstname:
        type: string
      lastname:
        type: string
      email:
        type: string
      phone:
        type: string
      uiLang:
        type: string
      contentFilterLang:
        type: string
      visibility:
        type: boolean
      properties:
        type: object
        description: |
          properties field will receive all the configuration parameters relative
          to the user accound. For example notification / prefered language / etc.
      avatar:
        type: string
        description: |
          Used to get the URL of the user picture that will be shown everywhere in the app
  Profile:
    type: object
    description: the representation of an access profile definition inside an Interest Group
    properties:
      id:
        type: string
      name:
        type: string
      title:
        $ref: string
      groupName:
        type: string
      permissions:
        type: object
        additionalProperties:
          type: string
      imported:
        type: boolean
      importedRef:
        type: string
        description: |
          in the case the profile is imported from another group, it is the IG nodeRef from which
          it has been imported
      exported:
        type: boolean
      exportedRefs:
        type: array
        items:
          type: string
        description: |
          in the case the profile is exported and imported at least once in an IG, it is the list of
          all the IGs in which the profile has been imported into
```
it generates 
```typescript
export interface NotificationDefinition { 
    profiles?: Array<any>;
    users?: Array<any>;
}
``` 
before it generated 3 files 
```typescript
/// fist 
import { NotificationDefinitionProfiles } from './notificationDefinitionProfiles';
import { NotificationDefinitionUsers } from './notificationDefinitionUsers';

export interface NotificationDefinition { 
    profiles?: Array<NotificationDefinitionProfiles>;
    users?: Array<NotificationDefinitionUsers>;
}
//// second 
import { Profile } from './profile';


export interface NotificationDefinitionProfiles { 
    profile?: Profile;
    notifications?: string;
    inherited?: boolean;
}
/// third

import { User } from './user';


export interface NotificationDefinitionUsers { 
    user?: User;
    notifications?: string;
    inherited?: boolean;
}


```

 

##### Command line used for generation
org.openapitools.codegen.OpenAPIGenerator
generate -i C:\swagger.yaml -g typescript-angular -o C:\temp --additional-properties ngVersion=6.0.0

##### Steps to reproduce

run generator with provided yaml file typescript-angular
##### Related issues/PRs

probably same issue is presented with some other generators

**Comment by topce** [comment] 2018-06-25 08:16
@jmini @wing328 
any news on this one ?

**Comment by macjohnny** [comment] 2018-07-10 13:37
@wing328 @jmini I can confirm this still is an issue with `3.1.0` for `typescript-angular` and `spring`, so I think this is an issue with the default codegen / parser.
could be related to https://github.com/OpenAPITools/openapi-generator/issues/222 and https://github.com/OpenAPITools/openapi-generator/issues/8

@topce would you like to attempt to fix this? maybe @wing328 @jmini can point you to the starting point

**Comment by macjohnny** [comment] 2018-07-10 13:49
@topce the problem can be fixed by changing the api definition as follows:
```yaml
swagger: '2.0'
info:
  title: Test
  description: Test
  version: "1.0.0"
host: "localhost:8002"
schemes:
  - http
basePath: /v1
produces:
  - application/json
securityDefinitions:
  basicAuth:
    type: basic
    description: HTTP Basic Authentication
security:
  - basicAuth: []
paths:

definitions:
  NotificationDefinition:
    type: object
    description: the representation of all the notification configuration of one node
    properties:
      profiles:
        type: array
        items:
          $ref: "#/definitions/ProfileWrapper"
      users:
        type: array
        items:
          $ref: "#/definitions/UserWrapper"
  User:
    type: object
    description: a CIRCABC user
    properties:
      userId:
        type: string
      firstname:
        type: string
      lastname:
        type: string
      email:
        type: string
      phone:
        type: string
      uiLang:
        type: string
      contentFilterLang:
        type: string
      visibility:
        type: boolean
      properties:
        $ref: '#/definitions/Properties'
      avatar:
        type: string
        description: |
          Used to get the URL of the user picture that will be shown everywhere in the app
  Profile:
    type: object
    description: the representation of an access profile definition inside an Interest Group
    properties:
      id:
        type: string
      name:
        type: string
      title:
        $ref: string
      groupName:
        type: string
      permissions:
        $ref: '#/definitions/Permissions'
      imported:
        type: boolean
      importedRef:
        type: string
        description: |
          in the case the profile is imported from another group, it is the IG nodeRef from which
          it has been imported
      exported:
        type: boolean
      exportedRefs:
        type: array
        items:
          type: string
        description: |
          in the case the profile is exported and imported at least once in an IG, it is the list of
          all the IGs in which the profile has been imported into

  ProfileWrapper:
    type: object
    properties:
      profile:
        $ref: "#/definitions/Profile"
      notifications:
        type: string
      inherited:
        type: boolean
  UserWrapper:
    type: object
    properties:
      user:
        $ref: "#/definitions/User"
      notifications:
        type: string
      inherited:
        type: boolean
  Properties:
    type: object
    description: |
      properties field will receive all the configuration parameters relative
      to the user accound. For example notification / prefered language / etc.
  Permissions:
    type: object
    additionalProperties:
      type: string
```

the reason is that inline-defined objects are not generated, see https://github.com/OpenAPITools/openapi-generator/issues/222#issuecomment-394645648

@jmini I think this issue should be closed as a duplicate of #8

**Comment by topce** [comment] 2018-07-10 14:09
Thank you @macjohnny  for fast comment and workaround.
@jmini probably you are right I will close this on 
even this one is little bit different it use swagger: '2.0'
not openapi: 3.0.0

@jmini  and @wing328 do you think we should fix this 
or you recommend me to change swagger.yaml file as workaround ?

**Closed** 2018-07-11 06:13 UTC

**Comment by macjohnny** [comment] 2018-07-17 07:32
@topce 
> do you think we should fix this

I think https://github.com/OpenAPITools/openapi-generator/issues/8 should definitely be fixed.

**Comment by topce** [comment] 2018-07-17 17:24
Thank you @macjohnny !
Workaround works for me as well ;-)

**Comment by jmini** [comment] 2018-08-16 04:13
There was some work made with #736 for version `3.2.1` can you give this version a try?
(#736 is a start, maybe more use cases needs to be covered as discuss in #8)
