### ISSUE TITLE
[BUG][MYSQL-SCHEMA] howto handle nested objects in schema generation?

### ISSUE THREAD

**Issue by el2ro** [OpenAPITools/openapi-generator#1672] opened 2018-12-14 10:32 UTC
##### Description

When generating DB schema out of OpenAPI spec how should be nested data structures be handled?

Currently it is working so that nested object will create a new table with fields in nested structure. Nested parameter in parent table is set as TEXT. This does not feel like right?

I am not sure if this is a bug, but I am looking info how this should be really handled in nested object case. Background: I am trying to make Postgresql-schema generator and this thing came up, this also applies to mysql-schema generator.

Somehow it feels that it should set nested object as JSON type to main table and not to generate additional table at all.

##### openapi-generator version

3.3.4 or 4.x.x

Using 3.xx open api yaml spec

##### OpenAPI declaration file content or url

Full test.yaml https://gist.github.com/el2ro/7d6a3007389429b906b4a49878621dc7
Only important part of it:
```yaml
components:
  schemas:
    Test:
      title: test
      type: object
      description: Test
      properties:
        id:
          type: string
          format: uuid
        name:
          type: string
        description:
          type: string
        settings:
          type: object
          description: Nested object inside an object
          properties:
            startValue:
              type: object
            endValue:
              type: object
            someValue:
              type: object
```

```SQL
CREATE TABLE IF NOT EXISTS `Test` (
  `id` TEXT DEFAULT NULL,
  `name` TEXT DEFAULT NULL,
  `description` TEXT DEFAULT NULL,
  `settings` TEXT DEFAULT NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci COMMENT='Test';

CREATE TABLE IF NOT EXISTS `Test_settings` (
  `startValue` JSON DEFAULT NULL,
  `endValue` JSON DEFAULT NULL,
  `someValue` JSON DEFAULT NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci COMMENT='Nested object inside an object';
```
(for JSON code), so it becomes more readable. If it is longer than about ten lines,
please create a Gist (https://gist.github.com) or upload it somewhere else and
link it here.
  -->

##### Command line used for generation
```
openapi-generator generate \
   -i src/test.yaml \
   -g mysql-schema \
   -o generated/
```

**Comment by macjohnny** [comment] 2018-12-14 14:52
@ybelenko can you help here?

**Comment by ybelenko** [comment] 2018-12-14 16:52
@el2ro Thanks for interest to MysqlSchema generator, I wasn't sure that somebody needs it.

We were thinking about perfect DB schema a lot. You can checkout community discussion at #955 

We've ended up with conclusion that all data types that is difficult to implement in the first version will mapped to `JSON`(`TEXT` as backup for old MySQL).

> Somehow it feels that it should set nested object as JSON type to main table and not to generate additional table at all.

Can't agree with you, in a perfect world I would prefer:
```SQL
CREATE TABLE `test` (
 `id` text COLLATE utf8mb4_unicode_ci,
 `name` text COLLATE utf8mb4_unicode_ci,
 `description` text COLLATE utf8mb4_unicode_ci,
 `settings` int(11) DEFAULT NULL,
 KEY `fk_test_settings` (`settings`),
 CONSTRAINT `fk_test_settings` FOREIGN KEY (`settings`) REFERENCES `test_settings` (`id`) ON DELETE SET NULL ON UPDATE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci COMMENT='Test'

CREATE TABLE `test_settings` (
 `id` int(11) NOT NULL AUTO_INCREMENT,
 `startValue` json DEFAULT NULL,
 `endValue` json DEFAULT NULL,
 `someValue` json DEFAULT NULL,
 PRIMARY KEY (`id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci COMMENT='Nested object inside an object'
```
I know that it's not possible to generate such complex schema without vendor extension fields(define primary key in each table, etc.), but you can modify table by hands with a small effort.

In my opinion, foreign keys or relation tables(for arrays) one-two-many or many-two-many works better than `JSON` column type. I would consider `JSON` type as temp workaround when you don't have time to built decent normalized data structure. When you don't have time and when you need to store `package.json` in DB, only these two cases. :smile:

**Comment by ybelenko** [comment] 2018-12-21 13:17
Closed as not a bug

**Closed by ybelenko** 2018-12-21 13:17 UTC
Labels: Issue: Bug, bug
