### ISSUE TITLE
[BUG] [TypeScript-Angular] It is not possible to receive 'text/plain' responses with a generated client.

### ISSUE THREAD

**Issue by cjuenger** [OpenAPITools/openapi-generator#4817] opened 2019-12-17 17:03 UTC
#### Bug Report Checklist

- [ ] Have you provided a full/minimal spec to reproduce the issue?
- [ ] Have you validated the input using an OpenAPI validator ([example](https://apidevtools.org/swagger-parser/online/))?
- [x] What's the version of OpenAPI Generator used?
- [x] Have you search for related issues/PRs?
- [x] What's the actual output vs expected output?
- [ ] [Optional] Bounty to sponsor the fix ([example](https://www.bountysource.com/issues/66123212-javascript-client-produces-a-wrong-object-for-a-string-enum-type-that-is-used-with-ref))

##### Description
For HTTP operations with a simple 'text/plain' response, the openapi-generator generates code that uses the template specialization of the appropriate HttpClient method (e.g. HttpClient.post<string>). As soon as the template specialization is used the Angular compiler expects the response to be a JSON object and the HttpClient method fails with an error.

See this [LINK ](https://github.com/angular/angular/issues/18672#issuecomment-322091282)for the described behavior in Angular. 

##### openapi-generator version
4.2.2

##### Suggest a fix

In case of plain text, call the HttpClient method without the template specialization (just remove the '<TYPE>' part from the function) and add 'responseType: 'text' to the options object of the method.

For example change this

```
return this.httpClient.post<string>('${this.configuration.basePath}/something',
	myObject,
	{
		withCredentials: this.configuration.withCredentials,
		headers: headers,
		observe: observe,
		reportProgress: reportProgress                
	}
);
```
to this

```
return this.httpClient.post('${this.configuration.basePath}/something',
	myObject,
	{
		withCredentials: this.configuration.withCredentials,
		headers: headers,
		observe: observe,
		reportProgress: reportProgress,
                responseType: 'text'                
	}
);
```

**Comment by macjohnny** [comment] 2019-12-18 16:00
duplicate of https://github.com/OpenAPITools/openapi-generator/issues/2035

**Closed by macjohnny** 2019-12-18 16:00 UTC
Labels: Issue: Bug
