### ISSUE TITLE
openapi-generator-maven-plugin not generating any test cases when the provided generatorName is spring

### ISSUE THREAD

**Issue by vanipareek** [OpenAPITools/openapi-generator#3366] opened 2019-07-15 09:37 UTC
<plugin>
<groupId>org.openapitools</groupId>
<artifactId>openapi-generator-maven-plugin</artifactId>
<version>4.0.0</version>
<executions>
    <execution>        
        <goals>
            <goal>generate</goal>
        </goals>
        <configuration>
            <inputSpec>${project.basedir}\src\main\resources\api.yml</inputSpec>
            <modelPackage>com.demo.model</modelPackage>
            <apiPackage>com.demo.api</apiPackage>
            <generatorName>spring</generatorName>
            <supportingFilesToGenerate>ApiUtil.java</supportingFilesToGenerate>
                <generateApi>True</generateApi>
                <generateApiTests>True</generateApiTests>
                <generateModelTests>True</generateModelTests>
                <validateSpec>true</validateSpec>
                <configOptions>
                 <delegatePattern>true</delegatePattern>
                 <title>swagger-codegen-demo</title>
            </configOptions>
        </configuration>
     </execution>

</executions>

**Comment by Zomzog** [comment] 2019-07-18 20:49
Looks like a duplicate of #3318

**Comment by wing328** [comment] 2019-08-14 14:09
Duplicated. Please see #3318

**Closed by wing328** 2019-08-14 14:09 UTC
