### ISSUE TITLE
[BUG][php-symfony] Issue with double type in model

### ISSUE THREAD

**Issue by Cubid** [OpenAPITools/openapi-generator#13335] opened 2022-09-01 12:17 UTC
#### Bug Report Checklist

- [X] Have you provided a full/minimal spec to reproduce the issue?
- [X] Have you validated the input using an OpenAPI validator ([example](https://apidevtools.org/swagger-parser/online/))?
- [X] Have you [tested with the latest master](https://github.com/OpenAPITools/openapi-generator/wiki/FAQ#how-to-test-with-the-latest-master-of-openapi-generator) to confirm the issue still exists?
- [X] Have you searched for related issues/PRs?
- [X] What's the actual output vs expected output?
- [ ] [Optional] Sponsorship to speed up the bug fix or feature request ([example](https://github.com/OpenAPITools/openapi-generator/issues/6178))

##### Description

The double format does not working with the new typings introduced in 6.0.

We are using the following property in our Yaml Open API spec:
```yaml
        myVar:
          description: My description
          format: double
          type: number
          nullable: true
```
The model code generated with 5.2.1 is the following
```php
    /**
     * My description
     *
     * @var double|null
     * @SerializedName("myVar")
     * @Assert\Type("double")
     * @Type("double")
     */
    protected $myVar;

....
    /**
     * Gets myVar.
     *
     * @return double|null
     */
    public function getMyVar()
    {
        return $this->myVar;
    }

    /**
     * Sets myVar.
     *
     * @param double|null $myVarMy description
     *
     * @return $this
     */
    public function setMyVar($myVar= null)
    {
        $this->myVar= $myVar;

        return $this;
    }

```
It is working fine.

When upgrading to 6.0.1, the generated code does not work:
```php

    /**
     * Gets primeTtc.
     *
     * @return |null
     */
    public function getPrimeTtc(): 
    {
        return $this->primeTtc;
    }

    /**
     * Sets primeTtc.
     *
     * @param  $primeTtc  Prime TTC qui sera accordÃ©e Ã  la contractualisation
     *
     * @return $this
     */
    public function setPrimeTtc( $primeTtc = null): self
    {
        $this->primeTtc = $primeTtc;

        return $this;
    }
```

When overloading the CodeGen class and mapping `double` to `foat` it is working fine:

```java
public class MyPhpSymfonyServerCodegen extends org.openapitools.codegen.languages.PhpSymfonyServerCodegen {

    public MyPhpSymfonyServerCodegen (){
        super();
        typeMapping.put("double", "float");
    }
}
```

##### openapi-generator version

6.0.1

##### OpenAPI declaration file content or url

See previous sample

**Comment by neclimdul** [comment] 2022-09-14 14:17
This seems to be a problem with all the PHP generators. There seem to be two related problems.

1) The primitive list includes double(as well as number) which is not a valid language or phpdoc primitive.
2) The map for double assumes double is a primitive which is not.

So the fix is mostly correct but should be applied to all the PHP generators. 

References:
https://docs.phpdoc.org/3.0/guide/guides/types.html#primitives
http://php.net/manual/en/language.types.intro.php
https://www.php.net/manual/en/language.types.float.php

**Comment by wing328** [comment] 2022-09-14 14:46
we just released v6.1.0 which include some enhancements to the php symfony generator. 

please give it a try and let us know it's still an issue.

**Comment by wing328** [comment] 2022-09-14 14:48
https://github.com/OpenAPITools/openapi-generator/blob/master/modules/openapi-generator/src/main/java/org/openapitools/codegen/languages/AbstractPhpCodegen.java

looks like this line needs to be fixed by mapping double to float instead. or am I missing something as the fix is so obviious?

**Comment by Cubid** [comment] 2022-09-14 14:56
Yes, just need to replace 
```
typeMapping.put("double", "double");
```
with
```
typeMapping.put("double", "float");
```
I have overriden the generator and done the change, it works perfectly!

**Comment by neclimdul** [comment] 2022-09-14 14:57
Yeah, I confirmed it exists in master. Working on the pull request.

I think its basically that plus removing it from the primitive list plus cleaning up some of the other generators that already had this

**Comment by wing328** [comment] 2022-09-14 15:01
I'm working on a PR

**Comment by wing328** [comment] 2022-09-14 15:01
sure

**Comment by wing328** [comment] 2022-09-14 15:01
go ahead pls

**Comment by wing328** [comment] 2022-09-14 15:06
I've filed https://github.com/OpenAPITools/openapi-generator/pull/13420 as a draft.

can you review and incorporate those changes if make senses and not yet included in your PR? thank you.

**Comment by neclimdul** [comment] 2022-09-14 15:16
I see you changed the enum code. I'll include that too. I hadn't been able to figure out if that was the native type or the spec type.

**Closed** 2022-09-15 09:16 UTC
Labels: Issue: Bug

**Comment by Cubid** [comment] 2022-09-15 09:25
@neclimdul @wing328 thanks for this modification. I wouldn't have gone as deep as you managed to do.
