### ISSUE TITLE
[BUG] [Go] GenericOpenAPIError returned from Execute should be pointer, not plain object

### ISSUE THREAD

**Issue by onitake** [OpenAPITools/openapi-generator#8370] opened 2021-01-07 15:00 UTC
#### Bug Report Checklist

- [ ] Have you provided a full/minimal spec to reproduce the issue?
- [ ] Have you validated the input using an OpenAPI validator ([example](https://apidevtools.org/swagger-parser/online/))?
- [x] Have you [tested with the latest master](https://github.com/OpenAPITools/openapi-generator/wiki/FAQ#how-to-test-with-the-latest-master-of-openapi-generator) to confirm the issue still exists?
- [ ] Have you searched for related issues/PRs?
- [ ] What's the actual output vs expected output?
- [ ] [Optional] Sponsorship to speed up the bug fix or feature request ([example](https://github.com/OpenAPITools/openapi-generator/issues/6178))

##### Description

In https://github.com/OpenAPITools/openapi-generator/blob/master/modules/openapi-generator/src/main/resources/go/api.mustache#L39 a custom error type (GenericOpenAPIError) is returned. But, instead of using a pointer to struct, as is common in Go, a plain struct object is used. This prevents idiomatic error checks like the following:
```go
_, err = client.MyApi.XyzPostExecute(sub.Content(*arg))
if err != nil {
    // report error
}
```

##### openapi-generator version

It seems this was introduced by 1562afea3980484a7f1819c4f51b0d53a44a009f to better support error handling, but actually does the opposite.

##### OpenAPI declaration file content or url

N/A, this is an issue with the code template itself.

##### Suggest a fix

*Execute functions should return a pointer instead, so the error can be consumed in an intuitive fashion. Or, perhaps go even further and make `GenericOpenAPIError` an internal type, and let *Execute simply return `error`.

**Comment by zsmuller** [comment] 2021-01-13 11:33
I concur. In client.go (generated with openapi generator 5.0.0) the GenericOpenAPIError struct has an Error() method with the following definition:
```
// Error returns non-empty string if there was an error.
func (e GenericOpenAPIError) Error() string {
	return e.error
}
```

So the usual `if err != nil { ... }` error handling now has to be `if err.Error() != "" { ... }`, which is quite inconvenient.

**Comment by wing328** [comment] 2021-01-13 13:02
I think it's a duplicate of https://github.com/OpenAPITools/openapi-generator/issues/8263. A PR has been filed to revert the change.

**Closed by wing328** 2021-01-13 13:02 UTC
Labels: Issue: Bug
