### ISSUE TITLE
[BUG] [go]  allOf with multiple schemas defined. Using only the first one: 

### ISSUE THREAD

**Issue by iafilius** [OpenAPITools/openapi-generator#10024] opened 2021-07-23 16:36 UTC
#### Bug Report Checklist

- [X] Have you provided a full/minimal spec to reproduce the issue?
- [X] Have you validated the input using an OpenAPI validator ([example](https://apidevtools.org/swagger-parser/online/))?
- [X] Have you [tested with the latest master](https://github.com/OpenAPITools/openapi-generator/wiki/FAQ#how-to-test-with-the-latest-master-of-openapi-generator) to confirm the issue still exists?
- [X] Have you searched for related issues/PRs?
- [X] What's the actual output vs expected output?
- [ ] [Optional] Sponsorship to speed up the bug fix or feature request ([example](https://github.com/OpenAPITools/openapi-generator/issues/6178))

##### Description

Issue: 2nd item of allOf ignored and no code is generated for go client library

Generating a go library form vendor provided spec file results in many warnings like:

```
[main] WARN  o.o.codegen.DefaultCodegen - allOf with multiple schemas defined. Using only the first one: logicalid_reference
```

##### openapi-generator version

5.2.0 and latest master, but tested different versions as well

```
version : WARN log #count while generating from vendor provided swagger file
4.2.2 : 79
4.2.3 : 79
4.3.1 : <crashes>
5.1.1 : 23
5.2.0 : 23
5.2.1-20210716.042228-7 : 23

```

##### Generation Details

java $JAVA_OPTS  -jar ${OAG} generate -i $SWAGGERFILE -g go -o ${VCDIR} -p enumClassPrefix=true

##### Steps to reproduce

Generate go library and watch output. check generated code on missing peaces (100% reproducable)

##### Suggest a fix

I think issue is caused by generator, or a special case of schema, not sure.
schema itself verifies fine.

See attached sample in case_nr7.json.txt which does have the issue
[case_nr7.json.txt](https://github.com/OpenAPITools/openapi-generator/files/6870097/case_nr7.json.txt)
Also see kind of similar attached sample case_nr1.json.txt which does NOT have the issue.
[case_nr1.json.txt](https://github.com/OpenAPITools/openapi-generator/files/6872018/case_nr1.json.txt)

regards

**Comment by oravecz** [comment] 2022-11-17 20:01
The bug is in `DefaultCodeGen`. Not particular to a language template

**Comment by wing328** [comment] 2023-11-20 02:41
tested with the latest master and couldn't reproduce the issue as we've merged some fixes recently.

please give it a try with the latest master and happy to reopen the issue if needed.

**Closed by wing328** 2023-11-20 02:41 UTC
Labels: Issue: Bug
