### ISSUE TITLE
[BUG][KOTLIN] Bug generator Kotlin client definition with multiple enums

### ISSUE THREAD

**Issue by andrewemery** [OpenAPITools/openapi-generator#3917] opened 2019-09-20 00:29 UTC
##### Description

Generating a Kotlin client that contains a definition with multiple enums produces invalid output.

##### openapi-generator version

4.1.2

##### OpenAPI declaration file content or url

```yaml
definitions:
  Pet:
    required:
        - one
        - two
    properties:
      one:
        type: string
        enum:
          - 'A'
          - 'B'
      two:
        type: string
        enum:
          - 'C'
          - 'D'
```

##### Command line used for generation

```bash
openapi-generator generate -g kotlin
```

##### Output

```kotlin
data class Pet (
    @Json(name = "one")
    val one: Pet.One,
    @Json(name = "two")
    val two: Pet.Two
)

{
    /**
    * 
    * Values: a,b
    */
    
    enum class One(val value: kotlin.String){
    
        @Json(name = "A") a("A"),
    
        @Json(name = "B") b("B");
    

    }
}

{
    /**
    * 
    * Values: c,d
    */
    
    enum class Two(val value: kotlin.String){
    
        @Json(name = "C") c("C"),
    
        @Json(name = "D") d("D");
    

    }
}
```

##### Expected output

```kotlin
data class Pet (
    @Json(name = "one")
    val one: Pet.One,
    @Json(name = "two")
    val two: Pet.Two
)

{
    /**
    * 
    * Values: a,b
    */
    
    enum class One(val value: kotlin.String){
    
        @Json(name = "A") a("A"),
    
        @Json(name = "B") b("B");
    

    }
    /**
    * 
    * Values: c,d
    */
    
    enum class Two(val value: kotlin.String){
    
        @Json(name = "C") c("C"),
    
        @Json(name = "D") d("D");
    

    }
}
```

**Comment by erfang-bondhouse** [comment] 2019-09-23 02:27
Hey guys, how does a patch release introduce such a breaking change? Does this mean ordinarily in production we should not rely on the `openapi-generator-cli` shell script and instead hard code a version? Since this was not broken in 4.1.1 just one patch version before

**Comment by wing328** [comment] 2019-09-23 16:03
First of all, my apologies in advance if the patch release contains breaking changes, which should not be the case. Breaking changes with fallback should go to 4.2.x release while breaking changes without fallback should go to the 5.0.x.

From what I can tell, it causes compilation issues but it's more like regression.

To better catch the issue, we'll add a test case to better uncover similar issue moving forward.

I'll try to find some time to review #3928 tomorrow

@erfang-bondhouse if you've time, please also have a look at #3928 to see if it fixes the issue for you.

**Comment by wing328** [comment] 2019-09-25 03:19
The issue should have resolved in the latest master. Please give it a try.

**Closed by wing328** 2019-09-25 03:19 UTC
Labels: Client: Kotlin, Issue: Bug
