### ISSUE TITLE
[BUG][Go][Bounty] Go client generator doesn't support deepObject in query

### ISSUE THREAD

**Issue by kamilsk** [OpenAPITools/openapi-generator#11401] opened 2022-01-25 20:35 UTC
#### Bug Report Checklist

- [x] Have you provided a full/minimal spec to reproduce the issue?
- [x] Have you validated the input using an OpenAPI validator ([example](https://apidevtools.org/swagger-parser/online/))?
- [x] Have you [tested with the latest master](https://github.com/OpenAPITools/openapi-generator/wiki/FAQ#how-to-test-with-the-latest-master-of-openapi-generator) to confirm the issue still exists?
- [x] Have you searched for related issues/PRs?
- [x] What's the actual output vs expected output?
- [ ] [Optional] Sponsorship to speed up the bug fix or feature request ([example](https://github.com/OpenAPITools/openapi-generator/issues/6178))

##### Description

Go client generator doesn't support deepObject in query.

##### openapi-generator version

v5.3.1

##### OpenAPI declaration file content or url

```yaml
openapi: 3.0.0

info:
  title: Example
  description: Example of deepObject failure.
  version: 1.0.0

paths:
  /test:
    get:
      operationId: test
      parameters:
        - name: filter
          in: query
          style: deepObject
          explode: true
          schema:
            type: object
            properties:
              search:
                description: Filter.
                type: string
      responses:
        '200':
          description: Response.
```

##### Generation Details

```bash
$ docker run --rm -it \
    -v "$(pwd)"/api.yaml:/specs/api.yaml \
    openapitools/openapi-generator-cli:v5.3.1 generate -i /specs/api.yaml -g go -o /sdk/go
```

##### Steps to reproduce

1. store example in api.yaml
2. run example from "generation details"

**expected result:** exit code 0 and successful generated content

**actual result:**

```
  Exception: null
        at org.openapitools.codegen.DefaultGenerator.processOperation(DefaultGenerator.java:1175)
        at org.openapitools.codegen.DefaultGenerator.processPaths(DefaultGenerator.java:1066)
        at org.openapitools.codegen.DefaultGenerator.generateApis(DefaultGenerator.java:566)
        at org.openapitools.codegen.DefaultGenerator.generate(DefaultGenerator.java:907)
        at org.openapitools.codegen.cmd.Generate.execute(Generate.java:441)
        at org.openapitools.codegen.cmd.OpenApiGeneratorCommand.run(OpenApiGeneratorCommand.java:32)
        at org.openapitools.codegen.OpenAPIGenerator.main(OpenAPIGenerator.java:66)
Caused by: java.lang.NullPointerException
```

**Comment by gfyrag** [comment] 2022-05-06 19:24
Same with v5.4.0 and latest.

**Comment by Christina0114** [comment] 2022-09-14 21:12
I meet the similar problem in the path parameters. I guess it is because of this line 
`                           CodegenProperty property = fromProperty(entry.getKey(), entry.getValue(), requiredVarNames.contains(entry.getKey()));
                                        property.baseName = codegenParameter.baseName + "[" + entry.getKey() + "]";
                                        return property;`
in `DefaultCodegen` Class.  It updates the key `property.baseName ` in the `schemaCodegenPropertyCache` map.

**Comment by altitude** [comment] 2022-10-04 11:54
Similar issue on our end, we just added a $250 bounty on this one: https://app.bountysource.com/issues/112016967-bug-go-go-client-generator-doesn-t-support-deepobject-in-query

**Comment by KN4CK3R** [comment] 2022-10-04 18:41
The given example works fine with 6.2.0. Do you have another example which does not work?

**Comment by kamilsk** [comment] 2022-10-05 06:38
I will check it and maybe will find another example. Thanks for the comment.

**Comment by kamilsk** [comment] 2022-10-05 08:53
test result

| version | result   |
|:-------|:--------|
| v5.3.1  | failure    |
| v5.4.0 | failure    |
| v6.0.0 | success |

Output is valid

```go
...
	if r.filter != nil {
		localVarQueryParams.Add("filter", parameterToString(*r.filter, ""))
	}
...


// TestFilterParameter struct for TestFilterParameter
type TestFilterParameter struct {
	// Filter.
	Search *string `json:"search,omitempty"`
}
```

but logic is wrong

```go
func parameterToString(obj interface{}, collectionFormat string) string {
	var delimiter string

	switch collectionFormat {
	case "pipes":
		delimiter = "|"
	case "ssv":
		delimiter = " "
	case "tsv":
		delimiter = "\t"
	case "csv":
		delimiter = ","
	}

	if reflect.TypeOf(obj).Kind() == reflect.Slice {
		return strings.Trim(strings.Replace(fmt.Sprint(obj), " ", delimiter, -1), "[]")
	} else if t, ok := obj.(time.Time); ok {
		return t.Format(time.RFC3339)
	}

	return fmt.Sprintf("%v", obj)
}
```

it makes an API call with something like this `"/test?filter=%7B0x14000098dc0%7D"`, because TestFilterParameter implements only json.Marshaler and doesn't implement Stringer/GoStringer

```go
package main

import "fmt"

type TestFilterParameter struct {
	// Filter.
	Search *string `json:"search,omitempty"`
}

func (t TestFilterParameter) GoString() string {
	return "yop"
}

func (t TestFilterParameter) String() string {
	return "yep"
}

func main() {
	s := "query"
	obj := TestFilterParameter{&s}
	fmt.Printf("%v\n", obj)
	fmt.Printf("%#v\n", obj)
}
```

**Comment by kamilsk** [comment] 2022-10-05 08:56
Full example

```go
package main

import (
	"context"
	"fmt"
	"testme/openapi"
)

type TestFilterParameter struct {
	// Filter.
	Search *string `json:"search,omitempty"`
}

func (t TestFilterParameter) GoString() string {
	return "yop"
}

func (t TestFilterParameter) String() string {
	return "yep"
}

func main() {
	q := "query"
	obj := TestFilterParameter{&q}
	fmt.Printf("%v\n", obj)
	fmt.Printf("%#v\n", obj)

	ctx := context.Background()
	cl := openapi.NewAPIClient(openapi.NewConfiguration())

	req := cl.DefaultApi.Test(ctx)
	req = req.Filter(openapi.TestFilterParameter{Search: &q})

	resp, err := cl.DefaultApi.TestExecute(req)
	fmt.Println(resp, err)
}
```

Expected call `/test?filter[search]=query`, not `/test?filter=%7B0x14000098dc0%7D`

**Comment by parvit** [comment] 2022-10-08 09:46
Hi all, i've created a PR for this feature, please review it.

**Comment by parvit** [comment] 2022-10-11 21:45
Any feedback on this?

**Comment by exitflynn** [comment] 2022-10-30 21:11
is this issue still open?

**Comment by parvit** [comment] 2022-10-30 21:56
It should just be merged and closed.

Il Dom 30 Ott 2022, 22:11 Akshit Tyagi ***@***.***> ha
scritto:

**Comment by parvit** [comment] 2022-10-31 06:01
@kamilsk Are you going to approve the completion of the bounty then? Seems unfair that i've done the work and you just close the ticket like that.

**Comment by kamilsk** [comment] 2022-10-31 07:13
@parvit I know nothing about the bounty. I closed it because I no longer wait for it and use a different stack. Feel free to reopen the issue, but I will unsubscribe from it.

**Comment by wing328** [comment] 2022-11-20 07:10
Fixed via https://github.com/OpenAPITools/openapi-generator/pull/13909. Thanks @parvit for the PR.

@altitude Can you please pull the latest master to give it a try and send @parvit the bug bounty if the fix is good? Thanks.

**Closed by wing328** 2022-11-20 07:10 UTC
Labels: Issue: Bug

**Comment by gfyrag** [comment] 2022-11-21 09:59
@wing328 Is the code on the latest docker image?

**Comment by gfyrag** [comment] 2022-11-24 09:14
@wing328 Tested today with the latest image (built 16 hours ago), and same results on my end.

**Comment by wing328** [comment] 2022-11-29 07:48
do you mind sharing the spec so that we can use it to reproduce the issue?

**Comment by gfyrag** [comment] 2022-11-29 14:57
@wing328 Retested from scratch with latest image, and it works as expected. Don't know why it was failing few days ago. Maybe a problem between the keyboard and the chair.
