### ISSUE TITLE
[BUG][PYTHON]  null in nullable array items and inhomogeneous array items raises AttributeError in model_utils.py:model_to_dict

### ISSUE THREAD

**Issue by MAKOMO** [OpenAPITools/openapi-generator#8770] opened 2021-02-19 15:58 UTC
#### Bug Report Checklist

- [ ] Have you provided a full/minimal spec to reproduce the issue?
- [x] Have you validated the input using an OpenAPI validator ([example](https://apidevtools.org/swagger-parser/online/))?
- [x] Have you [tested with the latest master](https://github.com/OpenAPITools/openapi-generator/wiki/FAQ#how-to-test-with-the-latest-master-of-openapi-generator) to confirm the issue still exists?
- [x] Have you searched for related issues/PRs?
- [x] What's the actual output vs expected output?
- [ ] [Optional] Sponsorship to speed up the bug fix or feature request ([example](https://github.com/OpenAPITools/openapi-generator/issues/6178))

##### Description

A method returning an object with property `additionalData` defined as follows

```yaml
  additionalData:
    type: array
    nullable: true
    items:
      type: object
      properties:
        labels:
          type: array
          items:
             type: string
             nullable: true
```

raises

```
  File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/site-packages/project-0.0.1-py3.9.egg/artisanplus/model_utils.py", line 1488, in model_to_dict
AttributeError: 'NoneType' object has no attribute '_composed_schemas'
```

in the generated code on printing the received object

```yaml
        {
          "labels": [
            null,
            "Test"
          ]
        }
```

I am aware that `nullable` is deprecated in OpenAPI v3.1.0, but it seems to me that the syntax

```yaml
      properties:
        labels:
          type: array
          items:
             type: ['string', 'null']
```

is not yet supported by OpenAPI-generator. Anyhow, the objects handled by the generated Python code should be able to render arrays with null values.

##### openapi-generator version

Tested with trunk of today and v5.0.1

##### Generation Details

```bash
# cd openapi-generator
# ./mvnw clean install
# cd ..
# mkdir _build
# PYTHON_POST_PROCESS_FILE='$(which yapf) -i' java -jar openapi-generator/modules/openapi-generator-cli/target/openapi-generator-cli.jar generate -i ./project.yaml -g python -o ./_build/client/ -c config.json
# cd _build/client
# sudo python3 setup.py install
```

with `config.json`:

```
{
  "packageName":"project",
  "projectName":"project",
  "packageVersion":"0.0.1",
  "pythonAttrNoneIfUnset": true
}
```

##### Steps to reproduce

The exception should be raised on printing any object with an array containing null items.

##### Related issues/PRs

Related to https://github.com/OpenAPITools/openapi-generator/pull/8652 which fixes another (non-overlapping) issue in the `model_to_dict` function.
Related issue https://github.com/OpenAPITools/openapi-generator/issues/8651

##### Suggest a fix

Totally new to this project, but it seems to me that the method `model_to_dict` in the generated `model_utils.py` does not handle the case of null values (None) well (at least not within lists).

I suggest to add the test if `model_instance is None` as follows to `modules/openapi-generator/src/main/resources/python/model_utils.mustache`.

```
def model_to_dict(model_instance, serialize=True):
    """Returns the model properties as a dict

    Args:
        model_instance (one of your model instances): the model instance that
            will be converted to a dict.

    Keyword Args:
        serialize (bool): if True, the keys in the dict will be values from
            attribute_map
    """
    if model_instance is None:
       return None

    result = {}

    model_instances = [model_instance]
   ....
```

**Comment by MAKOMO** [comment] 2021-02-19 19:58
a better fix then just testing `model_instance` for a null value at the head of `model_to_dict` is to replace

```
            if isinstance(value, list):
                if not value or isinstance(value[0], PRIMITIVE_TYPES):
                    # empty list or primitive types
                    result[attr] = value
                elif isinstance(value[0], ModelSimple):
                    result[attr] = [x.value for x in value]
                else:
                    result[attr] = [model_to_dict(x, serialize=serialize) for x in value]
            elif isinstance(value, dict):
            ....
```            

by 

 ``` 
            if isinstance(value, list):
                if not value:
                    # empty list or None
                    result[attr] = value
                else:
                    res = []
                    for v in value:
                        if isinstance(v, PRIMITIVE_TYPES) or v is None:
                            res.append(v)
                        elif isinstance(v, ModelSimple):
                            res.append(v.value)
                        else:
                            res.append(model_to_dict(v, serialize=serialize))
                    result[attr] = res
            ....
```

to also support list of inhomogeneous element types here.

**Comment by spacether** [comment] 2021-04-01 16:08
@MAKOMO I was attempting to fix this bug but I am unable to reproduce it with a v3 spec:
My PR that demonstrates this is here: https://github.com/OpenAPITools/openapi-generator/pull/9153
In it I included your sample schema in two endpoints. One where the schema is refed, another where it is inline.
For both endpoints I tested that serialization and deserialization work and no generator code needed to change.

Is this a v2 spec issue?
If I don't hear anything back in a week or two I will close this as unreproducible.

**Comment by spacether** [comment] 2021-04-01 16:56
Update: I was able to reproduce it. The ingested data needs to be [None, 'foo'] NOT ['foo', None]

**Comment by MAKOMO** [comment] 2021-04-01 17:51
I observed those issues with a v3 spec. 

One issue is just visible in the original code. For example:

```
elif isinstance(value[0], ModelSimple):
                    result[attr] = [x.value for x in value]

```
Here only the first element of the array `value` in the first line and the second line assumes that this array has only elements of the same type, which is not true in general.

Instead one needs to traverse the potential inhomogeneous array and decide per element type how to treat it.

Let me know if you need anything further from me to get this fixed.

Thanks for working on this,
Marko

**Closed** 2021-04-01 20:34 UTC
Labels: Client: Python, Issue: Bug
