### ISSUE TITLE
brew installed v6.5.0 generate python error

### ISSUE THREAD

**Issue by tongtie** [OpenAPITools/openapi-generator#15219] opened 2023-04-14 10:48 UTC
ruby is OK
<img width="1242" alt="image" src="https://user-images.githubusercontent.com/2959046/232023987-f796b00b-f5e4-4be7-b296-dd4167b22a83.png">

but change to python, it report errors:

```
[main] INFO  o.o.codegen.DefaultGenerator - Generating with dryRun=false
[main] INFO  o.o.c.ignore.CodegenIgnoreProcessor - Output directory (/tmp/test2) does not exist, or is inaccessible. No file (.openapi-generator-ignore) will be evaluated.
[main] INFO  o.o.codegen.DefaultGenerator - OpenAPI Generator: python (client)
[main] INFO  o.o.codegen.DefaultGenerator - Generator 'python' is considered stable.
[main] INFO  o.o.c.l.AbstractPythonCodegen - Environment variable PYTHON_POST_PROCESS_FILE not defined so the Python code may not be properly formatted. To define it, try 'export PYTHON_POST_PROCESS_FILE="/usr/local/bin/yapf -i"' (Linux/Mac)
[main] INFO  o.o.c.l.AbstractPythonCodegen - NOTE: To enable file post-processing, 'enablePostProcessFile' must be set to `true` (--enable-post-process-file for CLI).
[main] INFO  o.o.c.ignore.CodegenIgnoreProcessor - Output directory (/tmp/test2) does not exist, or is inaccessible. No file (.openapi-generator-ignore) will be evaluated.
[main] INFO  o.o.c.languages.PythonClientCodegen - Environment variable PYTHON_POST_PROCESS_FILE not defined so the Python code may not be properly formatted. To define it, try 'export PYTHON_POST_PROCESS_FILE="/usr/local/bin/yapf -i"' (Linux/Mac)
[main] INFO  o.o.c.languages.PythonClientCodegen - NOTE: To enable file post-processing, 'enablePostProcessFile' must be set to `true` (--enable-post-process-file for CLI).
[main] INFO  o.o.c.languages.PythonClientCodegen - generateAliasAsModel is hard coded to true in this generator. Alias models will only be generated if they contain validations or enums
Exception in thread "main" java.lang.RuntimeException: Could not generate model 'ApiResponse'
        at org.openapitools.codegen.DefaultGenerator.generateModels(DefaultGenerator.java:569)
        at org.openapitools.codegen.DefaultGenerator.generate(DefaultGenerator.java:926)
        at org.openapitools.codegen.cmd.Generate.execute(Generate.java:487)
        at org.openapitools.codegen.cmd.OpenApiGeneratorCommand.run(OpenApiGeneratorCommand.java:32)
        at org.openapitools.codegen.OpenAPIGenerator.main(OpenAPIGenerator.java:66)
Caused by: com.github.jknack.handlebars.HandlebarsException: model.handlebars:3:3: java.lang.reflect.InaccessibleObjectException: Unable to make field transient java.util.HashMap$Node[] java.util.HashMap.table accessible: module java.base does not "opens java.util" to unnamed module @b6ba78c
    model.handlebars:3:3
        at java.base/java.lang.reflect.AccessibleObject.throwInaccessibleObjectException(AccessibleObject.java:387)
        at java.base/java.lang.reflect.AccessibleObject.checkCanSetAccessible(AccessibleObject.java:363)
        at java.base/java.lang.reflect.AccessibleObject.checkCanSetAccessible(AccessibleObject.java:311)
        at java.base/java.lang.reflect.Field.checkCanSetAccessible(Field.java:181)
        at java.base/java.lang.reflect.Field.setAccessible(Field.java:175)
        at com.github.jknack.handlebars.context.FieldValueResolver$FieldMember.setAccessible(FieldValueResolver.java:150)
        at com.github.jknack.handlebars.context.MemberValueResolver.cache(MemberValueResolver.java:82)
        at com.github.jknack.handlebars.context.MemberValueResolver.resolve(MemberValueResolver.java:54)
        at com.github.jknack.handlebars.Context$CompositeValueResolver.resolve(Context.java:199)
        at com.github.jknack.handlebars.internal.path.PropertyPath.eval(PropertyPath.java:52)
        at com.github.jknack.handlebars.Context$PathExpressionChain.next(Context.java:361)
        at com.github.jknack.handlebars.Context$PathExpressionChain.eval(Context.java:381)
        at com.github.jknack.handlebars.Context.get(Context.java:618)
        at com.github.jknack.handlebars.internal.Partial.override(Partial.java:253)
        at com.github.jknack.handlebars.internal.Partial.merge(Partial.java:226)
        at com.github.jknack.handlebars.internal.BaseTemplate.apply(BaseTemplate.java:125)
        at com.github.jknack.handlebars.internal.TemplateList.merge(TemplateList.java:95)
        at com.github.jknack.handlebars.internal.BaseTemplate.apply(BaseTemplate.java:125)
        at com.github.jknack.handlebars.internal.BaseTemplate.apply(BaseTemplate.java:113)
        at org.openapitools.codegen.templating.HandlebarsEngineAdapter.compileTemplate(HandlebarsEngineAdapter.java:92)
        at org.openapitools.codegen.TemplateManager.write(TemplateManager.java:163)
        at org.openapitools.codegen.DefaultGenerator.processTemplateToFile(DefaultGenerator.java:1072)
        at org.openapitools.codegen.DefaultGenerator.processTemplateToFile(DefaultGenerator.java:1059)
        at org.openapitools.codegen.DefaultGenerator.generateModel(DefaultGenerator.java:408)
        at org.openapitools.codegen.DefaultGenerator.generateModels(DefaultGenerator.java:560)
        ... 4 more
Caused by: java.lang.reflect.InaccessibleObjectException: Unable to make field transient java.util.HashMap$Node[] java.util.HashMap.table accessible: module java.base does not "opens java.util" to unnamed module @b6ba78c
```

my os is :
<img width="353" alt="image" src="https://user-images.githubusercontent.com/2959046/232024514-8ea1b9d9-eb66-489e-86dd-645f2248c624.png">

I installed it by homebrew and the version is : 6.5.0

**Comment by tongtie** [comment] 2023-04-14 10:49
the java version is : 
openjdk version "20" 2023-03-21
OpenJDK Runtime Environment Homebrew (build 20)
OpenJDK 64-Bit Server VM Homebrew (build 20, mixed mode, sharing)

**Comment by spacether** [comment] 2023-04-14 14:43
Thank you for reporting this. Can you please provide a sample spec which demonstrates the issue? Otherwise there is no way to root cause this bug or fix it.

**Comment by tongtie** [comment] 2023-04-15 01:18
the petsotore.yaml in the doc

**Comment by spacether** [comment] 2023-04-16 19:45
I was able to reproduce this issue with the latest brew installed tool.

Some verification using docker images:

### openapi-generator
- [WORKS] 6.5.0 `docker run --rm -v "${PWD}:/local" openapitools/openapi-generator-cli:v6.5.0 generate -i https://raw.githubusercontent.com/openapitools/openapi-generator/master/modules/openapi-generator/src/test/resources/3_0/petstore.yaml -g python -o /local/out/python`

### similar-to project, openapi-json-schema-generator:
- [WORKS] v2.0.0 works `docker run --rm -v "${PWD}:/local" openapjsonschematools/openapi-json-schema-generator-cli:2.0.0 generate     -i https://raw.githubusercontent.com/openapi-json-schema-tools/openapi-json-schema-generator/master/modules/openapi-json-schema-generator/src/test/resources/3_0/petstore.yaml     -g python     -o /local/out/python`
- [WORKS] v1.0.4 works `docker run --rm -v "${PWD}:/local" openapjsonschematools/openapi-json-schema-generator-cli:1.0.4 generate     -i https://raw.githubusercontent.com/openapi-json-schema-tools/openapi-json-schema-generator/master/modules/openapi-json-schema-generator/src/test/resources/3_0/petstore.yaml     -g python     -o /local/out/python`
- The v1.0.4 release is nearly identical to the openapi-generator v6.3.0 release

I suspect this is caused by using a newer java version and the handlebars library using reflection.
Earlier I noticed this issue and fixed it in my new [openapi-json-schema generator repo](https://github.com/openapi-json-schema-tools/openapi-json-schema-generator) in [this PR](https://github.com/openapi-json-schema-tools/openapi-json-schema-generator/pull/129), which is built into the v2.0.0 release.

@tongtie 
- What is you java version?
- Does the issue go away if you compile openapi-json-schema generator locally with the version 2 release?

### Some Work Arounds
- use the docker image of openapi-json-schem-generator
- switch to the new project [openapi-json-schema generator v2.0.0 or later](https://github.com/openapi-json-schema-tools/openapi-json-schema-generator)

**Comment by tongtie** [comment] 2023-04-17 07:26
> I was able to reproduce this issue with the latest brew installed tool.
> 
> Here is some testing using docker images:
> 
> ### openapi-generator
> * [WORKS] 6.5.0 `docker run --rm -v "${PWD}:/local" openapitools/openapi-generator-cli:v6.5.0 generate -i https://raw.githubusercontent.com/openapitools/openapi-generator/master/modules/openapi-generator/src/test/resources/3_0/petstore.yaml -g python -o /local/out/python`
> 
> ### similar-to project, openapi-json-schema-generator:
> * [WORKS] v2.0.0 works `docker run --rm -v "${PWD}:/local" openapjsonschematools/openapi-json-schema-generator-cli:2.0.0 generate     -i https://raw.githubusercontent.com/openapi-json-schema-tools/openapi-json-schema-generator/master/modules/openapi-json-schema-generator/src/test/resources/3_0/petstore.yaml     -g python     -o /local/out/python`
> * [WORKS] v1.0.4 works `docker run --rm -v "${PWD}:/local" openapjsonschematools/openapi-json-schema-generator-cli:1.0.4 generate     -i https://raw.githubusercontent.com/openapi-json-schema-tools/openapi-json-schema-generator/master/modules/openapi-json-schema-generator/src/test/resources/3_0/petstore.yaml     -g python     -o /local/out/python`
>   
>   * The v1.0.4 release is nearly identical to the openapi-generator v6.3.0 release
> 
> I suspect this is caused by using a newer java version and the handlebars library using reflection. Earlier I noticed this issue and fixed it in my new [openapi-json-schema generator repo](https://github.com/openapi-json-schema-tools/openapi-json-schema-generator) in [this PR](https://github.com/openapi-json-schema-tools/openapi-json-schema-generator/pull/129), which is built into the v2.0.0 release.
> 
> @tongtie
> 
> * Does the issue go away if you compile openapi-json-schema generator locally with the version 2.0.0 release?
> 
> ### Some Work Arounds
> * use the docker image of [openapi-generator](https://hub.docker.com/r/openapitools/openapi-generator-cli/) or [openapi-json-schem-generator](https://hub.docker.com/r/openapjsonschematools/openapi-json-schema-generator-cli/)
> * switch to the new project [openapi-json-schema generator v2.0.0 or later](https://github.com/openapi-json-schema-tools/openapi-json-schema-generator)

I used this , It is worked. thank you
```
docker run --rm -v "${PWD}:/local" openapjsonschematools/openapi-json-schema-generator-cli:2.0.0 generate     -i https://raw.githubusercontent.com/openapi-json-schema-tools/openapi-json-schema-generator/master/modules/openapi-json-schema-generator/src/test/resources/3_0/petstore.yaml     -g python     -o /local/out/python
```

**Comment by SalvatoreT** [comment] 2023-05-03 22:34
I'm also seeing this same error. You can repro it here.

```
❯ openapi-generator generate \
  --input-spec https://raw.githubusercontent.com/OAI/OpenAPI-Specification/main/examples/v3.0/petstore.json \
  --generator-name python
```

Generates the following:
```
[main] INFO  o.o.codegen.DefaultGenerator - Generating with dryRun=false
[main] INFO  o.o.c.ignore.CodegenIgnoreProcessor - No .openapi-generator-ignore file found.
[main] INFO  o.o.codegen.DefaultGenerator - OpenAPI Generator: python (client)
[main] INFO  o.o.codegen.DefaultGenerator - Generator 'python' is considered stable.
[main] INFO  o.o.c.l.AbstractPythonCodegen - Environment variable PYTHON_POST_PROCESS_FILE not defined so the Python code may not be properly formatted. To define it, try 'export PYTHON_POST_PROCESS_FILE="/usr/local/bin/yapf -i"' (Linux/Mac)
[main] INFO  o.o.c.l.AbstractPythonCodegen - NOTE: To enable file post-processing, 'enablePostProcessFile' must be set to `true` (--enable-post-process-file for CLI).
[main] INFO  o.o.c.ignore.CodegenIgnoreProcessor - No .openapi-generator-ignore file found.
[main] INFO  o.o.c.languages.PythonClientCodegen - Environment variable PYTHON_POST_PROCESS_FILE not defined so the Python code may not be properly formatted. To define it, try 'export PYTHON_POST_PROCESS_FILE="/usr/local/bin/yapf -i"' (Linux/Mac)
[main] INFO  o.o.c.languages.PythonClientCodegen - NOTE: To enable file post-processing, 'enablePostProcessFile' must be set to `true` (--enable-post-process-file for CLI).
[main] INFO  o.o.c.languages.PythonClientCodegen - generateAliasAsModel is hard coded to true in this generator. Alias models will only be generated if they contain validations or enums
Exception in thread "main" java.lang.RuntimeException: Could not generate model 'Error'
        at org.openapitools.codegen.DefaultGenerator.generateModels(DefaultGenerator.java:569)
        at org.openapitools.codegen.DefaultGenerator.generate(DefaultGenerator.java:926)
        at org.openapitools.codegen.cmd.Generate.execute(Generate.java:487)
        at org.openapitools.codegen.cmd.OpenApiGeneratorCommand.run(OpenApiGeneratorCommand.java:32)
        at org.openapitools.codegen.OpenAPIGenerator.main(OpenAPIGenerator.java:66)
Caused by: com.github.jknack.handlebars.HandlebarsException: model.handlebars:3:3: java.lang.reflect.InaccessibleObjectException: Unable to make field transient java.util.HashMap$Node[] java.util.HashMap.table accessible: module java.base does not "opens java.util" to unnamed module @b6ba78c
    model.handlebars:3:3
        at java.base/java.lang.reflect.AccessibleObject.throwInaccessibleObjectException(AccessibleObject.java:387)
        at java.base/java.lang.reflect.AccessibleObject.checkCanSetAccessible(AccessibleObject.java:363)
        at java.base/java.lang.reflect.AccessibleObject.checkCanSetAccessible(AccessibleObject.java:311)
        at java.base/java.lang.reflect.Field.checkCanSetAccessible(Field.java:181)
        at java.base/java.lang.reflect.Field.setAccessible(Field.java:175)
        at com.github.jknack.handlebars.context.FieldValueResolver$FieldMember.setAccessible(FieldValueResolver.java:150)
        at com.github.jknack.handlebars.context.MemberValueResolver.cache(MemberValueResolver.java:82)
        at com.github.jknack.handlebars.context.MemberValueResolver.resolve(MemberValueResolver.java:54)
        at com.github.jknack.handlebars.Context$CompositeValueResolver.resolve(Context.java:199)
        at com.github.jknack.handlebars.internal.path.PropertyPath.eval(PropertyPath.java:52)
        at com.github.jknack.handlebars.Context$PathExpressionChain.next(Context.java:361)
        at com.github.jknack.handlebars.Context$PathExpressionChain.eval(Context.java:381)
        at com.github.jknack.handlebars.Context.get(Context.java:618)
        at com.github.jknack.handlebars.internal.Partial.override(Partial.java:253)
        at com.github.jknack.handlebars.internal.Partial.merge(Partial.java:226)
        at com.github.jknack.handlebars.internal.BaseTemplate.apply(BaseTemplate.java:125)
        at com.github.jknack.handlebars.internal.TemplateList.merge(TemplateList.java:95)
        at com.github.jknack.handlebars.internal.BaseTemplate.apply(BaseTemplate.java:125)
        at com.github.jknack.handlebars.internal.BaseTemplate.apply(BaseTemplate.java:113)
        at org.openapitools.codegen.templating.HandlebarsEngineAdapter.compileTemplate(HandlebarsEngineAdapter.java:92)
        at org.openapitools.codegen.TemplateManager.write(TemplateManager.java:163)
        at org.openapitools.codegen.DefaultGenerator.processTemplateToFile(DefaultGenerator.java:1072)
        at org.openapitools.codegen.DefaultGenerator.processTemplateToFile(DefaultGenerator.java:1059)
        at org.openapitools.codegen.DefaultGenerator.generateModel(DefaultGenerator.java:408)
        at org.openapitools.codegen.DefaultGenerator.generateModels(DefaultGenerator.java:560)
        ... 4 more
Caused by: java.lang.reflect.InaccessibleObjectException: Unable to make field transient java.util.HashMap$Node[] java.util.HashMap.table accessible: module java.base does not "opens java.util" to unnamed module @b6ba78c
        ... 29 more
```

I'm also using the brew install of it. ([Formula source](https://github.com/Homebrew/homebrew-core/blob/2bf6ad7cf8fd09b234b85fc951206fc1956f24f6/Formula/openapi-generator.rb))
```
❯ which openapi-generator
/opt/homebrew/bin/openapi-generator
```

**Comment by SalvatoreT** [comment] 2023-05-03 23:07
Ah, sorry! Thought you hadn't yet reproduced the issue. The two of you have very similar profile graphics, so I got confused. 😓

**Comment by pbarnes-tibco** [comment] 2023-05-04 16:32
We've run into this as well at my company, using the openapi-generator-maven-plugin, openapi generator 6.5.0, and the Python client generator. Looks like OS is irrelevant, and problem would probably occur when building with Java 17+ due to the internal use of reflection. And based on the call stacks in the exceptions, I'm guessing it would happen with any language using the handlebars engine; could be wrong tho. I just don't see python gen specific code in the stacks.

**Comment by spacether** [comment] 2023-05-04 22:11
@pbarnes-tibco are you able to use a higher version of java with
https://github.com/openapi-json-schema-tools/openapi-json-schema-generator v2.0.0 or later? [This PR](https://github.com/openapi-json-schema-tools/openapi-json-schema-generator/pull/129) should allow it to work I think.

**Comment by SalvatoreT** [comment] 2023-05-08 19:54
@tongtie and @spacether, generating Python is fixed on `brew`!

Update your installation
```
brew reinstall openapi-generator
```
and then generating Python works!
```
openapi-generator generate \
  --input-spec https://raw.githubusercontent.com/OAI/OpenAPI-Specification/main/examples/v3.0/petstore.json \
  --generator-name python
```

Here's the PR where the version of Java was pinned to 11 (as opposed to Java 20 which doesn't work for whatever reason). https://github.com/Homebrew/homebrew-core/pull/130185

**Comment by spacether** [comment] 2023-05-09 02:33
@SalvatoreT thank you for the fix, closing this issue because your merged brew PR fixed the issue

**Closed by spacether** 2023-05-09 02:33 UTC
Labels: Client: Python, Issue: Bug
