### ISSUE TITLE
Error running python-flask server generated with openapi-generator-cli-3.0.0.jar. 

### ISSUE THREAD

**Issue by fjd1234** [OpenAPITools/openapi-generator#323] opened 2018-06-15 00:26 UTC
I've generated python-flask SDK from petstore.yaml and hit the run time error summarized below. This worked fine with the swager-codegen and it seems "openapi" components is not found. It used to be "swagger". Maybe I'm missing some plugin or need a newer python? Any suggestions?

I've attached the complete backtrace.

Thanks
Frank

Traceback (most recent call last):
  File "/usr/lib/python3.5/site-packages/swagger_spec_validator/common.py", line 24, in wrapper
    return method(*args, **kwargs)
  File "/usr/lib/python3.5/site-packages/swagger_spec_validator/validator20.py", line 141, in validate_json
    cls=Draft4Validator,
  File "/usr/lib/python3.5/site-packages/swagger_spec_validator/ref_validators.py", line 53, in validate
    instance_cls(schema, *args, **kwargs).validate(instance)
  File "/usr/lib/python3.5/site-packages/jsonschema/validators.py", line 130, in validate
    raise error
jsonschema.exceptions.ValidationError: 'components', 'openapi', 'servers' do not match any of the regexes: '^x-'

##### Suggest a fix/enhancement

[petstore_flask.txt](https://github.com/OpenAPITools/openapi-generator/files/2104390/petstore_flask.txt)

**Comment by ackintosh** [comment] 2018-06-17 02:35
@fjd1234 Thanks for reporting this issue.

I've also tried to run python-flask stub (latest master) and got similar errors you reported.

```bash
$ cd openapi-generator
$ bin/python-flask-petstore-python2.sh
$ cd samples/server/petstore/flaskConnexion-python2/
$ pip install -r requirements.txt
$ python -m openapi_server

Traceback (most recent call last):
  File "/usr/local/Cellar/python@2/2.7.15/Frameworks/Python.framework/Versions/2.7/lib/python2.7/runpy.py", line 174, in _run_module_as_main
    "__main__", fname, loader, pkg_name)

...
...
...

<ValidationError: "'swagger' is a required property">)
```

It may caused by the two stuff below:

- the [yaml file](https://github.com/OpenAPITools/openapi-generator/blob/master/samples/server/petstore/flaskConnexion-python2/openapi_server/__main__.py#L11) parsed by connexion is always generated as OpenAPI v3 spec
- connextion doesn't support OpenAPI v3 spec yet
  - It seems just in progress 👀 
  - https://github.com/zalando/connexion/issues/420
  - https://github.com/zalando/connexion/pull/591

**Comment by ackintosh** [comment] 2018-06-18 04:48
cc [Technical committee](https://github.com/OpenAPITools/openapi-generator#62---openapi-generator-technical-committee): @taxpon  @frol  @mbohlool  @cbornet  @kenjones-cisco

**Comment by cbornet** [comment] 2018-06-18 07:02
Indeed, we generate an OAIv3 yaml but flask-connexion doesn't support it yet.
A solution would be to have a mustache tag that contains a v2 version of the spec.

**Comment by fjd1234** [comment] 2018-08-03 11:57
So the issue seems to be that connexion doesn't support openapi v3 and a suggested solution would be to use a mustache tag that conatains v2 version. How would I do this? I'd like to use this codegen to generate python-flask code for v3 specs.

Thanks
Frank

**Comment by abdullin** [comment] 2018-08-27 11:44
Still the same error with 3.2.2 of the generator. I couldn't find any documentation on how to make openapi generator work with python-flask with any version of the spec.

To avoid confusion, I would propose to remove "python-flask" from the list of the generators on the home page.

**Comment by wheelsandmetal** [comment] 2018-08-31 19:29
I would also like the ability to generate a OAIv2/Swagger v2 spec until such a time as connexion can fully support v3

**Comment by wing328** [comment] 2018-09-01 04:14
Here is the PR to support OpenAPI spec v3 in connexion: https://github.com/zalando/connexion/pull/621

**Comment by cbornet** [comment] 2018-09-18 15:19
The PR has been merged and will be part of connexion 2.0 : https://github.com/zalando/connexion/milestone/10

**Comment by wing328** [comment] 2018-09-20 11:49
UPDATE: @cbornet has made a fix (workaround) to the Python Flask generator before connexion 2.0 is officially released.

Please give it a try

**Closed** 2018-11-06 10:37 UTC
Labels: Issue: Bug, Server: Python

**Comment by wing328** [comment] 2018-11-07 14:39
The Python flask generator has been updated to use flask-connexion 2.0.0 stable version. Please pull the latest master to give it a try.
