### ISSUE TITLE
schemas are blank in html2 generatation

### ISSUE THREAD

**Issue by jcald1** [OpenAPITools/openapi-generator#3788] opened 2019-08-28 20:52 UTC
I pulled the latest openapitools/openapi-generator-cli Docker image: 193486a2ca74 

Command:

`docker run --rm -w /local -v ${PWD}:/local openapitools/openapi-generator-cli generate     -i openapi.yaml     -g html2`

Opened the generated `index.html` file and saw that all of the schemas were blank.  When I ran the html2 generator in https://github.com/swagger-api/swagger-codegen, the schemas were populated.

openapi.yaml:
https://raw.githubusercontent.com/PresencePG/grip-server/feature/time-series/documentation/openapi.yaml?token=ABKWFWZBSGDI6FYD4JA4IWS5OAR5Q

**Comment by JogoShugh** [comment] 2020-04-15 13:12
Any updates on this? I see the same behavior.

**Comment by bachorp** [comment] 2021-03-11 06:24
I ran into the problem that a single schema was blank. In my case this was fixed by turning
```yaml
... :
    schema:
        $ref: '#/components/schemas/X'
components:
    schemas:
        X:
            type: array
            items:
                $ref: '#/components/schemas/Y'
        Y:
            ...
```
into
```yaml
... :
    schema:
        type: array
        items:
            $ref: '#/components/schemas/Y'
components:
    schemas:
        Y:
            ...
```
This might be related to this issue.
The first snippet used to work, however, in an old version of openapi-generator. So there seems to be a regression.

**Comment by nmandya** [comment] 2021-05-31 03:21
Any update on this? I am facing the same issue too.

**Comment by haydenm315** [comment] 2022-08-09 13:31
> Any update on this? I am facing the same issue too.

May want to try openapigenerator version 6.0.0.  Something broke in 6.0.1 regarding schema refs. https://github.com/OpenAPITools/openapi-generator/issues/12842

**Comment by rittelle** [comment] 2022-10-04 13:14
This also happened to me on version 6.0.2 (from the Arch repositories), but without using any references.
Here is a (sort of) minimal example that results in empty schemas:
```yaml
openapi: 3.0.3
info:
  title: Minimal example
  description: |-
    description …
  contact:
    email: test@example.org
  license:
    name: proprietary
    # url: http://www.apache.org/licenses/LICENSE-2.0.html
  version: 0.1
paths:
  /test:
    post:
      operationId: test
      responses:
        '200':
          description: Success
          content:
            application/json:
              schema:
                type: object
                properties:
                  enabled:
                    type: boolean
        '405':
          description: Some reason
      security: []
```

I build the documentation with:
```
$ openapi-generator-cli generate -i example.yaml -g html2 -o output
```

**Comment by rittelle** [comment] 2022-10-04 13:24
And I did some further testing.  The example above is broken in version 6.0.1 but works in 6.0.0.  So it seems to be a regression in version 6.0.1.
Both version were from the Arch Package Archive (if that matters).
I don't have the time to investigate further atm.  For now, I'll stay at 6.0.0, but going forward, I can see this becoming a deal breaker for me :/ .

Oh and I forgot to mention that examples are not rendered as well (yes, the example given above does not include one).

**Closed as completed** 2024-04-12 13:16 UTC
Labels: Issue: Bug, Client: HTML
