### ISSUE TITLE
[REQ] Add support for OpenAPI 3.1

### ISSUE THREAD

**Issue by bilalshaikh42** [OpenAPITools/openapi-generator#10811] opened 2021-11-08 13:13 UTC
### Is your feature request related to a problem? Please describe.

Unable to use code generation with OpenAPI version 3.1 specifications

## Describe the solution you'd like

Add support for OASv 3.1
## Describe alternatives you've considered

Currently, I am simply changing the version number included in the spec and disabling spec validation. This works just fine, since the only incompatible change that I am dealing with is the use of "examples" as a list instead of a single value. While the spec is invalid when doing this, it is still parsed and generates code just fine. 

This approach would not work for some of the other changes, however. 

## Additional Context

Here are the major changes from the [release announcement:](https://www.openapis.org/blog/2021/02/18/openapi-specification-3-1-released)

Major Changes in OpenAPI Specification 3.1.0

- JSON Schema vocabularies alignment
- New top-level element for describing Webhooks that are registered and managed out of band
- Support for identifying API licenses using the standard SPDX identifier
- PathItems object is now optional to make it simpler to create reusable libraries of components. Reusable PathItems can be described in the components object. There is also support for describing APIs secured using client certificates.

**Comment by thetric** [comment] 2021-11-08 16:27
Duplicate of #9083

**Comment by bilalshaikh42** [comment] 2021-11-08 20:43
Thanks! Somehow missed it when searching.

**Closed** 2021-11-09 06:46 UTC
Labels: Enhancement: Feature

**Comment by antonio-petricca** [comment] 2022-01-05 13:29
Is it planned the support for 3.1?
