### ISSUE TITLE
Output of the generator is not working in the cli

### ISSUE THREAD

**Issue by JFCote** [OpenAPITools/openapi-generator#186] opened 2018-05-30 15:27 UTC
##### Description

When I try to put the output of the cli in a text file when doing a generation, it doesn't work. If I do a `validate`, it works.

##### openapi-generator version

Latest master

##### OpenAPI declaration file content or url

Any

##### Command line used for generation

```
java -jar openapi-generator-cli.jar generate -i swagger.yaml --generator-name
java-play-framework -o generatedServer -DhideGenerationTimestamp=true > lol.txt
```

##### Steps to reproduce

Just run the above command line and notice the lol.txt is 0 byte. If you do a `validate `instead, the file is modified as expected.

##### Related issues/PRs

None that I know of.

##### Suggest a fix/enhancement

I really don't know for the moment.

**Comment by jimschubert** [comment] 2018-06-02 18:45
I've noticed this as well. The issue is that some streams used by the generator project don't output to the same file descriptor as stdout/stderr for the CLI. I didn't have a chance to investigate, unfortunately. 

The reason `validate` works is because it to uses the system stdout and stderr streams. I believe with `validate` if you set log levels to debug, the logs from Swagger Parser are also not redirected.

The fix should be a matter of changing root level logging to a ConsoleLogger in the CLI module. There are some `println` calls in the generator project which also don't seem to be redirected, so it seems to me that `System.setOut` may be called somewhere.

**Comment by jimschubert** [comment] 2018-06-03 02:43
I looked into this. The issue was that we are using slf4j-simple in the core generator project. CLI uses this as well, and that implementation only writes to STDERR.

You'd need to do:

```
java -jar openapi-generator-cli.jar generate -i swagger.yaml --generator-name \
    java-play-framework -o generatedServer -DhideGenerationTimestamp=true 2>&1 > lol.txt
```

It's confusing that non-error messages would be written to stdout. I've opened #207 to have intuitive usage of these output streams.

**Comment by jimschubert** [comment] 2018-06-10 17:14
@JFCote #207 has been merged, and should fix this issue. Can you verify?

**Comment by JFCote** [comment] 2018-06-11 12:10
@jimschubert Will validate this today and let you know

**Comment by JFCote** [comment] 2018-06-11 16:38
@jimschubert Confirmed fixed!

**Closed** 2018-06-11 19:33 UTC
Labels: Issue: Bug, OpenAPI Generator CLI
