### ISSUE TITLE
[BUG] "missing OpenAPI input!" Occurs

### ISSUE THREAD

**Issue by yktakaha4** [OpenAPITools/openapi-generator#8679] opened 2021-02-11 12:52 UTC
#### Bug Report Checklist

- [x] Have you provided a full/minimal spec to reproduce the issue?
- [x] Have you validated the input using an OpenAPI validator ([example](https://apidevtools.org/swagger-parser/online/))?
- [x] Have you [tested with the latest master](https://github.com/OpenAPITools/openapi-generator/wiki/FAQ#how-to-test-with-the-latest-master-of-openapi-generator) to confirm the issue still exists?
- [x] Have you searched for related issues/PRs?
- [x] What's the actual output vs expected output?
- [ ] [Optional] Sponsorship to speed up the bug fix or feature request ([example](https://github.com/OpenAPITools/openapi-generator/issues/6178))

##### Description

My `spec.json` fails to load both validate and generate commands.
Since the validate command can be executed in `swagger-parser` (validation result is displayed), I think there is a problem specific to this tool.

I created an issue in this repository because the error was occurring inside `openapi-generator`.

##### openapi-generator version

5.0.1

##### OpenAPI declaration file content or url

Since the file size is large, it is provided as a URL.

https://yktakaha4.s3-ap-northeast-1.amazonaws.com/spec.json

##### Generation Details

Regardless of the generation method specified, the command is failing.

##### Steps to reproduce

```
$ docker run --rm -v $PWD:/vol openapitools/openapi-generator-cli:latest validate -i /vol/spec.json
Validating spec (/vol/spec.json)
Exception in thread "main" java.lang.NullPointerException
        at java.util.HashSet.<init>(HashSet.java:118)
        at org.openapitools.codegen.cmd.Validate.execute(Validate.java:54)
        at org.openapitools.codegen.cmd.OpenApiGeneratorCommand.run(OpenApiGeneratorCommand.java:32)
        at org.openapitools.codegen.OpenAPIGenerator.main(OpenAPIGenerator.java:66)
```

or

```
$ docker run --rm -v $PWD:/vol openapitools/openapi-generator-cli:latest generate -i /vol/spec.json -g python
[main] INFO  o.o.codegen.DefaultGenerator - Generating with dryRun=false
[main] INFO  o.o.c.ignore.CodegenIgnoreProcessor - No .openapi-generator-ignore file found.
Exception in thread "main" java.lang.RuntimeException: missing OpenAPI input!
        at org.openapitools.codegen.DefaultGenerator.generate(DefaultGenerator.java:837)
        at org.openapitools.codegen.cmd.Generate.execute(Generate.java:432)
        at org.openapitools.codegen.cmd.OpenApiGeneratorCommand.run(OpenApiGeneratorCommand.java:32)
        at org.openapitools.codegen.OpenAPIGenerator.main(OpenAPIGenerator.java:66)
```

##### Suggest a fix

I think this issue is due to the size of the input file, but I don't know.

**Comment by GrmpfNarf** [comment] 2021-02-18 08:54
I can confirm this issue for the Java Client to.

**Comment by wing328** [comment] 2021-02-18 09:09
The spec isn't valid:
```
Swagger schema validation failed. 
  Data does not match any schemas from 'oneOf' at #/components/schemas/Label
    Data does not match any schemas from 'oneOf' at #/components/schemas/Label/properties/type
      Expected type array but found type boolean at #/properties/type/required
      Missing required property: $ref at #/properties/type
    Missing required property: $ref at #/components/schemas/Label
  Data does not match any schemas from 'oneOf' at #/components/schemas/KeyResult
    Data does not match any schemas from 'oneOf' at #/components/schemas/KeyResult/properties/type
      Expected type array but found type boolean at #/properties/type/required
      Missing required property: $ref at #/properties/type
    Missing required property: $ref at #/components/schemas/KeyResult
  Data does not match any schemas from 'oneOf' at #/components/schemas/Objective
    Data does not match any schemas from 'oneOf' at #/components/schemas/Objective/properties/type
      Expected type array but found type boolean at #/properties/type/required
      Missing required property: $ref at #/properties/type
    Missing required property: $ref at #/components/schemas/Objective
(result omitted...)
```

Ref: https://apitools.dev/swagger-parser/online/

**Comment by Incstar** [comment] 2021-02-18 14:21
I got that "missing OpenApi input" issue to.

Debugging showed that inside the OpenAPIDeserializer.java class 
in public Server getServer(ObjectNode obj, String location, ParseResult result, String path) method
the final URI absURI = new URI(path);

throws an java.net.URISyntaxException

in my case i had inside my pom file the 
<inputSpec>${project.basedir}/src/main/resources/swagger.json</inputSpec> set and it turns to C:\User\Project/src/main/resources/swagger.json
So the backslash was the problem.

Hope this helps

**Comment by spacether** [comment] 2022-09-16 19:38
Closing because this problem was caused by a spec with invalid values

**Closed by spacether** 2022-09-16 19:38 UTC
Labels: Issue: Bug
