### ISSUE TITLE
[REQ][python-nextgen] datetime serialization format override

### ISSUE THREAD

**Issue by tnielens** [OpenAPITools/openapi-generator#14503] opened 2023-01-21 15:07 UTC
### Is your feature request related to a problem? Please describe.
The backend I'm requesting only supports a subset of the iso datetime format for query parameters.
`2023-01-01T00:00:00.000Z` is parsed correctly, but alternatives like `2023-01-01 00:00:00.000+00:00` or `2023-01-01T00:00:00+00:00` fail.

With the former python generators, api functions support both `datetime` and `str` arguments for datetime parameters. The default datetime serialization format of the generated api code it overridable by passing the str in the correct format. The python-nextgen generator annotates api call methods with `@validate_arguments`. This turns `str` inputs into `datetime`s which results in the default serialization format of the generated api to be used. 

## Describe the solution you'd like

Support datetime and date format overrides at different levels: api_client/specific api/api call.

## Describe alternatives you've considered

Removing the `@validate_arguments` and passing `str`s arguments works. But I'd prefer not modify the generated code.

## Additional context

I'd like to move from the `python-prior` codegen to the new `python-nextgen`.

**Comment by wing328** [comment] 2023-02-17 01:53
closed via https://github.com/OpenAPITools/openapi-generator/pull/14621

**Closed by wing328** 2023-02-17 01:53 UTC
Labels: Client: Python, Enhancement: Feature

**Comment by tnielens** [comment] 2023-02-17 10:41
The extra option doens't seem to work as expected. When the option is used, the parameter type is indeed a `Union[StrictStr, datetime]`, but str arguments are still converted to `datetime` objects when passed to api calls. Which results in the default datetime format being used.

**Comment by wing328** [comment] 2023-02-18 02:55
@tnielens thanks for testing the fix. I've revised the test to show that it's working as expected: https://github.com/OpenAPITools/openapi-generator/pull/14742
```
?datetime_query=19:20:30%202013-10-20
```

As you can see the value of `datetime_query` is the same as the input (string instead of datetime object)

Can you please share a minimal spec so that I can try to reproduce the issue?

**Comment by tnielens** [comment] 2023-02-20 09:35
@wing328 Here is some code that shows that the conversion happens.
```python
from datetime import datetime
from pydantic import StrictStr, validate_arguments

@validate_arguments
def pydantic_test(dt: datetime | StrictStr):
    return dt

pydantic_test("2022-01-01T00:00:00+00:00")
```
prints
```
datetime.datetime(2022, 1, 1, 0, 0, tzinfo=datetime.timezone.utc)
```

Curiously, if the union annotation order is reversed, `StrictStr | datetime`, the call above returns `'2022-01-01T00:00:00+00:00'`, the expected return value. Maybe this is pydantic dependent. I'm using version 1.10.2.

**Comment by wing328** [comment] 2023-02-20 10:10
The test is using the same version.

> Curiously, if the union annotation order is reversed, StrictStr | datetime

I can change the order if that works in your scenario/setup. Will file a PR shortly.

**Comment by wing328** [comment] 2023-02-20 10:25
UPDATE: filed https://github.com/OpenAPITools/openapi-generator/pull/14762 to switch the order. The python tests still passed as expected.

**Comment by tnielens** [comment] 2023-02-20 14:19
> UPDATE: filed https://github.com/OpenAPITools/openapi-generator/pull/14762 to switch the order. The python tests still passed as expected.
@wing328 are you sure datetimes aren't turned in strings now that you reserved the order?

**Comment by tnielens** [comment] 2023-02-20 19:54
So I closed the pydantic issue mentioned hereabove. This behavior is documented in the pydantic doc [unions](https://docs.pydantic.dev/usage/types/#unions), see the section on [smart unions](https://docs.pydantic.dev/usage/model_config/#smart-union). So reversing the order has the effect of turning datetimes into strs which isn't ideal either I guess. Best option seems to enable `smart-unions` it seems.

Also mind this warning from the doc 
> Note that this option does not support compound types yet (e.g. differentiate List[int] and List[str])

I guess that warning applies equally to `Optional[...]` types.

**Comment by wing328** [comment] 2023-02-22 08:48
I did more tests with `def pydantic_test(dt: Union[datetime, StrictStr]):`
```
>>> pydantic_test("2021-02-02 2:20")
datetime.datetime(2021, 2, 2, 2, 20)
>>> pydantic_test("March 28 2021 2:20")
'March 28 2021 2:20'
>>> pydantic_test("19:20:30 2013-10-20")
'19:20:30 2013-10-20'
>>> pydantic_test("2023-01-01 00:00:00.000+00:00")
datetime.datetime(2023, 1, 1, 0, 0, tzinfo=datetime.timezone.utc)
>>> pydantic_test("2023-01-01T00:00:00+00:00")
datetime.datetime(2023, 1, 1, 0, 0, tzinfo=datetime.timezone.utc)
```

so looks like if the input is a string, datetime will make a intelligent guess on the input and create an instance of datetime if possible.

I think we can go ahead with #14762 by placing StrictStr first:
```
Union[StrictStr, datetime]
```

After the users of your Python SDK has switched the input parameter to `datetime`, you can switch off the option to enforce `datetime` as the input parameter.

**Comment by tnielens** [comment] 2023-02-22 09:29
@wing328 
You don't test when users pass in a `datetime` it seems. But pydantic will coerce these `datetime` objects into `str`, so the internal `datetime` handling is made useless if you put `StrictStr` first in the union order.

> you can switch off the option to enforce datetime as the input parameter.

This doesn't address the original issue that the format used to serialize `datetime`objects is not the one we need (backend restriction). As suggested in the issue description, the best solution for us is not the ability to pass `str` in, but to configure the `datetimeformat` of the client instead so we can pass `datetime`s in.

**Comment by wing328** [comment] 2023-02-22 12:51
Just did a test with datetime object:
```
>>> a = datetime.now()
>>> a
datetime.datetime(2023, 2, 22, 20, 48, 38, 926560)
>>> pydantic_test(a)
datetime.datetime(2023, 2, 22, 20, 48, 38, 926560)
```

(with StrictStr first in the union)

I'll try to come up with a solution to allow one to set the `datetimeformat`

**Comment by tnielens** [comment] 2023-02-22 15:24
> Just did a test with datetime object:

Ok my bad, I tested myself as well and you're right. There is something I don't understand in `str` <-> `StrictStr` relation. `StrictStr | datetime` should work. 
Still overriding the datetime format would be the preferred approach to us as it is more strictly typed.

**Comment by wing328** [comment] 2023-02-23 10:37
I've filed https://github.com/OpenAPITools/openapi-generator/pull/14799 to allow overriding the datetime, date format in the query parameters.

Can you please have a quick look to see if it would meet your requirement?

**Comment by tnielens** [comment] 2023-02-24 15:20
@wing328 Sorry to realize this only now but it seems that daetime formatting is not the issue from the beginning but instead the fact that special characters aren't url-encoded. Chars like ":" and "+" aren't encoded. So `2022-01-02T00:00:00+00:00` should be `2022-01-02T00%3A00%3A00%2B00%3A00` in the url.

If the encoding is fixed, formatting shouldn't be an issue in our case. So request of allowing user to configure a print format is secondary. It is more important to fix the encoding of special characters.

About your changes with the `datetime_format`, the default format you're using isn't ISO compliant `%Y-%m-%d %H:%M:%S.%f`. The 'T' letter is missing. Also it doesn't print the offset which is important information to pass on if the input datetime has one. If the configuration isn't set by the user, I would keep using `datetime.isoformat()` and not an other arbitrary format. Also parsing strings with `datetime.strptime(str)` is very flexible as it supports many combinations of fields and formats, I would continue parsing time with that method, and only use the user provided format for printing. Maybe reflect that in the name, like `datetime_print_format`.

 As said above, overriding the format isn't necessary in our case, the issue is the url encoding.

**Comment by wing328** [comment] 2023-02-27 16:51
I've pushed an update to properly encode the query parameter. I didn't notice the issue as I saw space is properly encoded in `%20` 

I've also updated `datetime_format` default to `"%Y-%m-%dT%H:%M:%S%Z` instead. (this is not what python-legacy client uses by default but users can always customize it based on their use cases)

Please give it another try when you've time.

**Comment by tnielens** [comment] 2023-02-27 20:14
Thanks I've tested successfully by overriding the format to `%Y-%m-%dT%H:%M:%S.%f%z`.

Mind that the default format is broken. `%Z` is the timezone name (for example 'UTC', or 'CET'), not its offset. Lowercase `%z` is needed. Also the microseconds are truncated resulting in a precision loss, `%f` prints them. I suggest sticking to `datetime.isoformat()` by default which has the convenient behavior of only printing microseconds if they are not null. See [datetime.isoformat() doc](https://docs.python.org/3/library/datetime.html#datetime.datetime.isoformat).

**Comment by wing328** [comment] 2023-02-28 09:31
I agreed %Z is less commonly used. I've pushed another commit to change the default format to `%Y-%m-%dT%H:%M:%S.%f%z`. As we know, the default won't fit everyone's use cases and they will need to config `datetimeFormat` instead.
