### ISSUE TITLE
[RUST] I don't understand this "Could not process model" error

### ISSUE THREAD

**Issue by dvaerum** [OpenAPITools/openapi-generator#1339] opened 2018-10-29 11:44 UTC
##### Description
I am trying to create a rust lib client for MatterMost using openapi-generator as a base, but I keep running in to this error with I understand nothing of :disappointed: 
```
Could not process model 'inline_object_43'.Please make sure that your schema is correct!
```
and I have no idea what to do, can someone point me in the right direction. Plz keep in mind that I am new to openapi and this tool

##### openapi-generator version

I encounter the problem in version *3.3.1* and *4.0.0-SNAPSHOT*

##### OpenAPI declaration file content or url
The OpenAPI file can be found [here](https://api.mattermost.com/) or [direct link](https://api.mattermost.com/static/mattermost-openapi-v4.yaml)

##### Command line used for generation
I just select the language *rust* and file *mattermost-openapi-v4.yaml*
```
java -jar openapi-generator-cli.jar generate -g rust -i mattermost-openapi-v4.yaml -o test
```

##### Steps to reproduce

1. Download the mattermost-openapi-v4.yaml file
2. Run the command

##### Related issues/PRs
The only case I could find with a similar error is here https://github.com/OpenAPITools/openapi-generator/issues/409 and I still don't understand how that error is used to find the problem

##### Suggest a fix/enhancement
Better error description, maybe link to documentation

**Comment by wing328** [comment] 2018-10-29 14:57
@dvaerum have you tried using online validation tools (e.g. http://apidevtools.org/swagger-parser/online/) to validate the spec and see if there's any error?

**Comment by dvaerum** [comment] 2018-10-30 02:38
I tried the validate in openapi-generator-cli and have now tried this tool too and non of them shows any errors :disappointed:

**Comment by bcourtine** [comment] 2018-11-02 09:07
I can reproduce the problem. Here is the complete stacktrace:

```
[main] WARN  o.o.codegen.utils.ModelUtils - Multiple schemas found, returning only the first one
Exception in thread "main" java.lang.RuntimeException: Could not process model 'inline_object_43'.Please make sure that your schema is correct!
	at org.openapitools.codegen.DefaultGenerator.generateModels(DefaultGenerator.java:435)
	at org.openapitools.codegen.DefaultGenerator.generate(DefaultGenerator.java:845)
	at org.openapitools.codegen.cmd.Generate.run(Generate.java:349)
	at org.openapitools.codegen.OpenAPIGenerator.main(OpenAPIGenerator.java:62)
Caused by: java.lang.NullPointerException
	at org.openapitools.codegen.utils.ModelUtils.isArraySchema(ModelUtils.java:322)
	at org.openapitools.codegen.languages.RustClientCodegen.getTypeDeclaration(RustClientCodegen.java:310)
	at org.openapitools.codegen.languages.RustClientCodegen.getTypeDeclaration(RustClientCodegen.java:313)
	at org.openapitools.codegen.DefaultCodegen.fromProperty(DefaultCodegen.java:1963)
	at org.openapitools.codegen.DefaultCodegen.addVars(DefaultCodegen.java:3380)
	at org.openapitools.codegen.DefaultCodegen.addVars(DefaultCodegen.java:3351)
	at org.openapitools.codegen.DefaultCodegen.addVars(DefaultCodegen.java:3338)
	at org.openapitools.codegen.DefaultCodegen.fromModel(DefaultCodegen.java:1675)
	at org.openapitools.codegen.DefaultGenerator.processModels(DefaultGenerator.java:1079)
	at org.openapitools.codegen.DefaultGenerator.generateModels(DefaultGenerator.java:430)
```

We can see that the problem is located in generic classes, not related to Rust. I could confirm it using others generator (python, ruby, etc.): same error.

Note: java generator does not fail.

**Comment by bcourtine** [comment] 2018-11-02 09:36
Problem occurs when generator overrides `getTypeDeclaration`.

```
if (ModelUtils.isArraySchema(p)) {
            ArraySchema ap = (ArraySchema) p;
            Schema inner = ap.getItems();
            return "Vec<" + getTypeDeclaration(inner) + ">";
        }
```

In above code (from `RustClientCodegen`), inner schema can be null. This case should be verified and defaulted to `String` (It is done in `AbstractJavaCodegen`).

I can fix it for Rust codegen, but others generators should also be verified (at least Python and Ruby generators have the same bug).

**Comment by wing328** [comment] 2018-11-03 14:20
Thanks for the fix by @bcourtine . Closing this issue

**Closed by wing328** 2018-11-03 14:20 UTC

**Comment by dvaerum** [comment] 2018-11-03 22:11
Thanks :smiley:
