### ISSUE TITLE
[typescript] allOf with multiple values is not handled properly

### ISSUE THREAD

**Issue by Fredx87** [OpenAPITools/openapi-generator#927] opened 2018-08-29 13:37 UTC
##### Description
If a schema is defined with the `allOf ` operator with multiple values, the generated model is an interface that extends only the first value.

##### openapi-generator version
3.2.2

##### OpenAPI declaration file content or url
```yaml
openapi: 3.0.0
info:
  title: TestApi
  version: 1.0.0
paths:
  /test:
    get:
      summary: Test
      operationId: testApi
      responses:
        "200":
          description: Ok
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/ModelC"
components:
  schemas:
    ModelA:
      properties:
        foo:
          type: string
    ModelB:
      properties:
        bar:
          type: string
    ModelC:
      allOf:
        - $ref: "#/components/schemas/ModelA"
        - $ref: "#/components/schemas/ModelB"
        - type: object
          properties:
            baz:
              type: string
```

##### Command line used for generation
docker run --rm -v ${PWD}:/local openapitools/openapi-generator-cli:v3.2.2 generate -i /local/swagger.yaml -g typescript-angular -o /local/ts-angular -DngVersion=6.0
docker run --rm -v ${PWD}:/local openapitools/openapi-generator-cli:v3.2.2 generate -i /local/swagger.yaml -g typescript-fetch -o /local/ts-fetch

##### Suggest a fix/enhancement
The model generated for `ModelC` is the following interface:
```typescript
export interface ModelC extends ModelA { 
    baz?: string;
}
```
When it should be:
```typescript
export interface ModelC extends ModelA, ModelB { 
    baz?: string;
}

**Comment by mwoodland** [comment] 2018-08-30 15:06
I've just run into this same issue with the Spring generator, except in that case it's generating classes so multiple inheritance wouldn't work.

**Comment by macjohnny** [comment] 2018-08-31 08:09
@jmini @wing328 do you think this is a general bug? If the target language does not allow extending multiple classes, then the generated model should copy all properties.

**Comment by mwoodland** [comment] 2018-08-31 08:31
@macjohnny for java at least the model could be implementing multiple interfaces instead of  extending a concrete class but I'm guessing that's a fairly big change to the generator.

**Comment by wing328** [comment] 2018-11-01 17:40
Hi folks, I've filed https://github.com/OpenAPITools/openapi-generator/pull/1360 with better inheritance/composition support. Please give it a try and let us know if you've any feedback for us.

**Comment by wing328** [comment] 2018-12-10 16:22
@topce let me look into it...

**Comment by wing328** [comment] 2018-12-10 16:30
> and it should be
```
import { ModelA } from './modelA';
import { ModelB } from './modelB';


export interface ModelC extends ModelA, ModelB { 
    baz?: string;
}
```

Based on my understanding, it should not extends either Model A or B because both the definitions of A & B lack the `discriminator` field, e.g. https://github.com/OAI/OpenAPI-Specification/blob/master/versions/3.0.1.md#models-with-polymorphism-support 

Ref: https://github.com/OAI/OpenAPI-Specification/blob/master/versions/3.0.1.md#composition-and-inheritance-polymorphism

#1360 does not support mutiple inheritance and it becomes a priority now as typescript-angular needs it. I'll see if I can add it in the next few days...

**Comment by topce** [comment] 2018-12-11 16:03
Hi @wing328 
Thank you for fast response bu I do not agree with your opinion.
Here we do not speak about polymorphism.
Do not let extends in interface fool you.
Here it is typical case of composituion 
And both approach interfaces or intersection types are valid .
Regarding polymorphism I think in case of typescript it
Should be implemented as tagged union types
https://github.com/Microsoft/TypeScript/wiki/What's-new-in-TypeScript#tagged-union-types

**Comment by topce** [comment] 2018-12-11 18:42
@wing328 
Not easy to be expert in TypeScript some of smartest developers of Microsoft
every two months give us new version ;-)
As your code example is about class extends not interface extends in my opinion it is not relevant  
for this issue.
Regarding extending interface there is alternative intersection types like @Shockolate wrote in comment above
I prefer both approaches (extending interfaces or type intersection )  then just listing properties
because it is less code generated and less code changed 
for example   
if ModelA is changed we do not need to change ModelC

**Comment by TiFu** [comment] 2018-12-11 21:44
From the spec: `While composition offers model extensibility, it does not imply a hierarchy between the models.`

Extending an interface implies a parent-child relationship in the type hierarchy. This is therefore incorrect in the context of the spec. I think that intersection types would be appropriate to use in this case.

**Comment by topce** [comment] 2018-12-11 21:46
Agree with you

**Comment by topce** [comment] 2018-12-12 11:01
Small example for
@wing328  and @TiFu how polymorphic types could be generated in TypeScript 
```
type huntingSkillType = "clueless" | "lazy" | "adventurous" | "aggressive"

interface PetDiscriminator {
    petType: "Pet"|"Dog"|"Cat"
}

interface PetProperties {
    name: string;
}

interface Pet extends PetDiscriminator , PetProperties {
    petType: "Pet"
}
interface Cat extends PetDiscriminator , PetProperties {
    petType: "Cat";
    huntingSkill: huntingSkillType;
}
interface Dog  extends PetDiscriminator , PetProperties {
    petType: "Dog";
    packSize: number;
}

type PetType = Pet | Cat | Dog;


function getPet(pet: PetType) {
  switch (pet.petType) {
    case "Pet":
      return "Pet" + pet.name;

    case "Dog":
      return `Dog (${pet.packSize})`;

    case "Cat":
      return `Cat (${pet.huntingSkill})`;
  }
}
```

**Comment by topce** [comment] 2018-12-12 11:05
[Playground link](https://www.typescriptlang.org/play/#src=%0D%0Atype%20huntingSkillType%20%3D%20%22clueless%22%20%7C%20%22lazy%22%20%7C%20%22adventurous%22%20%7C%20%22aggressive%22%0D%0A%0D%0Ainterface%20PetDiscriminator%20%7B%0D%0A%20%20%20%20petType%3A%20%22Pet%22%7C%22Dog%22%7C%22Cat%22%0D%0A%7D%0D%0A%0D%0Ainterface%20PetProperties%20%7B%0D%0A%20%20%20%20name%3A%20string%3B%0D%0A%7D%0D%0A%0D%0Ainterface%20Pet%20extends%20PetDiscriminator%20%2C%20PetProperties%20%7B%0D%0A%20%20%20%20petType%3A%20%22Pet%22%0D%0A%7D%0D%0Ainterface%20Cat%20extends%20PetDiscriminator%20%2C%20PetProperties%20%7B%0D%0A%20%20%20%20petType%3A%20%22Cat%22%3B%0D%0A%20%20%20%20huntingSkill%3A%20huntingSkillType%3B%0D%0A%7D%0D%0Ainterface%20Dog%20%20extends%20PetDiscriminator%20%2C%20PetProperties%20%7B%0D%0A%20%20%20%20petType%3A%20%22Dog%22%3B%0D%0A%20%20%20%20packSize%3A%20number%3B%0D%0A%7D%0D%0A%0D%0Atype%20PetType%20%3D%20Pet%20%7C%20Cat%20%7C%20Dog%3B%0D%0A%0D%0A%0D%0Afunction%20getPet(pet%3A%20PetType)%20%7B%0D%0A%20%20switch%20(pet.petType)%20%7B%0D%0A%20%20%20%20case%20%22Pet%22%3A%0D%0A%20%20%20%20%20%20return%20%22Pet%22%20%2B%20pet.name%3B%0D%0A%0D%0A%20%20%20%20case%20%22Dog%22%3A%0D%0A%20%20%20%20%20%20return%20%60Dog%20(%24%7Bpet.packSize%7D)%60%3B%0D%0A%0D%0A%20%20%20%20case%20%22Cat%22%3A%0D%0A%20%20%20%20%20%20return%20%60Cat%20(%24%7Bpet.huntingSkill%7D)%60%3B%0D%0A%20%20%7D%0D%0A%7D) of above example

**Comment by wing328** [comment] 2018-12-16 11:17
I've filed: https://github.com/OpenAPITools/openapi-generator/issues/927 and here is what I got for [allOfMultiParent.yaml](https://github.com/OpenAPITools/openapi-generator/blob/master/modules/openapi-generator/src/test/resources/3_0/allOfMultiParent.yaml)

```
import { Child } from './child';
import { Human } from './human';
import { Person } from './person';


/**
 * A representation of an adult
 */
export interface Adult extends Person, Human {
    duplicatedOptional?: number;
    duplicatedRequired: number;
    children?: Array<Child>;
    adultRequired?: boolean;
}
```

This is far from complete but I think at least we're heading the right direction.

**Comment by topce** [comment] 2018-12-17 09:57
**Thank you @wing328 !**
If fix also this problem by coping all properties in new interface (original problem of this issue).
it generate something like this
```
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { ModelA } from './modelA';
import { ModelB } from './modelB';


export interface ModelC { 
    foo?: string;
    bar?: string;
    baz?: string;
}
```
**I prefer generated code like before with extended interfaces or intersection types  (less code , less complicated, less duplication of code** ).
By the way it looks that 2 import lines are not necessary anymore .

**Comment by oscarCrespo** [comment] 2019-01-11 20:51
Thanks for fixing this, we're experimenting the same issue. Will this changes applied to the **Typescript-Axios** template as well?

**Comment by amakhrov** [comment] 2020-01-31 06:22
Looks like currently both typescript-angular and typescript-axios handle this properly (and identically):
- `allOf` when one of the referenced schemas has `discriminator`: extends the discriminated base interface
`allOf` without any `discriminator`: all properties from referenced schemas are cloned into the target interface

**Comment by topce** [comment] 2020-03-26 14:26
Hi  @macjohnny @wing328  @amakhrov 

It looks like for some time this is broken 

before 
```typecript
import { Node } from './node';
import { Attachment } from './attachment';
import { ArchiveNodeAllOf } from './archiveNodeAllOf';

export interface ArchiveNode {
  id?: string;
  type?: string;
  service?: ArchiveNode.ServiceEnum;
  name?: string;
  /**
   * The object that is used to compile all the translations of a node into a JSON object. It is basically composed of a map with a key languaguage code and its value
   */
  title?: { [key: string]: string };
  /**
   * The object that is used to compile all the translations of a node into a JSON object. It is basically composed of a map with a key languaguage code and its value
   */
  description?: { [key: string]: string };
  properties?: { [key: string]: string };
  /**
   * Representation of the permissions given to the user making the call. To know what are the permissions for the specific node, the permission definition may vary depending on its type or service.
   */
  permissions?: { [key: string]: string };
  attachments?: Array<Attachment>;
  parentId?: string;
  notifications?: string;
  /**
   * true if the current user faved the node
   */
  favourite?: boolean;
  hasSubFolders?: boolean;
  deletedBy?: string;
  deletedDate?: string;
}
export namespace ArchiveNode {
  export type ServiceEnum =
    | 'library'
    | 'information'
    | 'events'
    | 'newsgroups'
    | 'directory';
  export const ServiceEnum = {
    Library: 'library' as ServiceEnum,
    Information: 'information' as ServiceEnum,
    Events: 'events' as ServiceEnum,
    Newsgroups: 'newsgroups' as ServiceEnum,
    Directory: 'directory' as ServiceEnum
  };
}
```
that was relatively OK if we ignore not needed  imports
now 
```typecript
import { Node } from './node';
import { Attachment } from './attachment';
import { ArchiveNodeAllOf } from './archiveNodeAllOf';

export interface ArchiveNode {
  deletedBy?: string;
  deletedDate?: string;
}
export namespace ArchiveNode {} 
```
All generated from same model 
```yaml
    ArchiveNode:
      allOf:
        - $ref: '#/components/schemas/Node'
        - type: object
          properties:
            deletedBy:
              type: string
            deletedDate:
              type: string
              format: date
```

So little bit annoying same/similar  error happen 
after few years in master
Maybe to test changes with one yaml file 
that cover all features  of open api spec

in attempt to minimize stupid regerssions  
so last comment of @amakhrov  is not correct any more because it look like 
generator is broken  
> * `allOf` without any `discriminator`: all properties from referenced schemas are cloned into the target interface.

**Comment by amakhrov** [comment] 2020-03-26 18:41
@topce thanks for bringing this up. Indeed support of allOf across typescript generators is inconsistent and incomplete atm.

> Maybe to test changes with one yaml file that cover all features of open api spec

Yep, that's something that I still plan to do (filed in this [issue](https://github.com/OpenAPITools/openapi-generator/issues/5335)) - decided to postpone till typescript examples cleanup by @macjohnny (which is planned to be done soon 4.3.0 release) to avoid redundant work.

> allOf without any discriminator: all properties from referenced schemas are cloned into the target interface.

It depends on a generator. I just tested typescript-axios and typescript-angular (using a version of 2_0/petstore-with-fake-endpoints-models-for-testing.yaml where I removed `discriminator`) - and they seems to emit valid model with all fields included.

**Comment by topce** [comment] 2020-03-27 07:29
@amakhrov 
Thank you for fast response.
Can you please provide example that is working for you ?

For me it does not work 

```yaml
    Node:
      type: object
      description: representation of a node
      properties:
        id:
          type: string
        type:
          type: string
        service:
          type: string
          enum:
            - library
            - information
            - events
            - newsgroups
            - directory
        name:
          type: string
        title:
          $ref: '#/components/schemas/i18nProperty'
        description:
          $ref: '#/components/schemas/i18nProperty'
        properties:
          type: object
          additionalProperties:
            type: string
        permissions:
          type: object
          additionalProperties:
            type: string
          description: >
            Representation of the permissions given to the user making the call.

            To know what are the permissions for the specific node, the
            permission

            definition may vary depending on its type or service.
        attachments:
          type: array
          items:
            $ref: '#/components/schemas/Attachment'
        parentId:
          type: string
        notifications:
          type: string
        favourite:
          type: boolean
          description: |
            true if the current user faved the node
        hasSubFolders:
          type: boolean
    ArchiveNode:
      allOf:
        - $ref: '#/components/schemas/Node'
        - type: object
          properties:
            deletedBy:
              type: string
            deletedDate:
              type: string
              format: date
``` 
Archive node does not include properties of node !?
```typescript
import { Node } from './node';
import { Attachment } from './attachment';
import { ArchiveNodeAllOf } from './archiveNodeAllOf';

export interface ArchiveNode {
  deletedBy?: string;
  deletedDate?: string;
}
export namespace ArchiveNode {} 
```

So I think it is broken.
It was working before but not anymore there is some regression there.

**Comment by topce** [comment] 2020-03-27 07:30
@amakhrov 
I was testing on master branch

**Comment by amakhrov** [comment] 2020-03-27 16:11
@topce oops. I realized I had a older docker image cached locally. After pulling latest image I see the same issue as you're describing.

**Comment by topce** [comment] 2020-03-27 19:23
@amakhrov 
no problem 
not sure when this regression happened
or how to fix it?
Do you know if it works any better for other TypeScript generators ?

**Comment by amakhrov** [comment] 2020-03-27 20:38
No idea, and I don't even have a prime suspect out of the typescript-related PRs merged since 4.2.3. I also consider a possibility that it was not a TS-specific PR at all.
I'll try to get some time on the weekend and investigate what's causing this

**Comment by topce** [comment] 2020-03-27 22:20
Thank you!

**Comment by amakhrov** [comment] 2020-03-28 22:26
Look like this was the breaking change: https://github.com/OpenAPITools/openapi-generator/pull/5526/files#diff-57d7532cf464a8d7c24aab4b22ceb993R1138

Current effect is:
- for model (Child) that is composed as  allOf on Parent and Model_AllOf, this `if` condition ensures Parent is treated as a parent in inheritance, even though it doesn't have a discriminator.

However, `getAllParentsName()` was not updated to follow the same logic, so `parent` and `allParents` are out of sync now (later should always be a superset of former). And typescript generators rely on `allParents`.
I'll make a PR to fix this

**Comment by digaus** [comment] 2020-04-04 19:04
Currently having the same issue. Glad to see it is already being worked on.

**Comment by topce** [comment] 2020-04-06 12:28
thank you @amakhrov it  is working now for angular typescript
even it generates less code because class is extended 
and not all properties are copied 
@wing328  maybe to accept this PR  it fix bug that was present for long time

**Comment by topce** [comment] 2020-04-15 14:12
hi @wing328 and @jimschubert 
any news on this one @amakhrov  fix one big problem 
why is still not merged !?

**Comment by wing328** [comment] 2020-07-05 15:41
@topce sorry completely missed this. Please PM via Slack if you still need help with this: https://join.slack.com/t/openapi-generator/shared_invite/enQtNzAyNDMyOTU0OTE1LTY5ZDBiNDI5NzI5ZjQ1Y2E5OWVjMjZkYzY1ZGM2MWQ4YWFjMzcyNDY5MGI4NjQxNDBiMTlmZTc5NjY2ZTQ5MGM

**Comment by topce** [comment] 2020-07-05 17:24
@wing328 no problem, latest stable is working OK  for me

**Closed** 2020-07-06 15:10 UTC
Labels: Client: TypeScript, Feature: Composition / Inheritance, Feature: OAS 3.0 spec support, Issue: Bug

**Comment by ypicard** [comment] 2022-03-15 23:49
Is this really fixed?

**Comment by MattiasMartens** [comment] 2022-09-09 13:57
I am seeing this too!

using openapigenerator 6.0.1, with generator "typescript".

the API is like this:

```
"IRBUserPermission": {
        "type": "object",
        "allOf": [
          {
            "$ref": "#/components/schemas/IRB"
          }
        ],
        "properties": {
          ...
        }
      }
},
"IRB": {
        "type": "object",
        "allOf": [
          {
            "$ref": "#/components/schemas/IRBBase"
          }
        ],
        "properties": {
          ...
        }
      },
"IRBBase": {
        "type": "object",
        "allOf": [
          {
            "$ref": "#/components/schemas/IRB"
          }
        ],
        "properties": {
          ...
        }
      },
```

In the generated types, the type of `IRBUserPermission` misses all the fields from `IRB` even though it has the fields of `IRBBase`.

**Comment by MattiasMartens** [comment] 2022-09-14 08:40
Created https://github.com/OpenAPITools/openapi-generator/issues/13417 to track
