### ISSUE TITLE
[BUG][Ruby] Using oneOf generated code has unexpected results

### ISSUE THREAD

**Issue by ssteeg-mdsol** [OpenAPITools/openapi-generator#3630] opened 2019-08-13 11:58 UTC
#### Bug Report Checklist

- [x] Have you provided a full/minimal spec to reproduce the issue?
- [x] Have you validated the input using an OpenAPI validator ([example](https://apidevtools.org/swagger-parser/online/))?
- [x] What's the version of OpenAPI Generator used?
- [x] Have you search for related issues/PRs?
- [x] What's the actual output vs expected output?
- [ ] [Optional] Bounty to sponsor the fix ([example](https://www.bountysource.com/issues/66123212-javascript-client-produces-a-wrong-object-for-a-string-enum-type-that-is-used-with-ref))

##### Description

When a `oneOf` is used, the generated model only includes one of the possible classes. Using the client, objects for all class types are forced into the same class, even if they're a different class. 

In the below example, if the API returns a `AuthenticationMonitor` MonitorResult object, the generated client forces it into the `SmokeTestMonitor` class type. This is a problem as it's the incorrect class type and as a result the model attributes are all `nil`.

###### Current output for the `AuthenticationMonitor` MonitorResult object:
```
...
@items=[#<ClientExample::SmokeTestResult:0x00007fb45220eaa0>]
...
```

###### Expected output for the `AuthenticationMonitor` MonitorResult object:
```
...
@items=[#<ClientExample::AuthenticationMonitorItems:0x00007fb45220eaa0 @result=true>]
...
```

##### openapi-generator version

4.1.0, seems to occur in every 4.x version. Haven't checked previous versions.

##### OpenAPI declaration file content or url

<details>
  <summary> OpenAPI spec</summary>

`AuthenticationMonitor` and `SmokeTestMonitor` are the same but the property name inside `items` is different
```yaml
openapi: 3.0.2
info:
  title: Example
  version: v1
paths:
  /endpoint:
    get:
      summary: Get All Monitors
      responses:
        '200':
          description: Successful operation.
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/Monitor'
components:
  schemas:
    Monitor:
      type: object
      properties:
        results:
          $ref: '#/components/schemas/MonitorResults'
    MonitorResults:
      oneOf:
        - $ref: '#/components/schemas/AuthenticationMonitor'
        - $ref: '#/components/schemas/SmokeTestMonitor'
    AuthenticationMonitor:
      type: object
      properties:
        items:
          type: array
          items:
            type: object
            properties:
              result:
                type: boolean
    SmokeTestMonitor:
      type: object
      properties:
        items:
          type: array
          description: Collection of smoke test result checks.
          items:
            type: object
            properties:
              passed:
                type: boolean
```
</details>

##### Command line used for generation

`openapi-generator generate -i <OPENAPI_SPEC> -g ruby -o <TEMP_DIR> -c <CONFIG_PATH>`

##### Steps to reproduce

1. Run the command to generate the Ruby client
2. Look at the 

##### Related issues/PRs

Maybe https://github.com/OpenAPITools/openapi-generator/issues/15 is related, but this issue is more specific to the Ruby client.

Another issue related to `oneOf` for the Ruby client is the generation of objects within a `response` schema. If you have the following OpenAPI spec, the class type gets generated as `ExampleClient::OneOfsimpleObjectcomplexObject`, and that class does not exist.

<details>
  <summary> OpenAPI spec snippet</summary>
Here is the spec:

```yaml
paths:
  /endpoint:
    get:
      summary: Get All Monitors
      responses:
        '200':
          description: Successful operation.
          content:
            application/json:
              schema:
                oneOf:
                  - $ref: '#/components/schemas/simpleObject'
                  - $ref: '#/components/schemas/complexObject'

components:
  schemas:
    simpleObject:
      type: object
      properties:
        simple_property1:
          type: string
    complexObject:
      type: object
      properties:
        complex_property1:
          type: string
        complex_property2:
          type: string
```
</details>

##### Suggest a fix

In https://github.com/OpenAPITools/openapi-generator/blob/master/modules/openapi-generator/src/main/resources/ruby-client/partial_model_generic.mustache#L49, the generated client only includes one option `Array<SmokeTestResult>`. I'm not sure about a specific fix, but has there been any Ruby-specific development into this area?

**Comment by autopp** [comment] 2019-08-18 07:22
@ssteeg-mdsol Thank you for the report. 
Does the following response reproduce this problem?
```json
[
  {
    "result": {
      // AuthenticationMonitor
      "items": [
        {
          "result": true
        }
      ]
    }
  },
  {
    "result": {
      // SmokeTestMonitor
      "items": [
        {
          "passed": true
        }
      ]
    }
  }
]
```

**Comment by autopp** [comment] 2019-08-18 07:28
@ssteeg-mdsol 
> ###### Expected output for the `AuthenticationMonitor` MonitorResult object:
> ```
> ...
> @items=[#<ClientExample::SmokeTestResult:0x00007fb45220eaa0 @result=true>]
> ...
> ```

And isn't the expected output in your description here?

```
...
@items=[#<ClientExample::AuthenticationMonitorItems:0x00007fb45220eaa0 @result=true>]
...
```

**Comment by autopp** [comment] 2019-08-19 00:59
This is not just a problem for Ruby, but for example Python.
A Python client generated with the same input contains the following code in `openapi_client/models/monitor_results.py`:
```python
class MonitorResults(object):
    """NOTE: This class is auto generated by OpenAPI Generator.
    Ref: https://openapi-generator.tech

    Do not edit the class manually.
    """

    """
    Attributes:
      openapi_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """
    openapi_types = {
        'items': 'list[SmokeTestMonitorItems]' # <- missing AuthenticationMonitorItems
    }
```

This looks like a problem with the Ruby client.

**Comment by ssteeg-mdsol** [comment] 2019-08-26 04:28
@autopp Sorry for the slow reply! My Gmail filters let me down 🙇 

You're right about the expected output, I will update the issue description. 

I believe the response you provided should reproduce the problem but will double-check this afternoon.

**Comment by ssteeg-mdsol** [comment] 2019-08-26 06:10
Confirmed that the response you provided reproduces the issue.

A response of
```yaml
[
  {
    "results": {
      // AuthenticationMonitor
      "items": [
        {
          "result": true
        }
      ]
    }
  },
  {
    "results": {
      // SmokeTestMonitor
      "items": [
        {
          "passed": true
        }
      ]
    }
  }
```

results in the following (from the ruby console):
```rb
items[0].results.items
# => [#< ClientExample::SmokeTestResult:0x00007ff1261bb380>]
items[0].results.items.first.passed
# => nil
items[0].results.items.first.result
Traceback (most recent call last):
        1: from (irb):11
NoMethodError (undefined method `result` for #< ClientExample::SmokeTestResult:0x00007ff1261bb380>)
Did you mean?  rescue

items[1].results.items
# => [#< ClientExample::SmokeTestResult:0x00007f98f4b191f0 @passed=true>]
items[1].results.items.first.passed
# => true

**Comment by ssteeg-mdsol** [comment] 2019-09-05 07:31
@autopp Do you have ideas about how or where the logic to handle `oneOf` could be implemented? Is there anything I can do to help fix the issues? Sorry for the vague questions, I'm not really sure where to start. 😕

**Comment by Frontrider** [comment] 2019-10-15 08:21
It's a general issue with the generator. Java has the same issue, no fix has been provided so far.

**Comment by autopp** [comment] 2019-10-15 14:40
@ssteeg-mdsol Sorry for the late reply.
As @Frontrider comments, this seems to be a general generator problem.
Unfortunately I still haven't been sure where to start.

**Comment by Frontrider** [comment] 2019-10-15 16:42
my start was to look into the java generator code, and I found absolutely no support for it in the example generator. i think it is just unimplemented.

**Comment by jfeltesse-mdsol** [comment] 2020-03-25 14:33
I tried to take a stab at it in #5706

**Closed** 2020-11-23 14:43 UTC
Labels: Client: Ruby, Issue: Bug
