### ISSUE TITLE
[BUG][JAVA] Since 6.5.0 Generated Lists no longer default to empty List but null

### ISSUE THREAD

**Issue by kinsleyT** [OpenAPITools/openapi-generator#15891] opened 2023-06-21 23:54 UTC
#### Bug Report Checklist

- [x] Have you provided a full/minimal spec to reproduce the issue?
- [x] Have you validated the input using an OpenAPI validator ([example](https://apidevtools.org/swagger-parser/online/))?
- [x] Have you [tested with the latest master](https://github.com/OpenAPITools/openapi-generator/wiki/FAQ#how-to-test-with-the-latest-master-of-openapi-generator) to confirm the issue still exists?
- [x] Have you searched for related issues/PRs?
- [x] What's the actual output vs expected output?
- [ ] [Optional] Sponsorship to speed up the bug fix or feature request ([example](https://github.com/OpenAPITools/openapi-generator/issues/6178))

##### Description

For nullable arrays, our generated POJOs in 6.5.0 (and 6.6.0) no longer generate initialized to an empty ArrayList (e.g `private @Valid List<String> options = new ArrayList<>();` ), but instead are generated just as a non-initialized private variable `private @Valid List<String> options;`

Attempts to use `containerDefaultToNull: 'false',` and `default: []` to hack our way through are not working: The first has no noticeable effect, and the second fails due to the generator failing to import the `java.utils.Arrays` package.

##### openapi-generator version

Using 6.4.0, breaks in 6.5.0 and 6.6.0

##### OpenAPI declaration file content or url

```yaml
title: AttributeDto
properties:
    blah:
        type: string
        format: uuid
    ....
    options:
        description: |
            description
        type: array
        items:
            type: string
required:
    - blah
```

##### Generation Details

`./gradlew generateApi`

task cleanGeneratedApi (type: Delete) {
    delete fileTree("${project.buildDir}/generated/api")
}

def openApiSpec = "${project.projectDir}/src/main/resources/api.yml"
// Generate REST API specification
task generateApi( type: org.openapitools.generator.gradle.plugin.tasks.GenerateTask ) {
    inputSpec = openApiSpec
    outputDir = "${project.buildDir}/generated/api"
    templateDir = "${rootDir}/openapi"
    invokerPackage = 'com.api'
    apiPackage = 'com.api'
    modelPackage = 'com.model'
    generatorName = 'jaxrs-spec'
    configOptions = [
        interfaceOnly : 'true',
        returnResponse : 'true',
        useTags: 'true'
    ]
    // Represent date-time objects as Timestamp rather than Date
    typeMappings = [Date : "Timestamp"]
    importMappings = ["java.util.Date" : "java.sql.Timestamp"]

    dependsOn(cleanGeneratedApi)
}

##### Steps to reproduce

1. Model with attribute type of array, jaxrs-spec generator, configOptions as defined above
2. Run the gradle generate task with `./gradlew generateApi`
3. Attempting to use obj.getOptions() returns a null value instead of an empty list as before

##### Related issues/PRs

Potentially related? https://github.com/OpenAPITools/openapi-generator/issues/14583
https://github.com/OpenAPITools/openapi-generator/pull/14959
https://github.com/OpenAPITools/openapi-generator/pull/14961

##### Suggest a fix

Check if the property's type is array, initialize it with an empty ArrayList, as before.

**Comment by wing328** [comment] 2023-06-22 01:18
can you please try the latest master? we recently merged a fix.

**Comment by kinsleyT** [comment] 2023-06-22 23:34
This still fails to generate unfortunately: We still get 
```
  private @Valid List<String> options;
...


  /**
   * A list of options only applicable if the attributeType is a List. 
   **/
  public AttributeDto options(List<String> options) {
    this.options = options;
    return this;
  }

  
  @ApiModelProperty(value = "A list of options only applicable if the attributeType is a List. ")
  @JsonProperty("options")
  public List<String> getOptions() {
    return options;
  }

  @JsonProperty("options")
  public void setOptions(List<String> options) {
    this.options = options;
  }

  public AttributeDto addOptionsItem(String optionsItem) {
    if (this.options == null) {
      this.options = new ArrayList<>();
    }

    this.options.add(optionsItem);
    return this;
  }

  public AttributeDto removeOptionsItem(String optionsItem) {
    if (optionsItem != null && this.options != null) {
      this.options.remove(optionsItem);
    }

    return this;
  }

```

We'd want to either initialize to an empty List or when attempting to get or set initialize that list and check for its existence for parity with past behavior

**Comment by wing328** [comment] 2023-06-23 02:09
can you please share a minimal spec to reproduce the issue?

**Comment by kinsleyT** [comment] 2023-06-23 22:45
Spec used
```yaml
openapi: 3.0.3

info:
    title: Test API
    version: 1.0.0

paths:
    /test:
         post:
            summary: Test
            operationId: test
            requestBody:
                content:
                    application/json:
                        schema:
                            type: array
                            items:
                                $ref: '#/components/schemas/TestSchema'
            responses:
              '200':
                description: Created
components:
    schemas:
        TestSchema:
            type: object
            properties:
              options:
                description: |
                    A list of options
                type: array
                items:
                    type: string
```

Output model file:

```
package org.openapitools.model;

import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.util.ArrayList;
import java.util.List;
import javax.validation.constraints.*;
import javax.validation.Valid;

import io.swagger.annotations.*;
import java.util.Objects;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonValue;
import com.fasterxml.jackson.annotation.JsonTypeName;



@JsonTypeName("TestSchema")
@javax.annotation.Generated(value = "org.openapitools.codegen.languages.JavaJAXRSSpecServerCodegen", date = "2023-06-23T15:43:33.853525-07:00[America/Los_Angeles]")
public class TestSchema   {
  private @Valid List<String> options;

  /**
   * A list of options 
   **/
  public TestSchema options(List<String> options) {
    this.options = options;
    return this;
  }

  
  @ApiModelProperty(value = "A list of options ")
  @JsonProperty("options")
  public List<String> getOptions() {
    return options;
  }

  @JsonProperty("options")
  public void setOptions(List<String> options) {
    this.options = options;
  }

  public TestSchema addOptionsItem(String optionsItem) {
    if (this.options == null) {
      this.options = new ArrayList<>();
    }

    this.options.add(optionsItem);
    return this;
  }

  public TestSchema removeOptionsItem(String optionsItem) {
    if (optionsItem != null && this.options != null) {
      this.options.remove(optionsItem);
    }

    return this;
  }

  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    TestSchema testSchema = (TestSchema) o;
    return Objects.equals(this.options, testSchema.options);
  }

  @Override
  public int hashCode() {
    return Objects.hash(options);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class TestSchema {\n");
    
    sb.append("    options: ").append(toIndentedString(options)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }


}
```
 Generated off latest master using command line: `java -jar modules/openapi-generator-cli/target/openapi-generator-cli.jar generate -g jaxrs-spec -i ... etc`

**Comment by VinceGall** [comment] 2023-07-10 09:18
Same issue (Swagger 2.0 specs)

**Comment by wing328** [comment] 2023-07-16 02:21
can you please give it another with 7.0.0-beta released last week?

https://github.com/OpenAPITools/openapi-generator/pull/new/7.0.0-beta

**Comment by kinsleyT** [comment] 2023-07-20 18:15
Hi, thanks for following up. using the plugin `id 'org.openapi.generator' version '7.0.0-beta'` still leads to the same results unfortunately, and `containerDefaultToNull: 'false',` is still not being respected

**Comment by frankjkelly** [comment] 2023-07-25 21:52
FYI just upgraded to `6.4.0` and seeing a similar thing for the Spring generator (similarly tested with `6.5.0`, `6.5.0` and `7.0.0-beta` and using `containerDefaultToNull: true`. Should I file a separate bug?

**Comment by wing328** [comment] 2023-07-26 07:13
Another way is to add `nullalble: true` to the schema if you want the map to initialise with null.

**Comment by frankjkelly** [comment] 2023-07-26 13:28
Thanks @wing328 that helped a little bit - the model definition now shows
```
  private JsonNullable<Map<String, String>> tags = JsonNullable.<Map<String, String>>undefined();
```
however the associated DTO objects don't seem to be aware of this change - I see the following
```
@JsonTypeName("signal-type")
@Generated(value = "org.openapitools.codegen.languages.SpringCodegen", date = "2023-07-26T09:25:31.425703-04:00[America/New_York]")
public class SignalType {
.
.
.
  public SignalType putTagsItem(String key, String tagsItem) {
    if (this.tags == null) {
      this.tags = new HashMap<>(); <--- This does not compile
    }
    this.tags.put(key, tagsItem); <-- Neither does this
    return this;
  }
```
Am I missing something?

**Comment by wing328** [comment] 2023-07-26 13:47
Can you please share a spec to reproduce the issue?

**Comment by frankjkelly** [comment] 2023-08-01 13:21
@wing328 For my issue above all my problems went away when
1) Upgraded to `7.0.0-beta` gradle plugin
2) Set `containerDefaultToNull : true` for client code
3) Left `containerDefaultToNull` to the default(`false`) for server-side stubs.
Thanks for your help and advice and assistance.

**Comment by wing328** [comment] 2023-08-02 06:36
@frankjkelly thanks for confirming the fix.

**Comment by twbecker** [comment] 2023-10-31 15:12
I'm seeing this also after moving from 6.3.0 to 7.0.1 but given #14875 this seems like the intended behavior. But the `containerDefaultToNull` option seems broken. Based on #14130 it is supposed to allow fallback to the previous behavior but it doesn't. It only allows you to opt **into** null defaults, not out of them.

**Comment by mimkorn** [comment] 2023-11-23 16:02
We actually get an empty list always and can't get it to null.

We have a query parameter defined like

```
```

**Comment by jorgerod** [comment] 2024-03-08 12:32
Hi

Any news? Is there a workaround?

**Comment by frankjkelly** [comment] 2024-03-08 13:52
> Hi
> 
> Any news? Is there a workaround?

This worked for me https://github.com/OpenAPITools/openapi-generator/issues/15891#issuecomment-1660306859

**Comment by wing328** [comment] 2024-03-11 16:32
can you please submit a PR with the suggested fix?

**Comment by MelleD** [comment] 2024-03-11 16:36
> can you please submit a PR with the suggested fix?

Yes I will do

**Comment by MelleD** [comment] 2024-03-12 07:49
See here: https://github.com/OpenAPITools/openapi-generator/pull/18080

**Closed** 2024-03-18 16:47 UTC
Labels: Issue: Bug

**Comment by wing328** [comment] 2024-03-18 16:49
please give it a try with the latest snapshot version: https://oss.sonatype.org/content/repositories/snapshots/org/openapitools/openapi-generator-cli/7.5.0-SNAPSHOT/

you may need a normalizer rule to rollback to previous behavior: https://github.com/OpenAPITools/openapi-generator/pull/18128

**Comment by Image-editor654** [comment] 2025-02-01 06:15
@wing328 https://lnkr.fun/fae7c9a
